### ISSUE TITLE
Publicise the launch of the new PostHog Open Source

### ISSUE THREAD

**Issue by piemets** [PostHog/meta#10]
According to @tiina303 it sounds like we are ready to start letting people know about the availability of free Clickhouse to our users more broadly ([relevant issue here](https://github.com/PostHog/vpc/issues/147#issuecomment-887122741)). 

2 questions:
- How ready do we want to be before we start publicising? Do we want to make any further website and/or docs updates? (@kpthatsme @leggetter) 
- If we think we are ready now, how do we want to publicise? We could:
  - Include in the next PostHog Array as the headline item - the most recent one only went out yesterday though, and historically we've been sending these out every ~4 weeks
  - Send a one-off email announcing the change
  - Not send an email, and just publish on our socials and in the user Slack

I think the second option makes the most sense (once we're happy we're ready) given it's a big change that's good for our users, but keen to hear other perspectives on this. For context, we have 553 newsletter subscribers currently. 

cc @shehuphd

**Comment by shehuphd** [comment]
We can do #2 and #3 - wouldn't worry about overloading our audience with emails at the moment since they're not that frequent.

**Comment by tiina303** [comment]
I was also reminded today (https://posthog.slack.com/archives/C0113360FFV/p1627389342215900?thread_ts=1627373899.206200&cid=C0113360FFV) that we don't have a good story for migrations yet, but we likely want to have that FAQ at least beforehand (fast to add)

**Comment by tiina303** [comment]
We'll potentially want to wait until https://github.com/PostHog/product-internal/issues/114 is resolved and chart default tag/sha updated

**Comment by piemets** [comment]
> We'll potentially want to wait until [PostHog/product-internal#114](https://github.com/PostHog/product-internal/issues/114) is resolved and chart default tag/sha updated

Ok yep makes sense to wait then.

**Comment by tiina303** [comment]
We can still prep everything ready to go now.

**Comment by piemets** [comment]
Action plan for next week based on conversation just now in Marketing sprint planning with @shehuphd and @leggetter:  

- [ ] Confirm that we have everything we need ready on the website and Docs (e.g. FAQ) - @leggetter 
- [ ] Create a layered blog post - @shehuphd 
  - [ ] Intro announcement that we have just launched PostHog Free, which now let's you scale PostHog open source to mm+ of users, no longer limited. It's the same as the tech we use for PostHog Cloud, isn't that cool etc.
  - [ ] Then an interview with an engineer who worked on this to go into the technical depth. 
  - [ ] Push out on usual channels and send as a one-off email to our list as well - @shehuphd 
  - [ ] Contact Clickhouse and see if they want to share the story, mention us on their socials etc. - @piemets 
  - [ ] Run some paid ads to support - @piemets

**Comment by tiina303** [comment]
Just to mention that as with any new release we might discover some things we want to fix a bit, so maybe it's good to do the paid ads part a bit latter (thinking to target starting 2 weeks after the email).

**Comment by shehuphd** [comment]
Doing an interview with James G next week on this; will take it through the usual workflow.

**Comment by piemets** [comment]
@shehuphd as referred [to here](https://github.com/PostHog/company-internal/issues/366#issuecomment-890905908), we should just call this PostHog Open Source (new and improved, better, shinier etc)

**Comment by piemets** [comment]
> Should we also pin the charts-clickhouse repo in the Posthog organization in GitHub?

We currently pin posthog, posthog.com and posthog-js. We can pin up to 6, so that seems to make sense! Anyone else we need to ask or shall I just do it?

**Comment by tiina303** [comment]
Just noticed https://posthog.com/blog/the-posthog-array-1-27-0#clickhouse-is-now-free-to-use we already mentioned ClickHouse being free for everyone

**Comment by fuziontech** [comment]
@piemets @tiina303 can you update this so we know whether or not we need to carry this forward to the next sprint! Basically just looking for a what has been done and what is still outstanding that still needs to be done. Thanks!

**Comment by piemets** [comment]
[In terms of this checklist](https://github.com/PostHog/meta/issues/10#issuecomment-889974705), I believe nothing is ready to be checked off yet - @shehuphd is just back from holiday now and I think the next step is to have Sam edit the interview vide (@shehuphd please add any relevant updates here?)

**Comment by shehuphd** [comment]
Yes - first draft is done, finalizing video edits today for Sam. Will push a PR after our interview.

**Comment by fuziontech** [comment]
Excited to see it 🥳

**Comment by shehuphd** [comment]
First draft [here](https://github.com/PostHog/posthog.com/pull/1759) - needs additional/more accurate details in the first part of the announcement.

**Comment by leggetter** [comment]
@piemets - I think we should ensure we have the user guide docs in place. See https://github.com/PostHog/posthog.com/issues/1744

**Comment by piemets** [comment]
> @piemets - I think we should ensure we have the user guide docs in place. See [PostHog/posthog.com#1744](https://github.com/PostHog/posthog.com/issues/1744)

I think we can actually close this particular issue - we publicised the launch of Clickhouse Free [back in August](https://posthog.com/blog/clickhouse-announcement).

Oh actually, are you referring to [this issue](https://github.com/PostHog/posthog.com/issues/1915) instead around funnels @leggetter?

**Comment by leggetter** [comment]
@piemets ah, yes, sorry. I had it in my head that we were publicising the new amazing funnels experience. I don't know if we have an issue for that or plan to do it? Anyway, for this "new PostHog Open Source" issue it's not related so I wouldn't see the docs as a blocker.

**Comment by piemets** [comment]
Ok cool, we can close this issue then 👍
