### ISSUE TITLE
Offsite: Aruba March 2023 retro

### ISSUE THREAD

**Issue by KendalHall** [PostHog/meta#106]
**Summary of survey:** 
**How satisfied were you with the event overall?**

- 91% said they were very satisfied with the event. There seemed to be one outlying result that was not positive, but the overwhelming consensus is that it was a successful event.

**How relevant and helpful do you think it was for your job?**

- 60.9% said the event was very relevant for their job.

**What were your key take aways from this event?**
- The main positives were getting to know the team better and the hackathon.

**How satisfied were you with each aspect of the trip?**
- The majority were happy with the accommodation, merch, catamaran trip (minus one outlier), posties/final meal, hackathon and general itinerary.
- However, there was more varied feedback about the food offered, the OKR session, interview with a founder, values session and the venue for activities. If anyone who scored lower for these aspects would like to expand further, please feel free!

**Which sessions did you find most relevant?**
- The hackathon and interview with a founder was seen to be generally very relevant for everyone.
- The feedback was varied again for the other sessions, 13% found the values session not relevant at all, and 8% for the OKR session.

**Any additional comments regarding the sessions or overall itinerary?**
- There seemed to be a general trend that the values session and the interview with a founder can be less relevant for team members that have been with Posthog longer as there are less new insights.
- There were a few comments suggesting that the OKRs should have been discussed outside of the offsite as it didn’t allow for cross-team discussions as much.

**How well did you feel you knew other members of the team before the offsite?**
- This question garnered very varied feedback from everyone as we had very new colleagues and people who have been with PostHog for a while, but the result was that nearly everyone felt that they got to know the team better as a result of the offsite.
- There was some good feedback suggesting that a 1/1 breakfast with someone not on your team could also help get to know others better, and could be implemented next time.

**Any overall feedback for the event? What went well, what could have been better?**
- One piece of feedback that was echoed by a few people was the quality of the wifi in the resort was not strong enough to conduct the hackathon properly.
- People overall were appreciative of the less crammed itinerary compared to other offsites so it gave people more time to relax and mingle.
- The climate of Aruba was preferred, and there are requests to do another warm destination next time.
- Overall, the majority said this was the best offsite yet, and it has made them more excited for the next one.

**Comment by joethreepwood** [comment]
Thanks for this! 

I personally had a lovely time, but I'm curious about the negative response and if there are any actions we can take off the back of that, or if we feel we can discount it complete as an outlier?

**Comment by postgrace** [comment]
Here is the [budget vs. actuals breakdown](https://docs.google.com/spreadsheets/d/1PYbJY0v8c7c8qbFfJmXIuLozGhl0f4QSudTYvu74s-c/edit?usp=sharing):

- We came in roughly $12,000 under budget
- Total per head cost was $5,087.51
- Airfare was a bit more than expected with folks flying from Europe
- We spent a bit extra on ground transportation, factoring in Ubers and taxi rides
- Team outings was a bit over due to the hike and our night out at the club 💃

**Comment by neilkakkar** [comment]
Forgot to add this in the survey: I thought posties in Iceland was a lot more fun & interesting than in Aruba, and I missed that. I think a combination of fun posthog related group activity (like jeopardy) followed by the awards made it a lot more fun. Also being able to appreciate everyone, clap for them, etc. etc. which couldn't exactly happen in the fancy restaurant 😅 .

Also, the actual awards this time in Aruba were brilliant, much nicer than the certificates :D
