### ISSUE TITLE
Messaging: Session replay upsell campaign

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#109]
### Context
@simfish85 and I want to run a test of upselling a targeted portion of users who are engaged with PostHog but _not_ using session replays, to use session replays. It'll be a short flow, targeting a custom segment that we've specified together. 

### Goal
Getting these users to enable, or engage with session replay as a feature. 

We'll track open and click-through rates as normal, but will export the segment back out of Customer.io and into Pocus to measure activation rates and any revenue impact. 

### Format
Email, via Customer.io. 

### Audience / Targeting
We've begun with a segment of 915 users identified by CS who are paying users that have not activated session replay. 

We're further narrowing this segment to focus on users who are currently actively engaged. Users must have completed the onboarding flow in the last 30 days, and have logged in in the last 14 days. 

### Resources, timeline, responsibilities

- [x] Simon to create the initial list
- [x] Joe to draft the initial content
- [x] Joe to build the emails 

### Requested input
Ideally we would get some dev assistance with this PR - https://github.com/PostHog/posthog/issues/15608 - so that we can most effectively link users to a very simple, direct modal to enable recordings. So, that's one ask. 

Failing that, we'd just have to link to the settings page and trust that users can find the option on that very long page. 

### Previews
[Drafts.](https://docs.google.com/document/d/1zfDsHlXnAZIpcexxVGCRBUtvXVPf6NILnukLv40mA_0/edit?usp=sharing) 

Coming soon.

**Comment by joethreepwood** [comment]
Good news/Bad news: We aren't immediately able to filter this campaign to focus on users who have completed the onboarding flow within the last 30 days because Customer.io doesn't support this. The list is small enough, however, that it shouldn't be a blocker to progress and, for future tests in this direction I've updated the onboarding flow to add a new `onboarding_completed_once: true` attribute whenever someone exits it.

**Comment by joethreepwood** [comment]
Additionally, going to use `app.posthog.com/replays` as a CTA, instead of settings. That page has a call-out for the modal which means it can function better as a place to send people.

**Comment by joethreepwood** [comment]
@simfish85 

There are two options to consider here, in terms of layout and approach across the three emails. The first is more of a marketing email, with a bit more design. The second is presented to look much more like a direct email from you. 

Do you have a preference? Or we could A/B test them across the campaign. 

<img width="767" alt="Screenshot 2023-05-24 at 14 41 49" src="https://github.com/PostHog/meta/assets/84011561/f3e4650a-7304-4eb3-96e5-352a0e946243">

<img width="839" alt="Screenshot 2023-05-24 at 14 41 10" src="https://github.com/PostHog/meta/assets/84011561/887df131-0429-4e51-9b64-8bf22eced280">

**Comment by joethreepwood** [comment]
Quick screenshots below for approval. All emails will look like they come from @simfish85 and replies will go to him. I've set a goal on the campaign: Generate a 'recording analyzed' event within 2 weeks of open.

One thing to note @simfish85 is that, of the list of 900ish users you shared, less than 300 of them match the criteria of also having logged in over the last 14 days. So each variation for each message will only get around 115 users in it, vs. the advised 500 minimum. 

We can push forth as-is, but we may want to consider dropping the 14 day criteria to get a better result and a more statistically relevant read. 

@simfish85 let me know what you think and, once I had a thumbs up, I'll set these to send over a 5-day period. 

### Email one: 
<img width="594" alt="Screenshot 2023-05-25 at 13 28 56" src="https://github.com/PostHog/meta/assets/84011561/80bd741a-6e57-4f77-9714-1df70234b144">

<img width="817" alt="Screenshot 2023-05-25 at 13 28 47" src="https://github.com/PostHog/meta/assets/84011561/c1019954-3e64-421f-a493-42d25e48181b">

### Email two
<img width="550" alt="Screenshot 2023-05-25 at 13 28 18" src="https://github.com/PostHog/meta/assets/84011561/e237118a-0d62-4c09-8e9c-51135b51b400">

<img width="894" alt="Screenshot 2023-05-25 at 13 28 35" src="https://github.com/PostHog/meta/assets/84011561/043c08d9-305b-4f94-a27e-63850f2ae36f">

### Email three
<img width="533" alt="Screenshot 2023-05-25 at 13 27 10" src="https://github.com/PostHog/meta/assets/84011561/093e422f-0b2a-46b3-8b35-72fa6216cfb6">

<img width="763" alt="Screenshot 2023-05-25 at 13 25 11" src="https://github.com/PostHog/meta/assets/84011561/aa0b087e-267d-4c7f-b45c-e6bc26f4e446">

**Comment by joethreepwood** [comment]
(there's no automation set up for the sticker promise btw, so we'd have to handle manually this time)

**Comment by andyvan-ph** [comment]
One email is fair enough, two is on the line, three feels excessive, especially over a five-day period. I get people can opt out whenever, but I feel strongly we shouldn't reach a point where people feel the need to do so. Most people will just block us rather than opt out.

**Comment by joethreepwood** [comment]
> One email is fair enough, two is on the line, three feels excessive, especially over a five-day period. I get people can opt out whenever, but I feel strongly we shouldn't reach a point where people feel the need to do so. Most people will just block us rather than opt out.

Agree with the time period on reflection. @simfish85 How would you feel if we scheduled this over a 10-day period instead? Like a Monday/Friday/Friday cadence. 

> Can we personalise the 'Hey there' to 'Hey Joe' ?

Unfortunately, it doesn't seem like we pass name information to Customer.io, so we can't do this.

**Comment by corywatilo** [comment]
> Have you tried PostHog's session replays yet?

Would probably change this since, as an analytics company, we _should know_ if they have/haven't tried it. (In fact we do, but _they_ may wonder.)

Instead something like, "I noticed you haven't tried session replay yet."

**Comment by simfish85** [comment]
@joethreepwood fine with the 10-day cadence!  Let's get it going

**Comment by joethreepwood** [comment]
Scheduled: 

Email 1: Monday 5th June
Email 2: Friday 9th June
Email 3: Friday 16th June

**Comment by joethreepwood** [comment]
The third email isn't sent yet, but a quick look at the results for 1 and 2 suggests that the more personal, non-designed version performs slightly better. Will loop back in a week with full results.

**Comment by joethreepwood** [comment]
Results are in:
- Average 55% open rate across all emails vs 3 total unsubscribes
- 7% conversion per email: 41/200 people tried replays for the first time
- 8 people clicked a link to book a call

 The personal style generated almost _twice_ as many conversions, except for the last email in the sequence.
