### ISSUE TITLE
Improving the startup program

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#112]
### Context
A goal for marketing is to get 200 orgs signed up to [the startup program](https://posthog.com/startups) by end of Q2. We're currently at 94, so it's extremely likely we'll miss this goal. 

As a result, I'm planning some changes to the program in order to drive growth, make it easier to run and help us perform better in Q3. Documenting here because many of these changes will be invisible (off GitHub) otherwise.

### Planned changes

Over the next sprint or two, I'm planning to...

- [x] **Create a monthly newsletter** for users within the program, highlighting the Startup Spotlight, sharing new content, requesting feedback, promoting office hours, and more. The aim here is to add value, improve visibility and provide an opportunity to promote awareness.
- [x] **Create a referral program** whereby, if successful applicants refer in another startup we accept, we give them both an extra $5k PostHog credit. Objective is to increase word of mouth growth. 
- [x] **Template and invite word of mouth.** We've moved the process to Zapier now, which means we can update the messaging there to support all these other points. We'll also invite users to send us pics of their merch, so we can invite WOM.
- [x] **Gather testimonials, improve the page.** I’ll take a pass at the `/startups` page to improve the copy, add some more spotlights and testimonials. It can't hurt to put a best foot forward. 
- [x] **Start a case study.** I'll secure a case study with a user from the program, to feature on the startup page. The focus will be on demonstrating the value of the program and providing tips for new applicants.
- [x] **Write a program comparison.** I'll create a comparison of the various startup programs run by Amplitude, Mixpanel, etc., to demonstrate the strengths of ours. This could sit as a table on the page, or as a longer blog post.

**Comment by andyvan-ph** [comment]
> Write a program comparison. I'll create a comparison of the various startup programs run by Amplitude, Mixpanel, etc., to demonstrate the strengths of ours. This could sit as a table on the page, or as a longer blog post.

For SEO reasons, I'd prefer if you avoid doing a blog, so table on the page would be ideal.

**Comment by joethreepwood** [comment]
Closing this out. The site and template stuff is all done, and I've opened discussions with Bugprove for a case study to come soon.
