### ISSUE TITLE
Newsletter [Mega-ish Issue]

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/meta#115]
**Goal:**
- Scale the newsletter to thousands of engaged subscribers

**Metrics:**
- Subscribers – Currently at 1,370. Stretch goal is to reach ~2,500, which equates to ~12 new subs per day.
- Post views – No goal here, but posts should reach more views than recipients
- Open rate – 30-day open rate should be above 40% at a minimum, ideally in mid-40s

**Growth tactics:**

- [x] Increase post frequency to at least every two weeks 
- [x] Start posting James CEO diaries (old and new) directly to newsletter
- [ ] Guest posts / trading with other newsletters / startups (open to suggestions here)
- [x] ~Auto-plug newsletter on James' Twitter threads (doing, already working)~
- [x] Convert old newsletter posts to threads + auto plug
- [x] Try and get recommendations from other Substacks (in progress)
- [x] Paid sponsorships in other newsletters (In Progress thanks to @ivanagas)
- [x] Paid ad campaigns on Twitter and LinkedIn

**Upcoming issues & ideas:**

- [x] A complete guide to A/B testing
- [x] What motivates me as a CEO (re-purposed James blog)
- [x] VC is a tool, not a religion (re-purposed James blog)
- [ ] How and when to pivot your startup
- [ ] The ultimate guide to product metrics ([1](https://posthog.com/blog/b2b-saas-product-metrics), [2](https://posthog.com/blog/product-health-metrics), [3](https://posthog.com/blog/churn-rate-vs-retention-rate))
- [x] How to hire great product engineers ([1](https://staysaasy.com/leadership/2022/11/06/traits-you-can-change-and-traits-you-cant.html), [2](https://posthog.com/blog/posthog-first-five), [3](https://posthog.com/blog/early-stage-startup-hiring-strategy), [4](https://posthog.com/blog/what-to-ask-in-interviews))
- [ ] How to build something people want ([inspired by James](https://posthog.com/blog/making-something-people-want))
- [x] How to measure product-market fit (in progress)
- [ ] The best of Paul Graham's essays
- [ ] x more lessons we've learned about product-market fit
- [ ] User Psychology 101: What / How your users really think
- [ ] How to ask open-ended questions / Get users to tell you their deep dark desires
- [x] What we've learned about hiring for startups
- [ ] All the signs of product market fit
- [x] How to ask good product questions (in progress)

**Comment by joethreepwood** [comment]
- We could invite PostHog for Startups members to submit things (maybe a few hundred words). Or we could select a handful of people from that program and ask CEOs for comments on what we're talking about, which would give us an opportunity to tag them in tweets and such, maybe get some RTs and reach?

- One tactic which Pragmatic engineer does which I also like is doing one 'public/free' issue which is posted, in full, on LinkedIn. Could be worth trying, as an incentive to drive sign-ups.

**Comment by joethreepwood** [comment]
It would also be good to _maybe_ free ourselves up to do a shorter, more ad-hoc style newsletter when the opportunity strikes. If a topic comes along which we can comment on, maybe throwing together a quick 'Our take on: X' newsletter could help force us into a current conversation and get some more traction. Not something we'd want to do vey often, as the cadence and quality should be maintained - but possibly valuable.

**Comment by joethreepwood** [comment]
Also, what about running a short survey, or request for comments at the end of each newsletter - and then surfacing the results on Twitter/LinkedIn. Another way to give us a bit of material to use on social to drive attention. 

A sticky post or something in /Community (and maybe a nav element) would also be good low hanging fruit.

**Comment by andyvan-ph** [comment]
> * We could invite PostHog for Startups members to submit things (maybe a few hundred words). Or we could select a handful of people from that program and ask CEOs for comments on what we're talking about, which would give us an opportunity to tag them in tweets and such, maybe get some RTs and reach?

Not so keen on this as I'm not confident about the quality of contributions, but could be persuaded.

> One tactic which Pragmatic engineer does which I also like is doing one 'public/free' issue which is posted, in full, on LinkedIn. Could be worth trying, as an incentive to drive sign-ups.

Our newsletter is free already, though, whereas his is paid.

> Also, what about running a short survey, or request for comments at the end of each newsletter - and then surfacing the results on Twitter/LinkedIn. Another way to give us a bit of material to use on social to drive attention.

Yeah, not sure about the best execution, but I like this. We get decent engagement on polls for the newsletter atm, so might be something in this.
