### ISSUE TITLE
RFC: PostHog for Startups in the sign-up flow

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#116]
This is a quick RFC to discuss something that came up in a recent Marketing brainstorm. 

We'd normally just PR it in, but wanted a quick alignment with Growth (CC @raquelmsmith) to think about the best way to do it and because most of the proposed change would happen off-GitHub (and therefore invisibly).  

Also tagging @camerondeleone and @simfish85 as FYI

## Currently...

<img width="966" alt="Screenshot 2023-07-10 at 15 28 19" src="https://github.com/PostHog/meta/assets/84011561/4a914a85-03cd-4c80-bfa2-4eecf29c0164">

At the moment, when signing up you see this option for telling us about who you are.

## Proposal...

What we're proposing is that we:

- Change 'Executive' to 'Founder' because it sounds a little less corporate
- We create an event which fires when someone signs up as a Founder

Having such an event as this would: 

- Enable us to very directly identify users who are founders and startups, which would be handy for segmentation
- Enable us to immediately send an email to these users informing them about the PostHog for Startups program and referral program

This would in turn address the problem that the PostHog for Startups program is currently quite hidden and difficult to find across the site.

**Comment by joethreepwood** [comment]
I don't have a strong feeling on that, though I'm unsure the value in keeping 'Executive' and what we'd use that for?

**Comment by simfish85** [comment]
I'd add Founder and change Executive (too corporate) to Leadership (which will help us differentiate CPO, CTOs who are non founders - useful for the CS team)

**Comment by joethreepwood** [comment]
As long as introducing more options is useful 👌

**Comment by raquelmsmith** [comment]
Fine with this, though there was also a request to add "Marketing" as an option, so we'd be adding two more options, at which point the list is feeling fairly long. Could combine CS & Sales, or just leave Marketing out (those people just fall into "Other"). 

Summary of field usage:

![image](https://github.com/PostHog/meta/assets/18598166/36b63176-e836-435f-9148-5f7baf4c9d61)

**Comment by joethreepwood** [comment]
I'd say leave marketing out. Will try and add this to my to-do list 👌

**Comment by simfish85** [comment]
Please can we keep marketing in as an option?  We use it in ICP scoring and evaluating prospects as it's a strong indicator that someone might struggle with PostHog, which changes our approach to demos etc.

**Comment by andyvan-ph** [comment]
As per @simfish85, I had a separate issue where adding Marketing was suggested: https://github.com/PostHog/meta/issues/113

I think there's a strong case for it:

1. Because of the GA4 work – would be good to know who we're capturing
2. Our plans to add website analytics as a product.

**Comment by joethreepwood** [comment]
The latest in what has been a day full of product-based changes and PRs ☝️

**Comment by joethreepwood** [comment]
Reopening this, as I think we may be at a point where it's worth removing the Leadership role. 

Also want to point out an interesting correlation here: We introduced 'Founder' as an option and 'Engineering' and 'Leadership' both dropped. Seems like there's a very strong chance that the difference between the 

two will specifically be CTOs or technical founders - a persona we don't specifically cater to, but could be quite sizable in our initial users.

Either way, the rationale for keeping 'Leadership' (previously 'Executive') was that it helps CS by identifying CTOs and CEOs - but my read on the data here is that we can actually just rely on Founder instead. 

![Screenshot 2023-08-31 at 14 47 39](https://github.com/PostHog/meta/assets/84011561/2ebcb0b0-ab3b-4c60-b416-51021609de7b)
