### ISSUE TITLE
PMF guide (real life)

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/meta#118]
## What 

Creating a physical version of James PMF guide to be distributed at YC event in August. V.2 for wider use (aka PostHog for Startups) 

## Where

[Working Figma file ](https://www.figma.com/file/u4bZtwcvFSPKX4ywE0zOmo/PMF-Guide?type=design&node-id=218%3A584&mode=design&t=K6n9RmOmBH4tB7un-1)

## Concept 

Bundle including: 
- PMF guide as an A5 book
- Sticker sheet of pixel hedgehogs and logo
- Custom pin
- Fold out poster

![Image](https://github.com/PostHog/meta/assets/65415371/227f9268-5e22-413b-a877-0747e4db4941)

Feedback open - but deadline is August so speak now or forever hold your peace ☮ 

(sample booklet ordered to sample font sizes and paper quality - from [Print.Work](https://www.print.work/about/)

**Comment by lottiecoxon** [comment]
## UPDATE:
### 1.  got mock book back from previous draft 1. **Learnings from this** 
- pixel images need to be exported at a much higher res
- A5 actually does feel quite large as books go 
- text (was 10px, now 8/9px) comes out quite large 
- front cover ink scratches off with minimal effort just from opening book - maybe worth editing printing process or colour scheme


### 2. Still to do : 
- order pins
- order posters 
- order paper wraps 
- send off final draft to @joethreepwood , @andyvan-ph and @corywatilo for final approval. 
- order books 

🔴  @jamesefhawkins please could you confirm a hard deadline for these 💯  🔴

**Comment by lottiecoxon** [comment]
PostHog Post Project Post Mortem :

Things that went well: 
- book quality came out really nice, getting a sample done was a good idea as the first supplier was rubbish
- (I think) we managed to not have any spelling or grammar mistakes, all thanks to the many people who scanned and grammar checked it multiple times
- Stickers are fun and bright and stick well - no complaints here
- We got this whole book+ bundle finished and shipped really quickly compared to others- a win!


Things that didn't go so well:
- Putting these bundles together took honestly 3 days of my time, I would highly suggest hiring someone on a temporary basis to put these together if we do decide to do a 2nd batch.
- The stickers, while good quality, had one small printing error with the fire hedgehog - hardly noticeable but I see it and it makes my blood boil. 
- transporting these in my old suitcases wasn't cute and probably meant that they fell apart in transit. We could avoid this if we did a 2nd run. 
- I would of liked to work out how to do a foldable poster in this bundle but after trying it with my local printer it didn't work out well, hence the postcards got made instead. On round 2 I could look into this a bit deeper to get a better poster experience.

**Comment by joethreepwood** [comment]
Two things I'd add: 

- We've seen some social and WOM response, which is good - though the project itself is really hard to track the success of. Maybe @jamesefhawkins has some feedback about what he's heard about them, if there was any feedback at the time?
- I _believe_ we have some stock left? Even if not, would be good to think about how we can use these and if the plan is to make them available long term (e.g. add them to the startup bundle and ensure stock is replenished) or if we're going to abandon this as a one-and-done (in which case we could make the guides available to users in the startup program while stocks last).

**Comment by andyvan-ph** [comment]
Other bits and pieces:

- Might be worth hiring a freelance sub-editor as well to help with copy editing
- Would be easier to fix typos etc if I (and others) had access to InDesign. Marking up PDFs is a PITA.
