### ISSUE TITLE
Messaging: Self-hosted onboarding emails update

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#124]
### Context
As per https://github.com/PostHog/meta/issues/123 I'm looking at the onboarding email flows. One thing I noticed is that the self-hosted email onboarding flow is still set up exactly as it was before the sunset of K8s. 

This shouldn't have been a big issue because we no longer support self-hosted and discourage users from trying it, which means few people are giving it a go. They are therefore hitting content which, while not technically incorrect, could lead them to believe SH is actively supported. 

I'm still investigating where users may be coming to SH from, but we want to move those users to Cloud. So, an update is needed. Documenting it here for visibility, and to get any feedback. 

### Current flow
The current flow is a hangover from the old, old Cloud onboarding flow with some specific tweaks in the copy. Here's a description of the current state. Worth noting that it includes `event ingested` flow that we dropped from the Cloud emails for being unreliable. 

- When a user signs up with a valid email address, we send them the first welcome email after a 1 hour delay.
- We check if an event has been ingested. 
   - If yes: Do nothing. 
   - If no: We send an email directing them to the docs, and advising them to invite an engineer, then wait 1 day and until a weekday. 
- We check if an event has been ingested, again.
   - If yes: Go to next step.
   - If no: We send an email directing them to the Slack and the Community, then wait 1 day and until a weekday.
- We check if an event has been ingested, a penultimate time.
   - If yes: Go to next step.
   - If no: We send an email directing them to book a demo.
- We check if an event has been ingested, a final time.
   - If yes: Go to next step.
   - If no: Do nothing until an event is ingested, then go to next step.
- We wait 1 day and until a weekday, then send an email which explains what an AARRR dashboard is and directs to a tutorial.
- We wait 1 day and until a weekday, then send them an email upselling them to session replay which directs them to the product page on the site.
- We wait 1 day and until a weekday, then send them an email upselling them to feature flags which directs them to the product page on the site.
- We add the `completed_onboarding_email property` as `true`

### Proposed flow
We should change this flow to be more similar to the current email flow for open source users, but with a greater emphasis put on the lack of support. That would look like this: 

- When a user signs up with a valid email address, we send them the first welcome email after a 1 hour delay. We are very clear that support is not offered and direct them to migration guides. 
- We wait for 1 week and for a week day, then send an email advising them to migrate to Cloud in order to continue scaling and benefit from support. 
- We wait for 2 weeks and for a week day, then send an email advising them to migrate to Cloud in order to benefit from the latest features, such as surveys and performance monitoring.

**Comment by joethreepwood** [comment]
Draft messaging. 

Email 1 
<img width="626" alt="Screenshot 2023-08-01 at 18 04 27" src="https://github.com/PostHog/meta/assets/84011561/14582df6-f4e2-41c9-a163-2d91a3e1d674">

Email 2
<img width="899" alt="Screenshot 2023-08-01 at 18 18 19" src="https://github.com/PostHog/meta/assets/84011561/53d68db9-fa44-4749-b348-0903149fe9ce">

Email 3
<img width="935" alt="Screenshot 2023-08-01 at 18 47 34" src="https://github.com/PostHog/meta/assets/84011561/e3272365-7827-4291-8881-38982b0bdf40">

**Comment by joethreepwood** [comment]
I've pushed this live immediately, as there are users in the funnels who would be getting incorrect information as it is. Happy to take any feedback still, however.

**Comment by raquelmsmith** [comment]
Do people get this messaging if they've set up the FOSS docker-based version? If so I think the first email isn't quite appropriate. Self-host4ed docker deployments won't be using kubernetes, and we shouldn't be scaring them away from self-hosted so much as enticing them to try cloud.

**Comment by joethreepwood** [comment]
No, there's a separate flow for that. The emails are similar, but they're tailored to open source and the tone is a little different. Less "You should really upgrade because K8s is dead" and more "Hope you're having fun, and did you know there are extra features on Cloud?"

**Comment by joethreepwood** [comment]
This is now launched and seems to be going well, so...
