### ISSUE TITLE
Messaging: Property flattener removal

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#125]
Context: https://posthog.slack.com/archives/C0374DA782U/p1691150080499099

The property flattener app is causing issues and needs to go away. 

200ish impacted orgs: https://posthog.slack.com/archives/C0374DA782U/p1691156277387579?thread_ts=1691150080.499099&cid=C0374DA782U

Proposed messaging below. I'm suggesting we give a weeks' notice for this as best practice, but please let me know if it needs to be more urgent. 

<img width="813" alt="Screenshot 2023-08-04 at 14 41 47" src="https://github.com/PostHog/meta/assets/84011561/93c1c500-425c-47f1-8d77-f3a5b06f327e">

**Comment by joethreepwood** [comment]
PR to remove from .com - https://github.com/PostHog/meta/issues/125

**Comment by tiina303** [comment]
it's not really a problem for us, it's a problem for the teams using the app. I'd maybe call out that it spams your filters search as a reason they want to migrate away from it and use hogQL instead.

**Comment by joethreepwood** [comment]
<img width="589" alt="Screenshot 2023-08-04 at 14 49 37" src="https://github.com/PostHog/meta/assets/84011561/1c6cb269-b1e5-4230-a1b4-9e1cc942d696">

Tweaked

**Comment by benjackwhite** [comment]
I think we have to be clever here and do the legwork to make sure that existing insights aren't broken.

If we aren't able to detect which insights are affected and pro-actively modify them to use hogql, I don't think we should expect our users to...

**Comment by joethreepwood** [comment]
Closing as Cam took lead on this as a different approach.
