### ISSUE TITLE
Messaging: Planned maintenance for Aurora upgrade

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#126]
### Context
We've got [a major DB upgrade](https://github.com/PostHog/posthog-cloud-infra/issues/1987#issuecomment-1686566451) coming up. 

It'll impact US cloud only, take around 4 hours, is planned for Aug 29th, and will require email comms, service page updates and an in-app warning at the time. We're launching this ASAP to ensure users have maximum visibility and warning.

New signups in this time will be redirected to EU cloud. 

### Audience / Targeting
All US Cloud users. 

### Resources, timeline, responsibilities
Checklist for deliverables:

- [x] Email comms to all users to notify of the upcoming work, to be sent ASAP - @joethreepwood 
- [x] Update service page to answer questions, etc - @joethreepwood 
- [x] Run an in-app notification / banner that runs while maintenance takes place - @joethreepwood 
- [ ] Redirect all signups during this period to EU Cloud - @raquelmsmith 
- [ ] Deactivate banners, update service page once work is completed - @joethreepwood 

Previews of planned copy to go below, for approval from the Infra team.

**Comment by joethreepwood** [comment]
Proposed in-app banner copy, to target US USERS ONLY. 

`<span style='font-size: 16px; font-weight: semibold;'>Planned maintenance is currently underway and ingestion is temporarily paused. <a href='https://posthog.com/service-message>Find out more</a>.</span>`

Email copy to send ASAP:
<img width="765" alt="Screenshot 2023-08-22 at 12 25 10" src="https://github.com/PostHog/meta/assets/84011561/29cfc815-ff64-4c0c-8e37-569062df3929">

Can I get a comment of approval from @neilkakkar and @danielxnj please? I'll prepare the service page update separately. 

@danielxnj Can you confirm that we're working in EDT, rather than EST as specified in the original issue?

**Comment by joethreepwood** [comment]
Service message changes: https://github.com/PostHog/posthog.com/pull/6565

**Comment by danielxnj** [comment]
Hi @joethreepwood, we want to do it at 6AM EDT. 11 AM is in the middle of the working day for US.

**Comment by joethreepwood** [comment]
<img width="768" alt="Screenshot 2023-08-22 at 13 53 06" src="https://github.com/PostHog/meta/assets/84011561/f4e1335f-58aa-4f5e-ba75-c8da61ee3857">

Corrected! All else look OK? I'd like to send this today if it seems good to you and @ellie

**Comment by ellie** [comment]
Looks good to me!

**Comment by joethreepwood** [comment]
Email scheduled to go in about an hour. Service page updates. Banner copy prepped. 

Just need to enable the in-app banner app on the day.
