### ISSUE TITLE
Messaging: Automatic Cohort Creator Deprecation

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#131]
# Messaging

### Context
There are some users still using the Automatic Cohort Creator app, which has been deprecated in favour of Group Analytics. 

### Goal
Convert users to Group Analytics. Scale down usage of ACC. 

### Format
Email

### Audience / Targeting
The specific users: https://posthog.slack.com/archives/C01FHN8DNN6/p1694182974999549?thread_ts=1694182947.789499&cid=C01FHN8DNN6

### Resources, timeline, responsibilities
Proposing 1x emails, to be send ASAP. We can send more, but this is a small list and low impact so...

Email to be sent from Customer.io, approved by @simfish85 and @tiina303, facilitated by @joethreepwood 

### Requested input
Feedback on copy requested. 

Q for @tiina303 and @simfish85:  In order to facilitate the deprecation, we should set a deadline. Start of next month (2nd Oct) is probably a good, clean time - but we can be flexible. Can we agree that deadline and that this approach is appropriate?

Would need Pipeline team to disable the app when the time comes. 

### Previews
Coming soon.

**Comment by joethreepwood** [comment]
Email for approval, please @tiina303 @simfish85 

<img width="620" alt="Screenshot 2023-09-12 at 17 56 35" src="https://github.com/PostHog/meta/assets/84011561/d9e6b360-27d4-43d3-86df-4203f01c0643">

**Comment by simfish85** [comment]
Couple of things:
1. I think Group Analytics should be capitalized as it's a product feature (like Cohorts)
2. Do we want some sort of migration guide to accompany this?  e.g. here's how you go from Cohorts to Groups

**Comment by joethreepwood** [comment]
> 1. I think Group Analytics should be capitalized as it's a product feature (like Cohorts)

[Style guide](https://github.com/PostHog/posthog.com/blob/master/STYLEGUIDE.md) is to write features in sentence case. 

> 2. Do we want some sort of migration guide to accompany this?  e.g. here's how you go from Cohorts to Groups

I'm actually a little in the dark on how one would switch over per se, as it seems a little custom to each org? Regardless, the group analytics docs cover most of the essential questions and so I think should work. 

@ivanagas may have an opinion here though

**Comment by ivanagas** [comment]
I'm not fully clear on the use case for it, but we could recommend:

1. Use group analytics: https://posthog.com/docs/product-analytics/group-analytics
2. Use HogQL expressions: https://posthog.com/docs/hogql/expressions

**Comment by joethreepwood** [comment]
Yeah, the link we have in there already goes to the group analytics docs. Let's leave at that for now. 

It's a small user set, so we can respond to questions if needed.

@tiina303 Does this look OK to you? If I can get a 👍 I'd like to schedule to run this week.

**Comment by joethreepwood** [comment]
This is now scheduled in for 3PM GMT on Sept 15th. 

If any other feedback, let me know before then. Otherwise we just need to deprecate the app on the date. 

I'll do a PR now to remove the docs.

**Comment by tiina303** [comment]
👍  yes, sorry I didn't see the issue earlier. The app is already not available for any new users. I agree that we can just respond to questions if they ask us anything in response. Can we make it so they will end up in zendesk in pipeline's queue (for replies)?

I will disable all remaining users and remove the app on the 2nd of Oct then unless we hear any reasons not to.
