### ISSUE TITLE
Launch Plan (Marketing): Surveys

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#133]
Surveys are launching and it's going to be awesome. So, let's make sure it launches really well!

### Preamble
User surveys are somewhat unique in that they are going to be desireable and useful for outside of our usual ICP because they're easy to set up and we have good customization tools within the platform. Marketers and product managers will want to use this tool, as well as engineers. 

We'll be deciding the exact pricing for this feature soon and will decided a hard launch date as part of that process. Watch this issue for details: https://github.com/PostHog/product-internal/pull/508

Without further ideas: Ideas and to-dos! 

#### Before launch - Oct 9th
- [x] Send https://github.com/PostHog/meta/issues/135 (@joethreepwood)
- [x] Update existing tutorials (https://github.com/PostHog/meta/issues/133#issuecomment-1727226042) (@ivanagas ) https://github.com/PostHog/posthog.com/pull/6890
- [x] https://github.com/PostHog/meta/issues/134 (@joethreepwood) 

#### Launch day activity - Oct 23th
- [x] Publish https://github.com/PostHog/posthog.com/pull/6580 (@joethreepwood)
- [x] Publish https://github.com/PostHog/posthog.com/pull/6819 (@joethreepwood)
- [x] Run paid ads, competing with HotJar, Pendo, SurveyMonkey, Sprig and other tools. (@joethreepwood via Hey) 
- [x] Add Surveys details to our Bookface deal. (@joethreepwood)
- [x] Publish a US in-app survey announcing that Surveys are now available. ([Draft here](https://app.posthog.com/surveys/018af528-dfc7-0000-2ff4-87edf3f92d1e), @joethreepwood)
- [x] Publish a EU in-app survey announcing that Surveys are now available. ([Draft here](https://app.posthog.com/surveys/018b47ff-c7aa-0000-e67b-0787f2cafaea), @joethreepwood)
- [x] Publish posts on all social channels and user Slack, mirroring the blog post. ([Draft here](https://docs.google.com/document/d/1WQFEUepGrjsXRREdW-HmA50znQsbHedCtqPTOe_V5ho/edit), @joethreepwood)
- [x] Publish a changelog announcement and add as a milestone. ([Draft here](https://squeak.posthog.cc/admin/content-manager/collectionType/api::roadmap.roadmap/265), @joethreepwood)
- [x] Merge [this PR](https://github.com/PostHog/posthog.com/pull/6766) to update Survey's docs. [Context](https://posthog.slack.com/archives/C034XD440RK/p1695288581074469) (@joethreepwood)

#### Follow-on activity
- [x] Publish the announcement in the PostHog for Startups & What's New In PostHog email newsletters. (@joethreepwood)
- [ ] Publish https://github.com/PostHog/posthog.com/pull/6794 (@joethreepwood)
- [ ] Create an onboarding flow to encourage new user adoption. (@joethreepwood)
- [x] Publish new tutorials about using Surveys. (@ivanagas)
- [ ] Update all existing content and competitor comparisons. (@andyvan-ph)

### Extra ideas (things we could do, but don't always)
- [x] Publish in Product for Engineers by making 'User surveys' a theme for discussion. 
- ~Publish announcement to HackerNews.~
- ~Send a dedicated announcement email to all users.~
- ~Launch Surveys as a tool on ProductHunt.~
- ~Ask for social amplification from influencers in our network. Dalton? Phil McParlane?~ 

### Feedback & next steps
It would be to get any feedback on the above ideas, and any additional ideas, as soon as possible.

Once I have that I'll update the list above with the definite actions we'll take and attach owners to them where needed (mostly I'll do it).

Tagging some relevant people for input: @charlescook-ph @andyvan-ph @ivanagas @Lior539 @liyiy @neilkakkar @annikaschmid @corywatilo

**Comment by Lior539** [comment]
Our survey docs are in a bit of meh state. Next sprint I plan on updating them. I've updated the launch plan to include this

**Comment by ivanagas** [comment]
I am working on a "how to ask great product questions" newsletter so related, maybe will hold off on publishing it until launch.

**Comment by liyiy** [comment]
- Add awesome surveys art that @lottiecoxon came up with 😀 

https://github.com/PostHog/posthog.com/issues/6508

**Comment by Lior539** [comment]
These 3 tutorials need to update as installing surveys no longer requires site apps:

https://posthog.com/tutorials/feedback-interviews-site-apps
https://posthog.com/tutorials/nps-survey
https://posthog.com/tutorials/survey

I've added them to Joe's list above

**Comment by andyvan-ph** [comment]
Since you asked for more feedback:

- Some of the launch day activity doesn't need to be on launch day – e.g. updating all the comparisons + paid ads.
- One for @ivanagas, but depending on availability, it would be good to get some newsletter sponsorships around the survey launch.
- I think a HN launch would be good, especially if we frame it around company vision + closing the loop. Should be from James if we're doing it, probably.
- Definitely should get any amplification we can get. 
- Do we have time to do a launch / demo video? Could be post-launch, but I think we need start thinking about video more in our launches.
- I quite like the idea of using the in-product survey instead of the banner...
- Maybe covered in product page PR, but Surveys needs to be added to homepage carousel as well.

**Comment by joethreepwood** [comment]
Agree with most of this!

> * Some of the launch day activity doesn't need to be on launch day – e.g. updating all the comparisons + paid ads.

It doesn't _need_ to be done on launch day, but there's no reason to delay and anything after launch would be detrimental so to me this is more a deadline than anything. 

Paid ads is, from our end, a conversation with Hey once we have the date locked down more certainly. Comparisons we could really be doing already due to the beta. 

> * I think a HN launch would be good, especially if we frame it around an update on company vision + closing the loop. Should be from James if we're doing it, probably.

I have a draft and PR out for a factual announcement, but agree a vision piece could work well. Tagging @jamesefhawkins in case he has Thoughts. 

> * Maybe covered in product page PR, but Surveys needs to be added to homepage carousel as well.

Yep, this will be in the product page PR. 

> * Speaking of the above, maybe the email we send to users should be more like the above – i.e. a letter from James about the launch and what it means etc.

I disagree with this, but that may be because I snap to thinking of these sort of vision letters as a bit airy/abstract. Fine for a blog post, but I think if we're hitting users over email it should be about [telling the features](https://newsletter.posthog.com/p/why-we-sell-features-not-benefits), not espousing the benefits.

That said, if you want to suggest the messaging in greater detail we can consider, or work it in. Not saying Hard No.

**Comment by andyvan-ph** [comment]
> I disagree with this, but that may be because I snap to thinking of these sort of vision letters as a bit airy/abstract.

I probably made this sound more abstract than I intended, I mainly meant I think it would be more effective if these big announcements came from James / a real person + isn't formatted like an "official" email. That would also make it easier to talk a little about the "why we've added this feature" in addition to the "what" bit. It's opportunity to indoctrinate users in our way of thinking, so they share that message with other people.

**Comment by joethreepwood** [comment]
You make a good point. I'll have a go at drafting something today so we're moving in that direction and add it as a separate post in the https://github.com/PostHog/posthog.com/pull/6819 PR -- that way we can choose and centralize work in one place.

**Comment by joethreepwood** [comment]
<img width="1004" alt="Screenshot 2023-10-03 at 11 51 47" src="https://github.com/PostHog/meta/assets/84011561/f3382329-2c02-4416-b309-0dd13e38ea2d">

Prepped this for launch. Directs to /surveys

**Comment by neilkakkar** [comment]
I love using surveys for the CTA for surveys xD

For the URL filter, sounds like you want this to show up in app, and also on the website? (regex filters are coming in a minute for better targeting)

**Comment by joethreepwood** [comment]
> For the URL filter, sounds like you want this to show up in app, and also on the website? (regex filters are coming in a minute for better targeting)

Yep. Would this not work as it is at the moment?

**Comment by neilkakkar** [comment]
it will, all good! - just wanted to confirm that's what you wanted. I feel it _might_ be a bit much on `posthog.com` if people aren't logged in / haven't created an account, since it ends up redirecting them to a useless link?

**Comment by joethreepwood** [comment]
ah, good call -- I may create a duplicate there then and direct it to the announcement

**Comment by joethreepwood** [comment]
Actually, I guess I'll need three duplicates. One for EU, one for US, on for site.

**Comment by neilkakkar** [comment]
Yeah annoying, because you want the link to change based on where it's shown as well.. so we can't do all 3 in 1.

**Comment by joethreepwood** [comment]
We’ve made the decision to announce to existing users on Monday 9th than survey pricing will launch on Oct 23rd, not Oct 19th as originally planned.

I'll update the assets and timeline above.

**Comment by joethreepwood** [comment]
We tried some new tactics this time around, so thought I'd close this issue out by looking at how some things did. 

### What went well?
Overall, surveys seems a very successful launch. 

We bought a lot of users into the `/surveys` area of the product and the spikes all line up with elements of our launch plan. 

<img width="1334" alt="Screenshot 2023-10-30 at 13 38 35" src="https://github.com/PostHog/meta/assets/84011561/b91048ad-e8b3-42fd-8212-3404116b08e7">

### What could we do better?
Where we didn't do as well was with conversion of those views. If a user arrives at `/surveys` for the first time, they see this: 

<img width="1359" alt="Screenshot 2023-10-30 at 13 50 14" src="https://github.com/PostHog/meta/assets/84011561/03dbd7fd-832b-414b-8a60-3d12926b1070">

We can do a better job here in the future by making onboarding slicker. We could try adding a video demo, a link to a case study, incorporating strong messaging about what surveys are for, etc. 

We should also consider how this view may work for organizations. We really want to educate all users in an org about new features, but if _any_ user in an org has created a survey then this onboarding step won't be shown -- instead, we'll show a list of all active surveys. Only one user sees onboarding steps; others miss out. 

### Anything else?

<img width="1350" alt="Screenshot 2023-10-30 at 13 55 04" src="https://github.com/PostHog/meta/assets/84011561/6894fd4f-f835-414b-9291-17b3d558718f">
<img width="1351" alt="Screenshot 2023-10-30 at 13 54 54" src="https://github.com/PostHog/meta/assets/84011561/8306462e-e61c-4d6b-a22f-73df6bb0c16b">

Using surveys to create CTAs that drive users to `/surveys` seems to work pretty well in terms of visibility, but the conversion rate isn't great. 

This is partly to be expected -- users who weren't otherwise thinking to launch a survey are unlikely to do so based just on availability. However, we can definitely trial new types of messaging to improve here.

**Comment by neilkakkar** [comment]
small nit on point 2: Every new person should see the 'getting started' flow, even if someone else created surveys. Was this not happening for you?

**Comment by joethreepwood** [comment]
Ah, no, I was just checking on the demo site. Nevermind on that point then!

**Comment by raquelmsmith** [comment]
> We can do a better job here in the future by making onboarding slicker. We could try adding a video demo, a link to a case study, incorporating strong messaging about what surveys are for, etc.

I like those ideas, if you have materials for this lmk and i can add to see if it improves conversion!
