### ISSUE TITLE
Messaging: Surveys pricing is coming soon

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#135]
# Messaging

### Context
We want to give users two weeks notice before surveys pricing goes live, so users are aware it's coming out of beta. 

Users who create a survey before then will get an enhanced offer. 

Part of https://github.com/PostHog/meta/issues/133

### Goal
Trigger 'survey created' within 2 weeks of getting the email. 

### Format
1x email. To be sent Oct 5th. 

### Audience / Targeting
All subscribed users on Cloud. 

### Requested input
Copy feedback and send time. 

### Previews
First draft for approval from @andyvan-ph @neilkakkar @liyiy @annikaschmid 

<img width="775" alt="Screenshot 2023-09-26 at 15 55 03" src="https://github.com/PostHog/meta/assets/84011561/de46cb3f-2963-4e88-9b54-ce36dfed3059">

**Comment by liyiy** [comment]
question: Where does the "create a survey now" take the user to?

**Comment by joethreepwood** [comment]
> question: Where does the "create a survey now" take the user to?

Takes users to: app.posthog.com/surveys

> FLy-by: I love this illustration, but people might think our suvey actually has hedgehog faces and that would honestly be a turnoff for me (as much as I love Max).

That seems a pretty big jump to me so I'd like to ask for more feedback on this (maybe @ivanagas @Lior539 ?) before changing. 

Not against the change at all, and I actually have an image ready. But we'll be using this image in other places too, so I need to know if this will apply to other messages.

**Comment by raquelmsmith** [comment]
I mean, we use hedgehogs all over the product so I don't think it's _that_ big of a jump. I really don't think we want people even questioning if the survey will use hedgehog faces 😄

**Comment by raquelmsmith** [comment]
> Surveys has improved massively since the beta launch in June

To me this reads as "our beta was shit so let's try again!" I'd say something more along the lines of "since we launched our beta in June we've added X, Y, and Z, among lots of other features." And link to somewhere they can read more about it?

**Comment by joethreepwood** [comment]
> > Surveys has improved massively since the beta launch in June
> 
> To me this reads as "our beta was shit so let's try again!" I'd say something more along the lines of "since we launched our beta in June we've added X, Y, and Z, among lots of other features." And link to somewhere they can read more about it?

Will amend that line a little, but yes we absolutely cover this in the blog PR too

> I mean, we use hedgehogs all over the product so I don't think it's _that_ big of a jump. I really don't think we want people even questioning if the survey will use hedgehog faces 😄

Fair. Let me move this to the art request topic then, so Lottie can work on new art.

**Comment by corywatilo** [comment]
> Will amend that line a little 

Inspiration: Since we released the beta in June, we've added: X, Y, Z.

Can we use a `<table>` for the pricing grid? Something like...

| Monthly responses 	| Price per response 	|
|---	|---	|
| 0-250 	| Free 	|
| 251-500 	| $0.20 	|
| 501-1,000 	| $0.10 	|
| 1,001-5,000 	| $0.03 	|
| More than 5,000 	| $0.02 	|

**Comment by jamesefhawkins** [comment]
flyby: not sure if it's what you'll use, this title doesn't make sense to me (what is "enhanced pricing" / why would I want to unlock this)

<img width="488" alt="Screenshot 2023-09-26 at 21 37 01" src="https://github.com/PostHog/meta/assets/47497682/2a300030-a0c9-4bb7-bb60-b5d0bcf401ec">

are we going to auto-charge people using it already? if so maybe something like:

"PostHog surveys are out of beta! Pricing info..."

**Comment by Lior539** [comment]
> FLy-by: I love this illustration, but people might think our suvey actually has hedgehog faces and that would honestly be a turnoff for me (as much as I love Max).

> That seems a pretty big jump to me so I'd like to ask for more feedback on this (maybe @ivanagas @Lior539 ?) before changing.

I would stick with the hedgehogs. More on brand, and showing the actually survey UI feels a bit plain and corporate. We can include images of the actual survey UI further below in the email, but I would stick to the hedgehogs for the cover

**Comment by lottiecoxon** [comment]
Updated blog image and PNG image 

![Untitled_Artwork 22 1](https://github.com/PostHog/meta/assets/65415371/df657fcc-e16b-4c1c-901b-578d8a86945f)

![Surveys](https://github.com/PostHog/meta/assets/65415371/59ecef38-1709-4972-81bf-1bb0f6116401)

**Comment by joethreepwood** [comment]
Thanks! Updated with new art. 

We weren't able to get the tables working properly, so defaulting back to this: 

<img width="614" alt="Screenshot 2023-10-02 at 15 50 24" src="https://github.com/PostHog/meta/assets/84011561/6a8914e0-5493-4b6b-87dd-41190fd68090">

**Comment by corywatilo** [comment]
I went ahead and re-added this and got it polished. Here's what it looks like in Gmail now:

<img width="827" alt="image" src="https://github.com/PostHog/meta/assets/154479/763c892f-390d-437f-bb47-4edb7d352f4c">

**Comment by joethreepwood** [comment]
We're now announcing it for the 23rd, and the news goes live in a few hours. 

<img width="672" alt="Screenshot 2023-10-09 at 11 00 53" src="https://github.com/PostHog/meta/assets/84011561/58384077-b43f-40d0-8b2f-4acb16ad9a42">
<img width="372" alt="Screenshot 2023-10-09 at 11 00 29" src="https://github.com/PostHog/meta/assets/84011561/6158f07a-65d6-4782-9d09-bafe16dfd3ec">
