### ISSUE TITLE
Messaging: Postgres & BigQuery app deprecation

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#137]
# Messaging

### Context
We're deprecating the Postgres & BigQuery export apps in favour of the new batch exports tool.

### Goal
We want users to migrate off the apps. We can track performance manually via the users of those apps and batch export usage, but cannot track these in C.io. 

### Details
1x email. Targeted to relevant users. Roughly 135 impacted orgs, with a list from Tomas. 

Cohort: https://app.posthog.com/cohorts/46971

Email to be in personal style, automated from Simon. 

To be followed by a second email, if needed, later. 

Deadline for migration is Oct 23rd. 

### Previews
Coming soon.

**Comment by joethreepwood** [comment]
There are 1200ish users in this cohort, but only 1160 are still subscribed to service updates -- meaning approx 40-50 users have unsubscribed from this sort of message, despite being warned they'd miss this sort of update. 

My inclination is not to message the unsubscribed users, but flagging here for feedback.

**Comment by joethreepwood** [comment]
<img width="846" alt="Screenshot 2023-10-10 at 11 43 05" src="https://github.com/PostHog/meta/assets/84011561/25649913-774d-4ca7-88c1-6316c9d1ab2c">

If you want it to look personal then here's some copy for approval @simfish85 @tomasfarias - just let me know any feedback. 

Alternative would be a designed message, similar to those used for https://github.com/PostHog/meta/issues/131

**Comment by tomasfarias** [comment]
@joethreepwood Some notes:
* The migration may take longer than a day, so I would word it to imply that we will start deprecating on October 23rd but may take a few days to completely deprecate.
* We should clarify that users will be migrated automatically if they don't or can't do it themselves. No data loss will occur when moving to the new system.

**Comment by joethreepwood** [comment]
I'd prefer to stick with a clear deadline if possible. If we try to say that we will start migrating users on the 23rd, but it might take longer and we aren't sure how much longer then the message starts to be less useful. 

Here's a new version, let me know what you think? I'd like to send this by tomorrow if possible. 

<img width="1015" alt="Screenshot 2023-10-12 at 12 26 54" src="https://github.com/PostHog/meta/assets/84011561/11ac414e-4b21-4b76-b840-39a539ff339b">

**Comment by tomasfarias** [comment]
> I'd prefer to stick with a clear deadline if possible. If we try to say that we will start migrating users on the 23rd, but it might take longer and we aren't sure how much longer then the message starts to be less useful.

That's a good point, we can take our time regardless 👍 

Second version looks good to me!

**Comment by joethreepwood** [comment]
<img width="523" alt="Screenshot 2023-10-12 at 13 19 59" src="https://github.com/PostHog/meta/assets/84011561/aff30941-dac6-4cd6-9a82-ef9a3755976c">

Scheduled. Put a day on it, in case @simfish85 wants to weigh in.

**Comment by simfish85** [comment]
Looks good to me - happy for you to send it @joethreepwood

**Comment by joethreepwood** [comment]
<img width="551" alt="Screenshot 2023-10-12 at 13 37 09" src="https://github.com/PostHog/meta/assets/84011561/879b38e5-caa3-421f-bfb3-9d793365033e">


Cool, moved it up then.
