### ISSUE TITLE
Messaging: Survey app deletion

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#138]
# Messaging

### Context
A follow on to https://github.com/PostHog/meta/issues/134 to ensure users take the needed steps. 

Further context: https://posthog.slack.com/archives/C01FHN8DNN6/p1696937313023089

### Goal
Delete the survey app. 

### Format
1x email to all users of the survey app.

Sending ASAP, encouraging users to upgrade. 

### Previews
Coming soon.

**Comment by joethreepwood** [comment]
We'll need to send 2x emails, it seems -- one to US, one to EU. 

Same copy for both. @neilkakkar does this look suitable?

<img width="705" alt="Screenshot 2023-10-10 at 13 23 19" src="https://github.com/PostHog/meta/assets/84011561/03fe5cf5-231f-4977-9e31-8ca93bc20cba">

**Comment by neilkakkar** [comment]
yeah looks good, thank you!

(cc: @jurajmajerik @liyiy @annikaschmid )

**Comment by joethreepwood** [comment]
<img width="445" alt="Screenshot 2023-10-10 at 14 07 23" src="https://github.com/PostHog/meta/assets/84011561/f0fbb4e3-4da2-43bd-82c8-3bc73c3f9bc7">

EU and US versions scheduled 👍
