### ISSUE TITLE
Keyword research and content plan

### ISSUE THREAD

**Issue by shehuphd** [PostHog/meta#14]
Keywords & content plan

A quick look at the [keywords](https://docs.google.com/spreadsheets/d/12JfkKzt6eVXqCgX6lI2rTS-ZCQWMF7unxOtFbd3OnBA/edit#gid=2013761559) bringing people to our website reveals a few recurring topics:

## Feature flags

**Keywords:**

* feature flag tools
* feature flag example
* what is feature flags
* why use feature flags
* posthog feature flags
* feature flags deployment
* feature flag best practice
* open source feature flags
* how do feature flags work
* feature flags development
* feature flag implementation

Feature flags received the most number of queries to the website by far. We can do a pillar post on how feature flags work in PostHog.

## Heatmaps

**Keywords:**

* heatmaps b2b
* posthog heatmap
* open source heatmap software

What exactly is a heatmap and how does it help you understand user behavior in your product? This blog post would address that.

## Funnels

**Keywords:**

* funnel analytics
* how to use funnel
* user funnel analysis
* how to make a funnel
* product funnel analysis
* how to do funnel analysis
* conversion funnel dropout
* marketing funnel analytics
* what is a funnel in analytics

Funnels are another popular search query leading people to our website, so we should focus on creating multiple pieces of content around how funnels work (esp. in PostHog) and how they can be better used to understand app user behavior.

## Session recording

**Keywords:**

* user session recording
* posthog session recording
* session replay self-hosted
* website session recording open source

This is an opportunity to explain the session recording and replay feature in PostHog and show how it helps devs better understand their products.

## Databases

**Keywords:**

* postgres scaling
* posthog clickhouse
* postgresql to clickhouse

Your database’s performance determines how fast your app loads, among other things. We can do a post on our decision to move to Clickhouse and drop Postgres, plus other posts on database performance/maintenance in general.

## Comparisons and alternatives

**Keywords:**

* PostHog alternative
* posthog vs mixpanel
* posthog vs amplitude
* amplitude vs heap vs mixpanel
* mixpanel open source alternative

Our users _will_ be comparing us against the competition, so we might as well have a definitive comparison post that positions us in the best light and drives that valuable traffic to our sign-up page.

## Tool, plugins, frameworks,. and platforms 

**Keywords:**

* posthog react
* posthog flutter
* posthog docker
* posthog plugins
* posthog react native

What are the underlying frameworks and platforms that PostHog is built on/with? This series could explore these technologies and explain why//how they contribute to making PostHog such a powerful platform.

## Metrics

**Keywords:**

* b2b product metrics
* product usage metrics

PMs and devs always want to know what type of metric is key to track. This blog will outline a few  metrics that high-performing business use to build better businesses.

## Open source web and app (product) analytics

**Keywords:**

* self hosted analytics
* product analytics system
* product analytics platform
* open source web analytics
* open source [app] analytics
* website analytics open source
* open source analytics software
* web analytics tools open source
* analytics database open source
* product usage analytics software
* web analytics software open source
* user behavior analytics open source
* data analytics platform open source
* software for product usage analytics
* marketing and analytics platform open source

People are searching for open source data analytics platforms, and a blog post on this topic would be a great way to draw people in.

## Revenue tracking 

**Keywords:**

* revenue tracking
* track revenue

Would PostHog be useful for tracking revenue within an app? If possible, this functionality might be highly useful for e-commerce brands with online stores.

## Event tracking

**Keywords:**

* event tracking guide
* custom event tracking

How do you track different events within your app? We’ve got the answers - using PostHog, of course…

## Cohorts, retention, and segmentation

**Keywords:**

* retention cohort
* cohort retention
* retention metrics
* retention tracking
* cohort segmentation
* cohort analysis tutorial
* how to measure app retention

Retention is a huge aspect of product development and growth, and we can touch on how PostHog helps companies track their user retention metrics over time.

## Monetizing open source

**Keywords:**

* how to make money with open source
* open source software software as a service

We already have an article out on this, but we can repurpose that info into an infographic, a narration, etc.

## Developer marketing strategy

We’d be getting a bit meta here, but a post like this would be extremely useful for exposing current and future devtool founders to PostHog early in their journey.

## Product-led growth

**Keywords:**

* product led companies examples
* product led growth

We can do an explainer on what PLG is, what metrics to track, and what mistakes to avoid.

**Comment by piemets** [comment]
This is super helpful! Just requested access to the sheet, but in the meantime - in general, how many times do these terms actually come up? It would be helpful to get a sense of scale, as the terms without this context might lead us down the wrong path.

**Comment by joethreepwood** [comment]
Thanks Mo, this is a great list. 

Do you have an idea of which keywords you want to prioritise and what the timeline/approach for delivering these ideas would be? I've requested access to the sheet but I wonder whether we go deep on a particular area (such as funnels) with multiple posts, or whether we hit each topic once as fast as we can and reassess. 

Tonally too, I wonder if we want to consider the positioning of the blog. Up until now the blog has mostly been content about PostHog's journey and we'd dilute that considerably if we drop in (potentially multiple) posts on these 15 topics. That may not be a problem, but I think worth considering if some of the content outlined should exist off-blog or should be de-listed from the main feed in order to preserve the current content-feel. 

Competitor comparison articles, for example, may exist better either as a separate landing page or as something which isn't listed in the main feed. 

On that topic I'd also suggest that in addition to doing straight '_PostHog vs. Mixpanel_' comparisons we also do some aggregator articles ('_The 31 Best Product Analytics Platforms_', '_The 11 Best Heatmap Tools_', etc). They tend to perform better at an SEO level as a result of the extra keywords and links, in my experience.

This is a long list, so if helpful then I'm happy to work on a couple of these articles or reach out to my freelance network to help us scale. Let me know.

**Comment by shehuphd** [comment]
@piemets:
Just opened access to the Sheet for anyone with a PH email addy - please try accessing it again. I've also sorted the terms by impressions to give you an idea of which keywords are netting us the most views.

@joethreepwood:
Re: the list, I'm thinking:
- Pillar articles on each topic, max 2 posts per topic (to not dilute link juice).
- We already have a mix of articles at the moment (storytelling mixed w/ Arrays) so adding technical content shouldn't be too much of a disruption - but what we can do is divide the blog into different sections like [monday.com](https://monday.com/blog) does. @corywatilo is this something we can do?
- Comparison articles should exist as individual landing pages. We can then play around with different page structures and layouts as needed.
- Round-up articles are a great idea - will need your and/or engineering's input here as you/they have got more experience with competing products (cc: @jamesefhawkins, @timgl, @paolodamico).
- Would definitely love your help with these, especially the comparison articles as your positioning chops will come in handy there.

**Comment by piemets** [comment]
Closing this as the output of the [SEO audit](https://github.com/PostHog/company-internal/issues/370) supersedes it
