### ISSUE TITLE
RFC: Using Surveys for CTA pop-ups on PostHog.com

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#141]
I know, I know. This feels innately like a bad, off-brand, anti-pattern idea. That's why I'm doing an RFC instead of stepping on toes with it. 

But, with the new surveys functionality, I feel it's worth at least having a discussion about tactical uses for Surveys on the marketing side. 

We could use survey targeting to limit these popups so that users don't see them if they've seen another survey in the last 14 days.

Ideas which immediately come to mind...

### CTAs on newsletter posts
<img width="357" alt="Screenshot 2023-10-20 at 11 15 43" src="https://github.com/PostHog/meta/assets/84011561/c7856ef4-15fa-44ee-9512-715226f7979b">

We could deploy a CTA like this on all posts which are from the Product for Engineers newsletter, directing users to the Substack directly. 

### CTAs on comparison posts
<img width="364" alt="Screenshot 2023-10-20 at 11 18 49" src="https://github.com/PostHog/meta/assets/84011561/27be06a6-ce05-4478-9024-acb10ee1d43d">

Comparison posts are pretty obviously high intent, and we currently rely on CTAs in the copy. We could offer a CTA here directing to the either the demo, or sign-up process. 

### CTA on app-building docs
<img width="350" alt="Screenshot 2023-10-20 at 11 20 30" src="https://github.com/PostHog/meta/assets/84011561/5f7cf3c7-4de4-43ef-a0a6-ed276220d3a3">

Some sections of the docs empower users to build functionality. It could be useful to know what feature's we're missing.

**Comment by charlescook-ph** [comment]
> This feels innately like a bad, off-brand, anti-pattern idea. 

Lol, you're not wrong. Brave of you to suggest it though!

I'm struggling to see why we would do this instead of just building a CTA into the content itself? 

Or to put it another way, when was the last time you didn't immediately dismiss a popup on a website?

**Comment by andyvan-ph** [comment]
I wouldn't use it for any of the suggested use cases.

_However_, I do think we could try using it for announcing new features, e.g. instead of an announcement bar in the product + website.

**Comment by joethreepwood** [comment]
Cool, enough feedback for me. I thought it was a bad idea and I was right. 

We'll definitely be using it for feature announcements in the future, starting with surveys!
