### ISSUE TITLE
Hackathon: Helicone + PostHog

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#142]
Date: Dec 2nd 
Attendees: @fuziontech @raquelmsmith @ivanagas 
Headcount: 300 people
Cost: $5,000 USD
Responsible: @joethreepwood 

Questions: 
- What else is needed
- What swag are we sending
- Do we need to arrange any speaking events
- Theme of hackathon
- Can we capture material from this event for content
- Third judge

**Comment by joethreepwood** [comment]
Swag-wise, we're going to be quite limited in what we can do. Timelines according to @lottiecoxon for merch would be 10-14 days for production, plus another 7 days for shipping, plus any design time (and @lottiecoxon is at an offsite this week). 

To keep this simple, we can just use our existing inventory and ship that from Printfection to SF for usage -- I just need to know where to ship it. 

The downside is that, if there are 300 people in attendance, we don't have enough for everyone in stock already. 

We currently have, in stock: 100x hats, 90x hoodies, 100x socks, 200x stickers, and 75x t-shirts. 

I'd suggest we send: 
50x hats,
50x hoodies,
150x stickers, and
25x backpacks for the winners

How does that sound?

**Comment by fuziontech** [comment]
Sounds reasonable - I don't know if we'll have the full 300, but I will keep up to date with the count as we get RSVPs

**Comment by jamesefhawkins** [comment]
do you think Helicone are competitive? ie they announced themselves as "product analytics for AI companies"

**Comment by joethreepwood** [comment]
I don't see them as competitive, personally. Their site at the moment indicates they're much more in the monitoring space.

On a broad view, maybe, but from the look I had at their product I think there's a big enough differentiation personally.

**Comment by fuziontech** [comment]
There's extremely little overlap on how you would use PostHog or Helicone. If I was to have an app (like max for instance) I would use Helicone to understand and monitor my calls out to OpenAI and PostHog to understand how users are using Max (funnels / retention / cohorting)

I definitely wouldn't use PostHog to do this with any current products in our portfolio. You could hack it, but you can [hack anything to do something it wasn't designed to do](https://zackoverflow.dev/writing/flappy-bird-in-type-level-typescript/).

I view this similarly to Sentry. You could use PostHog to do a lot of what Sentry does, but it's not turn key designed for it.

**Comment by fuziontech** [comment]
@joethreepwood & @ivanagas This was pushed back to Dec 2nd (and locked in) because of a conflict with a judge. This will make things a bit easier from the swag and planning department.

**Comment by joethreepwood** [comment]
Cheers, Jams -- Do you think you can intro me and Ian to someone on their side, so we can chat details? Takes a while to ship things so want to make sure we're all queued up.

**Comment by chitalian** [comment]
> do you think Helicone are competitive? ie they announced themselves as "product analytics for AI companies"

Hi James! We do not intend to compete with Posthog 🙌. We are doing product analytics, specifically around LLM calls and view ourselves more as LLM-Ops with features like (caching, retries, auto model mappings, key vaults, etc...) 

Monitoring is what we do well now, but not what we are planning on expanding to. 

James- Not sure if you remember me, but we chatted over zoom for 30 minutes a few months back and we talked about this then too. 

> from the look I had at their product I think there's a big enough differentiation personally.

I would totally agree. We think there will be a whole market just to monitor LLM calls, we do not intend on expanding into other product analytics like session recording or anything else like that.

**Comment by chitalian** [comment]
Hi @joethreepwood - Feel free to email me justin@helicone.ai, maybe we can schedule a quick call

**Comment by chitalian** [comment]
Just launched the waitlist

https://www.hacktopia.xyz/

https://github.com/Helicone/hacktopia

**Comment by joethreepwood** [comment]
@lottiecoxon I've confirmed the merch and have the address. Do we have a process or contact at Printfection who I need to reach out to in order to send?

**Comment by lottiecoxon** [comment]
Poster is done + ready to go to print! @chitalian 
[large poster for helicone.pdf.zip](https://github.com/PostHog/meta/files/13442113/large.poster.for.helicone.pdf.zip)

**Comment by chitalian** [comment]
@lottiecoxon this is awesome! What sizes would you like the poster?

**Comment by raquelmsmith** [comment]
Do we know what the schedule will be for the hackathon? Trying to figure out my travel plans.

**Comment by fuziontech** [comment]
```


Schedule
9am-10am Coffee + Recession
10am-10:30am Kickoff + Word from our sponsors
10:30am-12:00pm Hacking session
12:00pm-1:00pm Lunch and 
1:00pm-5:30pm Hacking (Submissions end at 5:30)
3:00pm-3:30pm Agent Workshop w/ Agent or AutoGPT
3:30pm-4:00pm Observability Workshop w/ PostHog + Helicone
6:00pm Dinner
7:00pm Presentations
8:00pm Finale
8:30pm EVERYONE OUT

**Comment by raquelmsmith** [comment]
ah ok long day! i'll fly in friday and out sunday then 👍

**Comment by joethreepwood** [comment]
@chitalian Would it be possible to get access to the list of attendees, or signups?

**Comment by lottiecoxon** [comment]
@chitalian I have just realised I missed out an important piece of info on the poster, have you got it printed yet? (If we could replace it with this version that would be ideal but no worries if not) 

[helicone poster.pdf](https://github.com/PostHog/meta/files/13478109/helicone.poster.pdf)

**Comment by chitalian** [comment]
> @chitalian Would it be possible to get access to the list of attendees, or signups?

Hi @joethreepwood i will email you a way to get access to the list of attendees.

**Comment by chitalian** [comment]
> @chitalian I have just realised I missed out an important piece of info on the poster, have you got it printed yet? (If we could replace it with this version that would be ideal but no worries if not) 
> 
> 
> 
> [helicone poster.pdf](https://github.com/PostHog/meta/files/13478109/helicone.poster.pdf)

Hi! No worries, what sizes would you like?

**Comment by lottiecoxon** [comment]
I believe it should be 100cm wide and 200cm in height!

**Comment by chitalian** [comment]
> I believe it should be 100cm wide and 200cm in height!

Sounds good! however, I think in the states for the print it will probably be closer to 36x72

**Comment by lottiecoxon** [comment]
Ah thats only a little smaller - should be absolutely fine at that size too!

**Comment by ivanagas** [comment]
Good job everyone, thanks for organizing!

**Comment by chitalian** [comment]
WOOHOOO
