### ISSUE TITLE
Messaging: BigQuery migration

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#147]
# Messaging

### Context
Around 50% of users previously contacted [to migrate to our BigQuery batch processing system](https://github.com/PostHog/meta/issues/137) have not done so yet. 

Specifically, they are missing the bigquery.jobs.create permission. This is a new requirement as we call it out in the docs.

We need to basically give them one final prod, and set a new deprecation date. It impacts 57 teams. 

### Format
One email, targeted to the 57 teams, via Customer.io. 

### Previews
...

**Comment by joethreepwood** [comment]
- [ ] Joe to build the Customer.io segment

**Comment by joethreepwood** [comment]
<img width="715" alt="Screenshot 2023-10-31 at 17 02 13" src="https://github.com/PostHog/meta/assets/84011561/bd98ebff-b069-40c6-90ff-fdacaf9a7c03">

Let's go simple and direct. We did a personal email last time, so this may have more cut through now. 

OK with you @tomasfarias ?

**Comment by tomasfarias** [comment]
@joethreepwood Looks great! I assume it's linking to the BigQuery docs?

**Comment by joethreepwood** [comment]
It does. I'll build the segment and get this done ASAP.

**Comment by joethreepwood** [comment]
OK, cohort here: https://app.posthog.com/cohorts/48234

<img width="613" alt="Screenshot 2023-11-01 at 12 09 04" src="https://github.com/PostHog/meta/assets/84011561/5b9e8dd4-c3f6-4ba8-b7ea-58202f64de43">
