### ISSUE TITLE
Messaging: BigQuery Migration (EU)

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#148]
### Context
We missed EU users in [a previous deprecation notice](https://github.com/PostHog/meta/issues/147). Luckily, we're extending the deadline anyway, so we can roll an update out to them which still gives them time. 

### Audience / Targeting
Tomas has provided [a list of impacted EU users](https://posthog.slack.com/archives/C0374DA782U/p1698835874930539?thread_ts=1698764423.476469&cid=C0374DA782U). 

### Resources, timeline, responsibilities
A single message, essentially combining messages from https://github.com/PostHog/meta/issues/137 and https://github.com/PostHog/meta/issues/147

### Preview
Coming soon

**Comment by joethreepwood** [comment]
Cohort: https://app.posthog.com/cohorts/48235

**Comment by joethreepwood** [comment]
<img width="743" alt="Screenshot 2023-11-01 at 13 30 44" src="https://github.com/PostHog/meta/assets/84011561/8d3c6d18-abba-4996-9f66-2af38326c024">

For your approval, @tomasfarias

**Comment by tomasfarias** [comment]
Looks perfect! I would perhaps omit the "you can disable the old export app" as we disable that as part of the migration, and if users disable it early they could miss data. This data can be re-exported, but I rather err on the side of having more data than less data.

**Comment by joethreepwood** [comment]
<img width="569" alt="Screenshot 2023-11-01 at 13 51 08" src="https://github.com/PostHog/meta/assets/84011561/7f9f1dee-9867-4099-8513-92436bd8dc3d">

Done, and scheduled! 

<img width="478" alt="Screenshot 2023-11-01 at 13 51 38" src="https://github.com/PostHog/meta/assets/84011561/0f289d92-c78e-4a49-b0f9-1779d91fc1df">
