### ISSUE TITLE
Hacktopia Hackathon (Dec 2) post-mortem

### ISSUE THREAD

**Issue by ivanagas** [PostHog/meta#156]
Details: https://github.com/PostHog/meta/issues/142

Team: @fuziontech @xrdt @raquelmsmith @chitalian

## What went well

- The Celo Center space was great for hosting. Lots of space for everyone, but everyone was still in the same space. Was great to have a mix of tables, desk, and couches to hack on. People who weren’t hacking (maybe 20%) had plenty of room to chat. Food had an obvious, central location too.
- Justin and the team at Helicone did a lot of work in advance to organize logistics, get attendees. Had a solid turnout, basically all in the ideal target audience. It was great to cohost with them because they had solid network of YC founders and people they knew who attended. They also knew the area around their office well which was useful. Cohosting is definitely the right move.
- We gave out a lot of merch and people were excited by it. Hats went first, men’s hoodies went next (L, M were most popular), a small amount of shirts and most of the women’s hoodies and stickers were left. Merch was especially powerful when you gave it to someone personally, usually sparked a conversation.
- People seemed quite happy with amount of coffee, pastries, lunch, snacks, water (plain and sparkling), and pizza (amazing). Buying a lot of water and snacks is important. Costco is a good deal. Demand for food increases to fill supply.
- The highlight for me was spending some time with PostHog users and founders, learning about what they liked about PostHog, and talking marketing. Hanging out with team was great too. Mintify hosted a YC dev tools mixer the night before where I met some cool people too. It’s energizing to be around people who are such big fans of PostHog.
- Took lots of photos, recorded demos and shared right away. Having a Slack helped share some details, but only a small percentage actually joined (could have launched this earlier).
- Poster was beautiful, in a great spot, and was talked about a lot.

## What to improve on for next time

- The actual hacking had little to do with PostHog. Some asked for AI credits. It definitely felt like a hackathon sponsored by PostHog rather than a PostHog event. This meant there wasn’t a lot of post-hackathon marketing to do, maybe an email.
- The hackathon happened in teams, but the prizes were for individuals, which some people didn’t like.
- The theme was unclear/changing until the last minute, and not sure how much it actually mattered in the end.
- A little less than half of the registered attendees actually showed. I think we could have done a better job building hype in the week before, but this requires a much larger marketing effort on our side. Getting people to show up requires a lot of follow up.
- Pitches went well, but some did need to be cut off (Justin handled well). 11 teams ended up pitching and filled our time for pitches. People will just shill their own stuff if you let them.
- Need more signs and labels for things like where to go, wifi, washroom, vegetarian options, that merch is free, etc.
- It is a lot of work. If we host another one, it might be worth it to get an event organizer to help with all of this.
- Some miscommunication about lunch and location, but minor and happens. Sending out an event invite with the location attached was a good idea.
- Should have more stuff to identify that we are from PostHog and are the organizers. By giving out merch, people couldn’t really tell.

**Comment by chitalian** [comment]
In addition to what Ian is saying...

Operation stuff
- Limiting who presents (We pick the top 7 projects)
- giving a TLDR on how to use the microphone
- Change prizes to items that are redeemed later (so we can use gift cards)
- Clear doc for food and ownership
- Bring a tripod and HDMI Splicer + Elgato for recording screens. 
- Better marketing drip campaign
- We should collect Twitter and Linkedins for Hackers to verify participants and enforce on entry
- Having a process where we tweet the chain of projects
- Signs night before and do the vetting night of
- Can give helpful hints on what makes a good presentation
 
 Other things Justin noticed
 - A ton of people came right at the end. (Like VCs, and other interested people)
 - We should encourage this behavior. Maybe we can change the "Demos" to be a separate invite.
 
Prepare a deck with an outline that contains the following elements to send out
1. This is the theme
2. These are the rules for Hacking
 - Rules around bringing work you've already worked on
 - NOT DOING PITCHES FOR YOUR STARTUP 😤
3. House Rules
 - 0 tolerance for harrasment
 - We CAN AND WILL ask anyone to leave
 - Open invites should just be for hackers.

**Comment by chitalian** [comment]
More coffee
