### ISSUE TITLE
Messaging: Hackathon follow-on

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#158]
# Messaging

### Context
A short email to attendees of the PostHog x Helicone hackathon. 

### Goal
Tracking sign-ups in a 2-week conversion window. 

### Format
1x email, from me. 

### Audience / Targeting
Targeted list. 

### Previews
1x email to send this week, linking to an updated Deskhog printable from @lottiecoxon - link to be added shortly. 

<img width="558" alt="Screenshot 2023-12-05 at 12 03 23" src="https://github.com/PostHog/meta/assets/84011561/18492cf4-9cca-4e54-a26d-552aa87084ae">

**Comment by joethreepwood** [comment]
@ivanagas want to give me a quick y/n in place of a review?

**Comment by ivanagas** [comment]
Looks good 😄

**Comment by joethreepwood** [comment]
Sent.
