### ISSUE TITLE
PM Thought Leadership Articles

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/meta#16]
To help build credibility (particularly with Product Managers and Data folks), I'd like to create a series of thought leadership articles that are not specifically about our product but about general best practices for product managers:

* **How to be less reactive and more strategic** - Identify opportunities to focus and get ahead of your customers needs, how do you solve multiple problems at the same time with one approach. What does a good but quick strategy look like? How to push back on reactive work?
* **How to think really big** - Its difficult to hit the balance of thinking really big but staying grounded, identifying the world-level questions that need to be answered in your industry, connecting the dots to your current state and breaking down a huge ambiguous problem into something tractable
* **How to work out what your users need** - There's many ways to understand what your users need, its key to use many of them, from interviews to surveys, aggregated data, session recordings etc
* **Defining your core product metric** - To make progress really fast its key to have a single metric that multiple teams can focus on, how do you go about defining such a metric, what are the common pitfalls? How to evolve the metric over time? Knowing when a metric (no matter how good) is the wrong way to approach a problem?
* **How to prioritize without data** - It's not always possible to get data or data in sufficient quantities to prioritize work on a product, combining together different types of qualitative data from user interviews, competitive analysis and broader experience can help you make the right calls without any data.
* **PMs create confidence** - The primary value of PMs in particular Senior PMs is not to tell people what to do or make decisions for them, but to give others the confidence they need to make great decisions fast and build a better product. How to build confidence (using data, user interviews, knowing your limits, etc) , how to undermine confidence (flip-flopping, lack-of transparency, etc)
* **Do PMs actually add value** - If you're working with an engineering team is common to see them shipping tones of new features which make the product better, but its not clear that as a PM you did anything to directly make this happen, in fact most work as a PM is indirect - which makes it harder to validate and measure in the short term. Example scenarios, ordering is critical, getting the long-term direction right, missing the big wave
* **Build tools not processes** - As organizations grow it's incredibly tempting to enforce standards using processes, however, processes generally take more effort to follow than making it up as you go along, the only way to truly make change is by building tools that make the path of least resistance "the right way"
* **Product experimentation for beginners** - Experimentation can be really complex, however there are some neat and simple techniques to give you an understanding if you've built a new feature that's better or worse than the old feature
* **Communicating ultra clearly** - For everyone in an organization communicating ultra-clearly cuts time, mistakes and can save lives, this will cover examples from railway safety to product management where absolute clarity has made a huge difference and will share simple approaches to structure communication to increase clarity
* **Influence without authority** - In an autonomous organization, no-one has authority, the only way to get stuff done is by influencing others to do it, this is not easy - there are a number of great ways using data, etc. to help influence others
* **How to validate product market fit** - Do we have product market fit? Is a very common question a product manager will ask themselves, there's no universal standard for measuring it, instead of proposing it I will share the dimensions you can use to define a bar for product market fit that works for your product
* **How to do more of what you do best** - How to think about your strengths and weaknesses as well as what you like most and least to do in order to increase the amount of impact and enjoyment you have at work
* **How to generate new scope** - To grow as a PM you can't just execute on your current goals you need to create new opportunities to work on and execute successfully on them too - this will talk about how to identify new scope, how to shape it and how to turn it from something ambiguous into something you can execute on
* **When conflict is great** - It's natural to be hesitant about conflict but in product management conflict is often the key to getting to the best solution to a problem, how to find the right conflicts? How to know when conflict is good or bad? How to resolve conflicts? How to handle escalations? How to create more conflict when you need it?
* **A PM should use their product more than 80% of users** - A common pitfall of PMs is to build a product which they never use - if you're not using it as much as the top 20% of your users, you're not going to have empathy for their problems and you'll likely prioritize badly and build the wrong things. How to find the time to do this? How to encourage others to dogfood? How to make your product more dogfoodable? How to give feedback on your product? How to avoid overbearing to your own feelings about the product?
* **Product Led Growth 101** - What is product led growth, why does it matter and how to succeed at it.

I will get started on a couple of these right away - but would appreciate any feedback on ones you think I should focus more or less on @piemets @shehuphd @joethreepwood @jamesefhawkins

**Comment by marcushyett-ph** [comment]
@piemets and I briefly chatted about this but since It's a fair amount of investment to write each of of these and the audience is PMs at large and not specifically PMs who may or may not need to buy product analytics software right now. 

e.g. Should it also be posted on medium for organic distribution with the PM community, or does this detract from it being on our blog? How should I distribute this in the PM communities I'm part of - being on the blog of a company might make it look biased etc? Should I stop overthinking this? etc.

**Comment by piemets** [comment]
I'm super excited about this! I think those articles that are connected more directly towards our value props would be the ones I'd be naturally inclined towards, as it'll help us share a more consistent message across our different channels:

- How to work out what your users need
- Defining your core product metric 
- Product experimentation for beginners
- A PM should use their product more than 80% of users 

I think generally at the end of these articles where it's not massively contrived, we should mention how PostHog is relevant in helping you do this stuff - we can be quite jokey ('of course we're biased, but we built PostHog to help you with this stuff - and it's free!'). 

(I'm definitely not suggesting you shouldn't post stuff that isn't directly connected to Posthog btw!)

In terms of distribution, I'd keep it simple - we can post it on our blog and if you want to put it on a personal Medium as well for example, that's fine. We're very far from the point of having a sophisticated distribution strategy which needs optimising, so I wouldn't worry about that too much.

**Comment by marcushyett-ph** [comment]
Sounds great - thanks for your feedback.

Will update this thread with links to in-progress articles...perhaps I can leave the weaving in of PostHog to the end of the article to @shehuphd's talents, but makes sense to connect the article to our product in some way.

**Comment by piemets** [comment]
> perhaps I can leave the weaving in of PostHog to the end of the article to @shehuphd's talents

I think you can also do this organically and genuinely in some of the articles - for example 'once I've defined my core product metric, this is how I track it in PostHog, though of course similar products like X Y and Z will also enable you to do the same thing.'

**Comment by joethreepwood** [comment]
This sounds like (a lot of) great work! Where possible I'd be very happy to either help with polishing drafts or taking on some of the writing so that we're not bottlenecking you away from other things. I'll let you pull me in where helpful. 

Topic-wise, I'd steer towards anything with a product, user or data focus as this has the most overlap. Ideas like 'How to understand what users need', 'Product experimentation for beginners' and 'Defining your core product metric' all seem great. Anything with 'How To' in the headline is also good from an SEO perspective. 

'How to communicate ultra clearly' and 'When conflict is great' sound interesting, but I'm not sure we should be writing about them now or that our audience would know to trust PostHog as a really good source for these topics. 

Regarding distribution, I also agree with @piemets . Keep it simple, throw it up on the blog and go through the usual content release checklist. I also would say that this content doesn't need to be very long or detailed; if we see it performs well then we can create longer-form content in other ways later. For now, 2x short articles are better than 1 long one. 

I'd also suggest we revisit these ideas when https://github.com/PostHog/company-internal/issues/370 is complete. Annika's SEO audit will suggest some additional priorities and ideas.

**Comment by shehuphd** [comment]
These are great, @marcushyett-ph - would also add `How to validate product market fit` to the priority list as it's relevant to the set of problems we're helping our users solve.

Happy to help with polishing articles where necessary. What cadence are you thinking of for these articles - one a week?

**Comment by marcushyett-ph** [comment]
@shehuphd @joethreepwood thanks....

I'd really appreciate any crafting and shaping of my drafts (my written English is generally very bad), I can should be able to churn out the raw content quite quickly though.

Great feedback on quantity of length @joethreepwood - I will aim for this. Hopefully if we see a few topics are resonating well we can dive deeper and create more and longer content in that niche.

@shehuphd hopefully I can do more than 1 per week - aiming for 3 this week... but will depend on other priorities etc.

**Comment by marcushyett-ph** [comment]
Draft 1: ["How to work out what your users need" ](https://docs.google.com/document/d/1jgZXkn4NXCDNltv0vSV2WOMH43p_2aqdrwexcbYjluM/edit?usp=sharing)

**Comment by joethreepwood** [comment]
> Great feedback on quantity over length @joethreepwood - I will aim for this. Hopefully if we see a few topics are resonating well we can dive deeper and create more and longer content in that niche.

Sounds great. A good medium-term follow-on goal for this will be, if they perform well, to look at networking pages together and expanding them into other types of content.

**Comment by shehuphd** [comment]
@marcushyett-ph First draft looks great! Tightened the [copy](https://docs.google.com/document/d/1jgZXkn4NXCDNltv0vSV2WOMH43p_2aqdrwexcbYjluM/edit#heading=h.skqszc9act1a) and left a few edits for you to review/accept before we create a PR for it.

**Comment by marcushyett-ph** [comment]
Draft 2: ["A PM should use their product as much as their users"](https://docs.google.com/document/d/1HNA42ixJJfpC6eRQpSvIKCdvMpgd4TiM7lHg-luuK_E/edit#)

**Comment by marcushyett-ph** [comment]
Draft 3: ["How to validate B2B product market fit"](https://docs.google.com/document/d/1SpX6FUVnNRgRmT-vbT6iEHWdr1sU7FOdhjc_v_VD87I/edit?usp=sharing)

**Comment by jamesefhawkins** [comment]
Feedback on the above:

- These are incredibly valuable. First box ticked.
- They're very dry as they're reasonably high level. Could we get a little more specific? Often I will hear "talk to users" "build for a handful of people that love you", but what do these actually mean? How is PostHog specifically tackling these? Do we have an anecdote for some of the points we're making?

- Some of the slightly more unusual titles I think will land better ie "how to think really big" is something I'd love to read. I'd not want to read "A PM Should Use Their Product more than 80% of their users", as that's just clichéd advice. That said, someone browsing our blog that found us through something clickbait-ier will perhaps then read it if the first article is decent.
- If an article is more generic ie "Product Led Growth 101", we need to go much further with the content to make it compelling. How do we make this better than what ie [entire orgs dedicated to talking about this](https://productled.com/), or similarly for the article on "how to validate product market fit". Whereas "how to think really big" is something I've never read about. It is valuable covering both as some will land on HN, whereas the more generic ones will land better on Google

**Comment by marcushyett-ph** [comment]
> They're very dry as they're reasonably high level. Could we get a little more specific? Often I will hear "talk to users" "build for a handful of people that love you", but what do these actually mean? How is PostHog as a company specifically tackling these problems? Do we have an anecdote for some of the points we're making?

Yeah I think this is good feedback - It's generally much easier to write something more generic as individual real-world examples rarely fit the global pattern. I can try to weaving in some PostHog (or other) specific examples going forward.

> Some of the slightly more unusual titles I think will land better ie "how to think really big" is something I'd love to read. I'd not want to read "A PM Should Use Their Product more than 80% of their users", as that's just clichéd advice. That said, someone browsing our blog that found us through something clickbait-ier will perhaps then read it if the first article is decent.

Would definitely appreciate any support on making the titles catchy - these are very much initial thoughts on a title based on the content

> If an article is more generic ie "Product Led Growth 101", we need to go much further with the content to make it compelling. How do we make this better than what ie entire orgs dedicated to talking about this, 

For this I feel this article is more "So you've heard about product led growth, but how do you ACTUALLY do it (using PostHog)" - which should be how we add incremental value over what's already about there...

**Comment by piemets** [comment]
> Something like 'What is a user funnel?' is something we can outsource at any time, but 'How to optimize your sign-up flow for a clinical trial' is a lot more nuanced.

Yep agree with this bias for doing something industry-specific, although @joethreepwood how should we approach trying to include helpful keywords (if at all)?

For example, looking at our most recent SEMRush report, it would probably be worth writing content that includes some of these keywords:
- data warehouse business intelligence
- big data analytics
- customer engagement analytics
- customer retention analytics
- conversion funnel optimisation
- enterprise data analytics
- (plus more in the attached PDF - look at p.7 onwards as we want to start with stuff outside the top 100)

[SEMrush-Position_Tracking__Overview_(organic)-posthog_com-7th_Oct_2021.pdf](https://github.com/PostHog/meta/files/7322398/SEMrush-Position_Tracking__Overview_.organic.-posthog_com-7th_Oct_2021.pdf)

I think my recommendation would be to take the above and then phrase the title & content around them so we're still taking an easy opportunity to hit valuable keywords. So to build on @marcushyett-ph's suggestions above, things like 'How to optimize your conversion funnel for a clinical trial' or 'How to do HIPAA-compliant big data analytics' would be both really interesting and unique pieces of content _and_ hit relevant keywords for us.

**Comment by charlescook-ph** [comment]
I think this has been superseded by @andyvan-ph 's work on our broader content strategy, so closing this particular issue
