### ISSUE TITLE
Messaging: Year In PostHog

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#160]
# Messaging

### Context
[We're doing it again!](https://github.com/PostHog/product-internal/issues/403) 

### Goal
Get people clickin', sharin' their year in posthog

### Format
1x email to all users who have logged in in the last 60 days, and who are subscribed to marketing emails. 15,500 approx total (vs 5,000 last year). 

To be sent on Thursday 14th. 

### Questions
- Do we need to segment this by EU and US Cloud again, or can we send just to the single `https://app.posthog.com/year_in_posthog/` address @pauldambra ?

### Preview

Proposed email: 

<img width="1017" alt="Screenshot 2023-12-06 at 14 57 42" src="https://github.com/PostHog/meta/assets/84011561/c85c01a4-4623-49c2-ba89-55d356fdda35">

First link goes to `https://app.posthog.com/year_in_posthog/` and second link goes to [this banger](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by joethreepwood** [comment]
Feedback or thumbs up, please @charlescook-ph @pauldambra @lottiecoxon

**Comment by pauldambra** [comment]
It'll need to be app.blah and eu.blah... I think 🤔 Although we have the login redirection stuff now, no?

Will figure this out and let you know

**Comment by charlescook-ph** [comment]
Thumbs up not a heart - do we want to do more? Or is that too much work? e.g. to add surveys?

**Comment by pauldambra** [comment]
@charlescook-ph https://github.com/PostHog/posthog/issues/19128 (I can't commit commit because I have to focus on mobile replay)

**Comment by joethreepwood** [comment]
> Thumbs up not a heart - do we want to do more? Or is that too much work? e.g. to add surveys?

We're doing some more within the feature, and we're widening the scope so that 3x more users get invited this year. 

We _could_ do a lot more promo-wise. We could announce this on ProductHunt or HN, we could widen the email targeting even further, we could start a countdown clock on the website and we could even include it in the 3000 launch... but I think that's all overkill compared to the feature itself, as per retro last year. 

One year we _really_ should plan ahead for this properly and max the feature out somehow!

**Comment by charlescook-ph** [comment]
> We're doing some more within the feature,

All good! I meant the feature itself, rather than promoting it

**Comment by joethreepwood** [comment]
> It'll need to be app.blah and eu.blah... I think 🤔 Although we have the login redirection stuff now, no?
> 
> Will figure this out and let you know

Segmenting isn't a problem FYI.

**Comment by joethreepwood** [comment]
I've split the campaign out into US and EU variants. 

US: 8100 users. 
EU: 4000 users.

**Comment by joethreepwood** [comment]
<img width="1035" alt="Screenshot 2023-12-11 at 16 35 52" src="https://github.com/PostHog/meta/assets/84011561/3914ef9e-9d13-4a77-a8dc-2a748902d4e2">

New image, courtesy of https://github.com/PostHog/posthog.com/issues/7312
