### ISSUE TITLE
Messaging: Missing Tax ID EU & UK

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#161]
# Messaging

### Context
We need to send a short reminder to EU and UK customers who haven't shared a Tax ID yet. 

### Format
1x email

To be sent on 13th December

### Audience / Targeting
[List from Fraser](https://posthog.slack.com/archives/C0687TXM941/p1702055833995319)

### Previews
_Got previews of the copy, the emails, the content? Shove them here._

**Comment by joethreepwood** [comment]
<img width="1250" alt="Screenshot 2023-12-11 at 14 07 14" src="https://github.com/PostHog/meta/assets/84011561/fd5f61a6-475f-44e8-9413-42ca3520e103">

Please comment with your feedback or approval, @fraserhopper

**Comment by fraserhopper** [comment]
Looks good to me! 

We can try and figure out a more automated method of this in the new year :-)

**Comment by corywatilo** [comment]
Darker text, ideally

**Comment by joethreepwood** [comment]
The text will be standard - that's just my shoddy screenshotting with the text box selected.

**Comment by joethreepwood** [comment]
<img width="331" alt="Screenshot 2023-12-11 at 16 25 06" src="https://github.com/PostHog/meta/assets/84011561/2d3c018b-ea50-4192-be99-ebf4274c2c5e">


Fyi @fraserhopper and @simfish85 @camerondeleone this is now scheduled
