### ISSUE TITLE
Messaging: Auth merge between cloud and website

### ISSUE THREAD

**Issue by MarconLP** [PostHog/meta#162]
# Messaging

### Context
We are going to merge the auth between cloud and website. In the future users will login to create posts/questions using their cloud account
![2023-12-14 at 08 14 51](https://github.com/PostHog/meta/assets/13001502/201bf3a5-a620-40ba-a9a9-3a9613163be6)

### Goal
Make users aware of the change. They should open a ticket if they want their account to be attached to another cloud account.

### Format
Blog & Email

### Audience / Targeting
All current forum users (1661), letting each individually know if their account has been:
- (753) merged with an existing us account, since they have an us account and maybe a eu account aswell
- (409) merged with a new us account, since they don't have a cloud account at all
- (206) merged with an existing eu account, since they only have an eu account
- (212) nothing, since the email hasn't been confirmed yet

cc: @joethreepwood 
related: https://github.com/PostHog/posthog.com/issues/5847

**Comment by joethreepwood** [comment]
Great! 

There are a few things to do here, I think.

1. We can add this to https://github.com/PostHog/posthog.com/pull/7307/
2. We can include this in the email to Slack users as part of that announcement
3. We should, as you say, message existing forum users to tell them how their accounts are merging

@smallbrownbike for 2. how will this impact your plan to give these users an achievement?

@MarconLP for 3, where can I get the user email lists for each of these segments?

**Comment by joethreepwood** [comment]
Also, @MarconLP How will this function for users who are on self-hosted instances, or who don't have Cloud accounts set up? Will they need to create one in both cases?
