### ISSUE TITLE
Messaging: Slack closure email

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#163]
# Messaging

Due to https://github.com/PostHog/meta/pull/152

Waits for https://github.com/PostHog/meta/issues/162

Waits for https://github.com/PostHog/posthog.com/pull/7307

## Details

1x email to 5,000 users exported from the Slack group

First draft: 
<img width="700" alt="Screenshot 2023-12-14 at 17 05 07" src="https://github.com/PostHog/meta/assets/84011561/6c0826f4-3fb2-413f-a392-0eceb2506cd3">

CC @smallbrownbike @MarconLP 

@andyvan-ph and @charlescook-ph for approval

**Comment by joethreepwood** [comment]
<img width="997" alt="Screenshot 2024-01-10 at 13 47 14" src="https://github.com/PostHog/meta/assets/84011561/e9f7da83-ca6c-4af9-a7c8-c1aa1be708f3">

Slight language tweaks. 

I'd like to send this tomorrow alongside https://github.com/PostHog/posthog.com/pull/7307 if @andyvan-ph can give me a quick 👍

**Comment by charlescook-ph** [comment]
If it's been a great place to swap ideas and chat, why are we closing it? Would probably say something like it worked when we only had X users (either PostHog or Slack) but now we've got Y people, we've outgrown it, it doesn't keep history, lots of extra features etc. we've built ourselves?

Sorry for the extra hassle (and not giving timely feedback), but I also wonder if it coming from @jamesefhawkins directly will land more strongly as well - a more heartfelt founder type thing?

**Comment by joethreepwood** [comment]
> If it's been a great place to swap ideas and chat, why are we closing it? Would probably say something like it worked when we only had X users (either PostHog or Slack) but now we've got Y people, we've outgrown it, it doesn't keep history, lots of extra features etc. we've built ourselves?

Sorry, should have been clear -- this is covered in the blog post, which I was going to add a link to within the copy when it is published. Don't think we need to explain all the details in the post, personally. 
 
> Sorry for the extra hassle (and not giving timely feedback), but I also wonder if it coming from @jamesefhawkins directly will land more strongly as well - a more heartfelt founder type thing?

Happy to go this route. @jamesefhawkins if you want to send me some copy, or I can draft if you prefer? Once I have that I can set it to come from you via C.io.

**Comment by joethreepwood** [comment]
<img width="445" alt="Screenshot 2024-01-17 at 13 55 10" src="https://github.com/PostHog/meta/assets/84011561/beca4253-0f67-4cd9-8427-5c99c1a03375">

Lacking further feedback or new copy, I've scheduled this in for Friday. Happy to take amends until then, however.
