### ISSUE TITLE
Messaging: Adding notebooks to onboarding

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#164]
<img width="818" alt="Screenshot 2023-12-15 at 11 46 50" src="https://github.com/PostHog/meta/assets/84011561/ee21bb6c-1e20-428b-b6a5-6e9356ccc2cd">

Re-adding this email into the onboarding flow, replacing the push for survey templates as originally planned for Onboarding 4.0

Part of https://github.com/PostHog/meta/issues/139

Currently marked as Do Not Send. Just needs flipping to Send Automatically.

**Comment by ivanagas** [comment]
Could it just say "Stay organized with notebooks" ? We have the PostHog logo above and it is in the sentence below, maybe PostHog overload?

**Comment by raquelmsmith** [comment]
Curious why you decided to do this instead of surveys?

**Comment by joethreepwood** [comment]
> Curious why you decided to do this instead of surveys?

We do already have an upsell for surveys, if someone isn't subscribed to it. The email this replaced was just about the survey templates and encouraging users to try them. But, given that those templates are the first thing you see when you click on Surveys, it didn't seem super valuable.

**Comment by joethreepwood** [comment]
Done!
