### ISSUE TITLE
Messaging: 3000 & Notebooks announcement

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#165]
# Messaging

### Context
As per https://github.com/PostHog/meta/issues/139 this is an email we'll send one week after launch.

I've tweaked this from the initial `7+ days since log in` targeting because it's too noisy. It would hit 88,000+ users. 

This now targets all users who _have_ logged in 1+ times in the last 60 days, but _not_ within the last 7 days. 13,000 users. 

Goal is to tell them, briefly, about 3000 and the notebooks launch. 

### Goal
Login within 7 days. 

### Format
1x email, 7 days after 3000 roll out to 100% users.

**Comment by joethreepwood** [comment]
<img width="1261" alt="Screenshot 2023-12-15 at 13 07 53" src="https://github.com/PostHog/meta/assets/84011561/5f75561f-aca1-4cc5-973a-52bc3a3d258b">
<img width="1219" alt="Screenshot 2023-12-15 at 13 08 07" src="https://github.com/PostHog/meta/assets/84011561/dbc59bf9-cebf-4d7c-88ed-af63950d8f57">
<img width="1216" alt="Screenshot 2023-12-15 at 13 08 18" src="https://github.com/PostHog/meta/assets/84011561/b519d183-56a4-439e-bc78-a9e1b128e8a0">


Would love a quick check @ivanagas @andyvan-ph 

The video image is placeholder. That'll be updated to embed or link to Ian's video.

**Comment by ivanagas** [comment]
Looks good, will the thumbnail on the video automatically generate?

**Comment by ivanagas** [comment]
Video: https://youtu.be/B73WnVRi0ko

**Comment by joethreepwood** [comment]
<img width="1103" alt="Screenshot 2023-12-18 at 12 12 32" src="https://github.com/PostHog/meta/assets/84011561/dbefada3-650f-4fd5-bb15-d715ab01518b">

Updated header.

**Comment by joethreepwood** [comment]
<img width="458" alt="Screenshot 2023-12-19 at 11 19 17" src="https://github.com/PostHog/meta/assets/84011561/ab4685ff-cf1b-45ac-99a0-ec467c170ac4">

Scheduling this in.
