### ISSUE TITLE
Messaging: API Key Fault response

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#166]
# Messaging

We had a bit of an issue with API keys, impacting about 26 individual users. 

We've fixed it, but it needs an email still. 

1x email to all users, sent by C.io ASAP.

**Comment by webjunkie** [comment]
The issue for these 26 is that these new keys stopped working when we rolled back, and we only made them working today. So I'd slightly alter the text.

For all other users with old keys though it's true that these had problems during the brief period on the 14th only.

**Comment by joethreepwood** [comment]
<img width="652" alt="Screenshot 2023-12-15 at 15 37 30" src="https://github.com/PostHog/meta/assets/84011561/bfc79b3f-7f5f-4f60-8e3b-48c1db0b4889">

@webjunkie Better?

**Comment by webjunkie** [comment]
That's fine with me. Thanks!

**Comment by simfish85** [comment]
Do we have the impacted customer list?

**Comment by joethreepwood** [comment]
Approved async, changed to come from me, scheduled for 1 hour from now. 

Simon, sent you the list.
