### ISSUE TITLE
Messaging: YC giveaway

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#169]
# Messaging
We've got all these cool new stickers. Lets give some of them away!

We have a bigger giveaway planned for current batch participants, but right now I'd like to generate some WOM by sending an email which invites all YC and startup teams to claim some free stickers.

It'll be a simple, direct email from me announcing that we've got some new merch and that we'd like to offer them some free goodies as a thanks for continuing to use PostHog - but it's WHILE STOCKS LAST. 

We'll provide a link as a Printfection Giveaway campaign. We have four sticker sets, so I'll create four campaigns and users will be assigned randomly to one of the four offers. We have around 400 users in the startup program currently.

**Comment by joethreepwood** [comment]
<img width="802" alt="Screenshot 2024-01-02 at 16 46 44" src="https://github.com/PostHog/meta/assets/84011561/3b2ae2f9-60f4-4e55-a3c0-767c4f5bd536">


CC for quick approval and thoughts @andyvan-ph @lottiecoxon

**Comment by joethreepwood** [comment]
<img width="755" alt="Screenshot 2024-01-09 at 11 17 13" src="https://github.com/PostHog/meta/assets/84011561/23a5552f-7d05-4375-bb4f-e7d20ffaa6f3">

Small tweak to reflect some Printfection quirks. 

I'm going to focus this on _just_ YC teams, given stock levels, and limit it to 100 redemptions so we don't go out of stock. 

Will include a packing note from Lottie that asks for tweets.

**Comment by joethreepwood** [comment]
@charlescook-ph After giving it some thought, I'd like to send this out ASAP to increase visibility with the current batch, rather than waiting for the merch store redesign. This user path won't actually take users through the store anyway, unless they click the first link in the email. 

Any objections if I send this week?

**Comment by charlescook-ph** [comment]
Go for it 👍

**Comment by joethreepwood** [comment]
Sending at 9PM today, to arrive midday SF time.

**Comment by joethreepwood** [comment]
23 redemptions in the first 24 hours!
