### ISSUE TITLE
Marketing Goal: Make sure we have good Getting Started content for all products

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#171]
### Context

My second goal for this quarter is to "make sure we have good getting started content for all products". While it's worded to focus on content, it was discussed to be broader than that - basically, use any levers we can to make sure users can get started quickly with any product. Content is just the main lever which Marketing directly owns.

Other teams (notably @raquelmsmith and @xrdt ) are also working on similar areas, and I've started putting myself at their disposal and feeding into relevant projects where (hopefully) helpful.

Here, I'm going to plan some further efforts across this quarter to hit this goal. 

### Establishing best practices for each product

This goal shouldn't mean just doing a quick pass on the content and processes we have now. It should mean making sure that we have good getting started steps for _every product going forward_. 

So, we should set some minimum best practices for every product now and in the future. These are the things we will do before taking any product out of beta. 

- Ensure the product has at least one customer story created for it within 3 weeks of launch
- Ensure we publish best practice content for the product and link to it from docs
- Ensure that products have at least one pre-made template (or similar) for users
- Ensure the product has at least one tutorial created for it at launch
- Ensure the product has a robust docs page, and product page if needed
- Ensure launch activities (such as changelog) link clearly to the docs
- Ensure the product is added to email and in-app onboarding flows

I tend to lead marketing on new product launches, so I can roll these into those plans - however I'd like to get input from @benjackwhite and @annikaschmid on the point around templates. Some products (analytics, surveys, notebooks) have them already, but I'm interested if we could add more, such as pre-made playlists for replays, and roll-out templates for experiments and flags. 

### Things I'm going to do

A mix of big projects and micro-improvements.

- [x]  https://github.com/PostHog/meta/issues/172
- [x] https://github.com/PostHog/posthog.com/pull/7485
- [x] https://github.com/PostHog/posthog/issues/19680
- [x] https://github.com/PostHog/posthog/issues/19683
- [x] https://github.com/PostHog/posthog/issues/19681
- [x] https://github.com/PostHog/posthog.com/pull/7443 
- [x] https://github.com/PostHog/posthog.com/pull/7795
- [x] https://github.com/PostHog/posthog/pull/20216
- [x] https://github.com/PostHog/posthog.com/pull/7307
- [x] https://github.com/PostHog/posthog.com/issues/7567
- [x] https://github.com/PostHog/meta/issues/175 
- [x] https://github.com/PostHog/posthog.com/pull/7807
- [x] https://github.com/PostHog/posthog.com/pull/7747
- [x] https://github.com/PostHog/posthog.com/pull/7732
- [x] https://github.com/PostHog/posthog.com/pull/7796
- [x] https://github.com/PostHog/posthog.com/pull/7793
- [x] https://github.com/PostHog/posthog.com/pull/7662
- [x] https://github.com/PostHog/posthog.com/pull/7599 
- [x] https://github.com/PostHog/posthog.com/pull/7595
- [x] https://github.com/PostHog/posthog.com/pull/7815
- [x] https://github.com/PostHog/posthog.com/pull/7861
- [x] https://github.com/PostHog/posthog.com/pull/7858
- [x] https://github.com/PostHog/posthog.com/pull/7794 
- [x] https://github.com/PostHog/posthog.com/pull/7823/
- [ ] ~OR redirect `/docs/[feature]/tutorials` to `/docs/tutorials/[feature]`~ - [Deferring to W&D here](https://posthog.slack.com/archives/C01V9AT7DK4/p1707319605389039)
- [x] Opt-in daily tips email flow to sit alongside onboarding flow - https://github.com/PostHog/posthog.com/pull/7978
- [x] https://github.com/PostHog/posthog.com/issues/7993
- [x] https://github.com/PostHog/posthog.com/pull/8020

In addition, the content team is looking at [their own doc sprint](https://github.com/PostHog/posthog.com/issues/7754) to improve content across neglected docs.

### Feedback requested
The easy way to hit this goal would be to go heads-down and churn out a bunch of tutorials around basic topics. However, I don't think that's the actual solution. We already have a bunch of great tutorials and our docs are awesome. 

Instead, I want to focus on on making sure other processes _around_ the content work well to surface, enhance, and standardize that content. Hence: Pinned posts, adding videos, creating best practices. 

This approach veers a little away from the literal wording of the goal, so I'd love feedback from the marketing team if this approach is strongly opposed. @andyvan-ph @ivanagas @charlescook-ph @Lior539 

All other feedback, yells, etc, greatly appreciated too.

**Comment by benjackwhite** [comment]
Just on the replay front - the standard screen is fully controlled by the url so you can _sort of_ template things by just linking to replays with a bunch of filters pre built (e.g. recordings where active time is longer than 20 seconds, where they visit the pricing page etc.) 

Tricky bit (which applies to a lot of other things) is most of it's based on events so it's sort of dependent on their implementation.

**Comment by joethreepwood** [comment]
Another idea: 

**Onboarding 5.0.** 
This would basically flip our onboarding logic away from upsells. Instead, we'd update the flow in this way: 

- After two weeks, check: has user created 5 insights in two weeks?
- If NO: Email with content about getting started with analytics.
- If YES: Check if subscribed. If YES do nothing. If NO send upsell email. 

It would be a LOT more complicated to set up, but could help boost activation.

**Comment by joethreepwood** [comment]
> Just on the replay front - the standard screen is fully controlled by the url so you can _sort of_ template things by just linking to replays with a bunch of filters pre built (e.g. recordings where active time is longer than 20 seconds, where they visit the pricing page etc.)
> 
> Tricky bit (which applies to a lot of other things) is most of it's based on events so it's sort of dependent on their implementation.

Why can't we do what we did with templates? Off a user a selection of templates. If they click one that needs a particular event, ask them what that event is and then plug that in. (And ideally add a thing saying 'Don't have an event for this? Set one up here").

**Comment by xrdt** [comment]
> Why can't we do what we did with templates? Off a user a selection of templates. If they click one that needs a particular event, ask them what that event is and then plug that in. (And ideally add a thing saying 'Don't have an event for this? Set one up here").

This lines up with how growth has been thinking about [incorporating dashboard creation](https://github.com/PostHog/product-internal/pull/551/files#diff-81c87d8e075d474b8f7917645c5cc269a8348fefae6c996d7483d088760deda5R60) into the onboarding flow. One major new piece is letting users use the toolbar to create new actions on the fly.

**Comment by corywatilo** [comment]
> "Don't have an event for this? Set one up here"

[Field mapping](https://github.com/PostHog/posthog/issues/12021) wouldn't be hard to do, and it would unlock a lot of potential to make things way more useful out-of-the-gate.

**Comment by raquelmsmith** [comment]
> Onboarding 5.0.
> This would basically flip our onboarding logic away from upsells. Instead, we'd update the flow in this way (for every product and based on the activation targets):

I know this would be complicated but it seems like it might be worth it. If someone is struggling to find value in the first product they signed up for, it's probably unlikely that they will be interested in trying another product (at least for a while). I think it would be good to focus on getting people using their first product before we even think about getting them to try another one.

On an unrelated note: It's often easier to give feedback if you [open a PR](https://posthog.com/handbook/company/communication#requests-for-comment-rfcs) because you can comment line-by-line 🙂

**Comment by andyvan-ph** [comment]
> The easy way to hit this goal would be to go heads-down and churn out a bunch of tutorials around basic topics. However, I don't think that's the actual solution. We already have a bunch of great tutorials and our docs are awesome.

I mostly agree, but I suspect there are some gaps here and there. The bit that's missing, for me, is a destination. If someone asks us "what should I do next?" we should be able to say "go here, read these guides / watch this video" and leave them to it. We have some of this stuff in docs, blogs etc., but it's dispersed and hard to discover.

**Comment by joethreepwood** [comment]
> The bit that's missing, for me, is a destination. If someone asks us "what should I do next?" we should be able to say "go here, read these guides / watch this video" and leave them to it. We have some of this stuff in docs, blogs etc., but it's dispersed and hard to discover.

I'd say we just send them to the docs section for that product, or as a whole? I think it's hard to get more comprehensive than that. But I do agree we can improve some of that by bringing in more blogs, etc. Is part of what I want to do when I get to "Improve the 'Tutorials and Guides' section of the docs for each product" -- make it so it's not just a list of tutorials.

**Comment by joethreepwood** [comment]
## Ensuring best practices are applied to all existing products

### Product analytics
**Does it have at least one customer story associated with it?**
Yes. Hasura, Contra, YC and Speakeasy are all examples clearly linked on product page. 

**Does it have at least one pre-made template (or similar) for users?**
Yes. It has a library of dashboard templates made by Some Handsome Gentlemen. However, we could feature the templates better on the product page. [Have raised this with Website & Docs](https://posthog.slack.com/archives/C01V9AT7DK4/p1704814289218789). 

**Does it have at least one tutorial created for it?**
We have [lots](https://posthog.com/docs/product-analytics/tutorials) of tutorials, and we surface them well. I'll be adding these to Onboarding 5.0 too, to further build on this. 

**Does it have a robust docs page, and product page?**
Yes. A really good one, with some further docs improvements planned. 

**Does it feature in the email and in-app onboarding flows?**
Onboarding 4.0 currently features a lot of content and has dedicated upsell and after-sell flow. Onboarding 5.0 will build on this by adding distinct, personalized flows for each initial product selection. 

### Feature flags
**Does it have at least one customer story associated with it?**
Yes. Phantom, Contra, Speakeasy and carVertical are all examples clearly linked on product page. 

**Does it have at least one pre-made template (or similar) for users?**
No. We currently have no templates for flags, so I've raised a feature request. 

**Does it have at least one tutorial created for it?**
We have [a handful](https://posthog.com/docs/feature-flags/tutorials) of tutorials, and we surface them well. I'll be adding these to Onboarding 5.0 too, to further build on this. 

**Does it have a robust docs page, and product page?**
Yes. A really good one, with some further docs improvements planned. 

**Does it feature in the email and in-app onboarding flows?**
Onboarding 4.0 currently features a lot of content and has dedicated upsell and after-sell flow. Onboarding 5.0 will build on this by adding distinct, personalized flows for each initial product selection. 

### A/B experiments
**Does it have at least one customer story associated with it?**
Yes. YC, Vendasta and AssemblyAI are all examples clearly linked on product page. 

**Does it have at least one pre-made template (or similar) for users?**
No. We currently have no templates for experiments, so I've raised a feature request. 

**Does it have at least one tutorial created for it?**
We have [a handful](https://posthog.com/docs/experiments/tutorials) of tutorials, and we surface them well. I'll be adding these to Onboarding 5.0 too, to further build on this. 

**Does it have a robust docs page, and product page?**
Yes. A really good one, with some further docs improvements planned. 

**Does it feature in the email and in-app onboarding flows?**
Onboarding 4.0 currently features a lot of content and has dedicated upsell and after-sell flow. Onboarding 5.0 will build on this by adding distinct, personalized flows for each initial product selection. 

### Session replays
**Does it have at least one customer story associated with it?**
Yes. Hasura, Contra, Pry and Netdata are all examples clearly linked on product page. 

**Does it have at least one pre-made template (or similar) for users?**
No. We currently have no templates for flags, so I've raised a feature request. 

**Does it have at least one tutorial created for it?**
We have [a handful](https://posthog.com/docs/session-replay/tutorials) of tutorials, and we surface them well. I'll be adding these to Onboarding 5.0 too, to further build on this. 

**Does it have a robust docs page, and product page?**
Yes. A really good one, with some further docs improvements planned. 

**Does it feature in the email and in-app onboarding flows?**
Onboarding 4.0 currently features a lot of content and has dedicated upsell and after-sell flow. Onboarding 5.0 will build on this by adding distinct, personalized flows for each initial product selection. 

### Surveys
**Does it have at least one customer story associated with it?**
Yes. Purplewave is clearly linked on product page and CS hasn't asked for more. 

**Does it have at least one pre-made template (or similar) for users?**
Yes, surveys has a robust set of templates for users to choose from as an initial product step. 

**Does it have at least one tutorial created for it?**
We have [a handful](https://posthog.com/docs/surveys/tutorials) of tutorials, and we surface them well. I'll be adding these to Onboarding 5.0 too, to further build on this. 

**Does it have a robust docs page, and product page?**
Yes. A really good one, with some further docs improvements planned. 

**Does it feature in the email and in-app onboarding flows?**
Onboarding 4.0 currently features a lot of content and has dedicated upsell and after-sell flow. Onboarding 5.0 will build on this by adding distinct, personalized flows for each initial product selection.

**Comment by joethreepwood** [comment]
Things we can improve on the docs and tutorials pages (and other related places)

- [ ] Adding some relevant case studies to the guides section: ‘How other teams use [Feature]
- [ ] Add lists of useful posts too each section: ‘Best practices for [feature]’
- [ ] Add a template list to /docs/surveys
- [ ] Add a ‘Follow along in the app’ button to tutorials, which reopens the tutorial in the app sidebar
- [ ] Add the lightbulb search tip to 
- [ ] Ensure all tutorials are linked on the main tutorial page (some aren’t)
- [ ] OR redirect `/docs/[feature]/tutorials` to `/docs/tutorials/[feature]` - these basically overlap, but one needs to be maintained

**Comment by joethreepwood** [comment]
I'm [planning](https://docs.google.com/document/d/1McQHYn2C2HjnLyBj_uEDnxsdZi0mNpYBg09E38I2r04/edit?usp=sharing) three short videos that can act as introductions to certain features, which we can use to test if this sort of content is especially helpful too.

**Comment by joethreepwood** [comment]
No further action planned here now, so going to close this out as we shift to Q2
