### ISSUE TITLE
Messaging: Experiment engagement test

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#178]
# Messaging

### Context

Raquel suggest the idea of trying a re-engagement campaign for users who repeatedly visit a section of the product without using it. 

This tests the tactic by running a holdout test for experimentation. 

If a user visits the `/experiments` section 3 times in 30 days _and_ has a valid email address _and_ has not completed `experiment created` they are entered into an A/B holdout test. 

50% of users get no email (holdout). 
50% of users get this email (variation). 

<img width="669" alt="Screenshot 2024-02-12 at 14 14 25" src="https://github.com/PostHog/meta/assets/84011561/785c210d-b44d-472b-82b4-03bde3b0e42d">

The idea is to see if users will be encouraged to start an experiment, measured with the campaign goal of completing `experiment created` within one week of opening an email in the campaign. 

The holdout variant will give us a baseline to judge against. The failure criteria will be a high unsubscribe rate.

**Comment by raquelmsmith** [comment]
Cool excited to hear the results of this!

**Comment by joethreepwood** [comment]
Ugh, I actually had this configured wrong. I've set it up correctly now and will check back in a week or two.

**Comment by joethreepwood** [comment]
I’m going to leave this running for another two weeks, but so far the holdout group who get nothing performs better. 8.6% conversion vs 9.2% conversion. If it continues to bear out this way we may want to think about testing this in a new way that’s more immediate? We could maybe use surveys to give users a prompt.
