### ISSUE TITLE
Messaging: Outage apology - Feb 2024

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#181]
# Messaging

We had an outage which impacted all customers. It lasted 15 minutes and resulted in lost data for users. We should say sorry. 

Two ways to do this: 

1. We update the `/service_message` page and send a notification in the app, directing users to it
2. We email all users directly

In either case we need to explain:

1. What happened
2. The impact of it
3. How we'll stop it happening again
4. ~It was a DNS issue~
5. That we take responsibility
6. What happens next (nothing in this case)

Let's assume for now that we go the email route. 

<img width="761" alt="Screenshot 2024-02-15 at 14 37 10" src="https://github.com/PostHog/meta/assets/84011561/7a2d3c38-eca4-4999-9341-73fad7e0f851">

**Comment by Twixes** [comment]
Public post-mortems are a good way to win confidence that we're serious about issues like these

**Comment by joethreepwood** [comment]
We're already discussing if we can make the post mortem public :)

**Comment by simfish85** [comment]
Looks good - should it come from customers@posthog.com in case anyone replies?  hey@ is _technically_ unmonitored

**Comment by corywatilo** [comment]
[US date/time formats!](https://posthog.com/handbook/company/communication#writing-style) ;)
