### ISSUE TITLE
Marketing Goal: Support Improvements

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#186]
## Context
I've been asked to (and want to) get involved with the support process, to see if there are some improvements we can make here and any lessons/connections we can bring over from other work, such as onboarding. It's not an overt marketing team goal for the quarter, but as https://github.com/PostHog/meta/issues/170 is winding down a little it feels like I can invest some time here.

I'm a planner, so I wanted to put a transparent issue out to plan the work and invite feedback/ideas. Especially important because this work doesn't typically happen on GitHub, but needs to be documented somehow. 

## Things I'm going to do
A bunch of ideas I've had, or which came up in context-gathering calls. 

- [x] Have a context-gathering meeting with Simon and Marcus 
- [x] Standardize existing macros for smoothers comms
- [x] https://github.com/PostHog/posthog.com/pull/7975
- [x] Start a bi-weekly one-touch ticket update - in [Content Ideas](https://posthog.slack.com/archives/C015CRUQR7Y/p1709645446388639)
- [x] Introduce monthly/weekly reporting on key metrics
- [x] Find out how (and start) tracking time to resolution, per team - [Zendesk dashboard](https://posthoghelp.zendesk.com/explore/dashboard/47B166C92FAB65A545192D274819567261A3E545A89E551825C78EB4C3DC7BB9)
- [x] [Investigate macro incident comms or alerting processes](https://posthog.slack.com/archives/C01MGUHFH6G/p1713358104255559)
- [x] [Investigate methods for telling users what support prio they are on](https://github.com/PostHog/meta/issues/186#issuecomment-2063922733)
- [x] ~Investigate methods for upselling low prio users into Teams plan~
- [x] ~Investigate frequency ranking for teams (more tickets in short time = higher prio)~
- [x] https://github.com/PostHog/posthog.com/issues/7961
- [x] ~Investigate if we can use Yarn to improve the support exp~ ruled out, too big a lift for small a gain
- [x] Collect frequent requests and turn them into docs improvements/new content
- [x] Do [some competitors analysis to see how we can specifically match Amplitude, Heap](https://docs.google.com/spreadsheets/d/1k4-j8lAA7PigkeLQBPZpomP20epjyZY0T9TT_vuSVg8/edit?usp=sharing), etc.
- [x] ~Auto out-of-hours responses~ Discussed and ruled out for now
- [x] [Set a no weekend support policy](https://posthog.slack.com/archives/C01MGUHFH6G/p1710330676365379)
- [x] [Setup business hours for 5PM to 9AM CET](https://posthog.slack.com/archives/C01MGUHFH6G/p1710330676365379)
- [x] [One dashboard to rule them all](https://posthoghelp.zendesk.com/explore#/new-dashboard-builder/50115001/)
- [x] Shadow how Prod Analytics solves tickets
- [x] Shadow how Feature Success solves tickets
- [x] Shadow how Marcus assigns tickets
- [x]  Investigate one-touch %age by agent (see if Marcus is biasing any results)
- [x]  [Improve the CS/Support Hero handbook to give better guidance](https://github.com/PostHog/posthog.com/pull/8304#event-12530280889)
- [x]  https://github.com/PostHog/company-internal/issues/1332#issuecomment-2049197912
- [x]  Improve the escalation macros to set better user expectations
- [x]  Create a new macro for feature requests and on-hold statuses
- [x]  https://github.com/PostHog/posthog/issues/21073
- [x]  Clarify what the support plan for Surveys is (Support is covering FS now)
- [x] https://github.com/PostHog/posthog.com/pull/8284
- [x] https://github.com/PostHog/posthog.com/pull/8345
- [x] (Re)activate support for free users, with new routing
- [x] (Re)define SLAs in Zendesk after https://github.com/PostHog/posthog.com/pull/8345 merges
- [x] https://github.com/PostHog/posthog/pull/21818#pullrequestreview-2023454585
- [ ] https://github.com/PostHog/meta/issues/201
- [x] Edit views to give everyone SLA visibility

## Next steps and feedback
All feedback appreciated. For now, I'm going to try and churn through this plan and identify + add new ideas as I go.

**Comment by joethreepwood** [comment]
I've created a new dashboard for tracking time-to-resolution per team. 

```
Median first resolution time over last 30 days, by team: 

Everyone: 42 hours
CS: 12 hours
Growth: 16 hours
Analytics: 25 hours
Infra: 31 hours
Replay: 53 hours
Pipeline: 53 hours
Feature success: 169 hours
Warehouse: 261 hours
```

**Comment by charlescook-ph** [comment]
Honestly these are all great ideas to try out! Really excited to see this. 

> Introduce monthly/weekly reporting on key metrics

I think an important part of this will be getting everyone aligned on what the actual definitions are we are using - ie. what does 'closed' mean. I think our reporting historically has actually made things seem worse than they actually are sometimes because (for example) a bunch of tickets that are open is because of a feature request, not because we've 'failed' to get back to someone.

**Comment by joethreepwood** [comment]
In that instance, I think the metrics that matter most are: 

**First reply time:** The duration between ticket creation and the first public agent reply on the ticket. 
**Time to first resolution:** Duration between ticket creation and its first resolution.
**Time to final resolution:** Duration between ticket creation and its most recent resolution.

These should be showing us how fast we are at getting back to people and solving problems, our accuracy in solving problems, and the overall user wait time. 

Zendesk documents these mostly [here](https://support.zendesk.com/hc/en-us/articles/4408834848154-About-native-Support-time-duration-metrics). 

'Closed' doesn't matter as much to me/users as 'Solved', so really we want to be focused on this metric. I've got a dashboard up to monitor it in Zendesk now and will start reporting on it into Slack.

**Comment by minekansu** [comment]
> Median first resolution time over last 30 days, by team:

Tracking/reporting 90th percentile for these metrics could be more beneficial here. People at the tail end of the support experience are the ones who are upset/at risk of churning/wouldn't engage with CS. And by trying to improve the 90th percentile will automatically improve the median.

**Comment by minekansu** [comment]
In line with the "analyze the extremes" theme, it could also be useful to look at top 1% support experiences to see what went well. This approach is more qualitative but can provide clues about what works (this is how Zappos did support reviews)

**Comment by charlescook-ph** [comment]
On the SLA breach stuff, is there a smart way to track this in Zendesk so it's only counting working day response times in terms of when the targets are met?

Given the vast majority of our paying customers are using PostHog in a business context, I don't think there is a need for us to worry about weekend/OOH support at this stage - if we were a consumer product, this would be different, but there probably isn't that expectation in B2B SaaS land.

**Comment by joethreepwood** [comment]
> On the SLA breach stuff, is there a smart way to track this in Zendesk so it's only counting working day response times in terms of when the targets are met?

Going to look at this next, but that'll basically mean what I allude to: setting business hours. We can probably do a simple version of this (e.g. No weekends), but that won't solve the whole issue. If a ticket gets created at 6PM GMT then it still may not get looked at within the SLA timeframe. 
 
> Given the vast majority of our paying customers are using PostHog in a business context, I don't think there is a need for us to worry about weekend/OOH support at this stage - if we were a consumer product, this would be different, but there probably isn't that expectation in B2B SaaS land.

Agree we can cut weekends as it's a low number of tickets, but OOH is still worth considering I think. Timezones make a big difference if it's just Marcus looking at many tickets. 

(Not suggesting anything certain here until I get stuck into the numbers more though).

**Comment by joethreepwood** [comment]
@MarconLP Super rough at the moment, but I've started speccing out some ideas for macros I could add to speed things up for you. If you get chance, please take a look and add (or remove) any further ideas!

https://docs.google.com/document/d/1HRgTvi7oqGL5oOVI6NXY6E_anMbOc_h31yIQRKdwjTk/edit?usp=sharing

**Comment by MarconLP** [comment]
> Can we push critical issues to someone, even at the weekend and evenings? Probably good to hear from @charlescook-ph @simfish85 @MarconLP here.

Currently, the entire CS team is responding to 1-hour response tickets through the [`#support-high-priority`](https://posthog.slack.com/archives/C053HJDRZSA) channel. That means we can cover the entire US and EU day.

**Comment by joethreepwood** [comment]
I shadowed some support heroes and found some new ideas. 

Discussion of shadowing findings: https://github.com/PostHog/meta/issues/189
New actions: added above

**Comment by joethreepwood** [comment]
> - [x] Clarify what the support plan for Surveys is

Discussed this with Neil. The plan is that Surveys support is now only in 'maintenance mode'. FS team will fix any outstanding issues, but we're saying no to all feature requests.

**Comment by joethreepwood** [comment]
I've had some back and forth with Zendesk over the last few days. Unfortunately, they say it's not possible to use the number of tickets a user as a trigger. That means we can't do any sort of frequency ranking for tickets/users in terms of either priority or upselling them to a Teams plan, or just entering a card. Sad times, but also probably for the best given the feedback on the latter idea. 

Crossed them off the list, on to the next thing.

**Comment by joethreepwood** [comment]
>  Investigate methods for telling users what support prio they are on

>  Improve the escalation macros to set better user expectations

One thing I'm considered to better hit both of these points is to update the automations which assign users to a priority. 

- **For users who are assigned not paying or Low priority:** Automatically tell users they can ask these questions in the community and that we can't provide support for non-paying users due to volumes. 
- **For users who are assigned Medium priority:** Automatically thank users for the report and confirm that we'll aim to respond within our SLA, but that we do not offer weekend support. 
- **For users who are assigned High or Critical priority:** Automatically thank users for the report, confirm that we've tagged this as a High/Critical priority ticket and will attempt to respond within our SLA. 

This would be an automation and so would go into effect immediately, so eager to get your thoughts before I set it up @slshults @MarconLP !

**Comment by joethreepwood** [comment]
I did some research into how Amplitude, Mixpanel, Heap, LaunchDarkly, Matomo, Plausible, and Sprig compare to us in terms of their support channels, coverage, SLAs and free user support. Sheet here: https://docs.google.com/spreadsheets/d/1k4-j8lAA7PigkeLQBPZpomP20epjyZY0T9TT_vuSVg8/edit?usp=sharing

Idea here was to help us think about, if we treat support as it's own product with a revenue line dependant on the Teams add-on (as @jamesefhawkins) recently suggested, then what opportunities are their to differentiate our offering. 

Here's what I concluded:

- **Who has the best support offering?** 
LaunchDarkly. They have the most comprehensive set of features and training materials available, the best SLAs, and the best operating hours. Mixpanel is a close second. Amplitude trails in third. 

- **Should support generate revenue directly?** 
Both Mixpanel and LaunchDarkly are able to do more because they treat support as a revenue generator, with explicit paid add-ons just for premium levels of support. Amplitude also does this. There's definitely a strong precedent and case for treating support as a line-item (regardless of whether it makes profit). 

- **Should we focus on 24 hour or out of hours support?** 
Nobody offers 24/7 support for free, or 24/5 support without generating revenue from support. Based on this, I don't think there's a strong need to hire more engineers with out-of-hours support or broader timezone coverage in mind. This is further supported by analysis of when tickets get made for us. 

- **How do our SLAs compare?** 
With the exception of Heap, Mixpanel, and LaunchDarkly in a few cases we are on-par or promising above most other competitors. Given [our SLA performance](https://posthoghelp.zendesk.com/explore#/new-dashboard-builder/50115001/) there's an argument here that we could arguably ease up on our SLAs a little and still remain competitive. If we wanted to settle for less. 

- **Should we support free users?**
There's no strong consensus here. Some competitors do, some don't. Very few have SLAs for free users though. Based on everything I've learned about support over Q2 so far, I think we're fully justified in not offering support to free users given the level of support they require and how competitors deal with similar situations.

**Comment by joethreepwood** [comment]
Support auto-responses now set up. https://posthog.slack.com/archives/C01MGUHFH6G/p1713870998047369

**Comment by joethreepwood** [comment]
Proposing new response targets: https://github.com/PostHog/posthog.com/pull/8345

**Comment by joethreepwood** [comment]
New modal changes merging in: https://github.com/PostHog/posthog/pull/21818
New SLAs agreed: https://github.com/PostHog/posthog.com/pull/8345
New dashboard updates: https://posthoghelp.zendesk.com/explore#/new-dashboard-builder/50115001/

This closes out most of the work I had planned for support now, so I'll stop meddling there and shift over to https://github.com/PostHog/meta/issues/193 by having a kick-off call with Mine tonight.
