### ISSUE TITLE
Megaissue 2024 Q2 -  Posthog for LLMs (Langfuse)

### ISSUE THREAD

**Issue by Lior539** [PostHog/meta#190]
## Summary

As the number of companies building integrating LLMs increases, we want PostHog to be known as a go-to tool that helps engineers (that build with and integrate LLMs.) build better products.

To do this, we've teamed up with Langfuse to create an integration to bring LLM insights into PostHog. This quarter we'll be focusing on driving adoption of this integration

## Goal

Get 50 PostHog customers using the Langfuse integration

### Alpha/Private Beta (current stage)

- [x] Dashboard template
- [x] Email mutual PostHog and Langfuse customers @jamesefhawkins
- [x] Email AI companies in the YC startup program
- [x] ~Email AI companies in the general Startup program~ (won't do, not necessary)
- [x] [Docs page for the integration in the Product Analytics docs](https://github.com/PostHog/posthog.com/pull/8067)

### Open Beta / Prod release

- [x] Case study post(s) featuring customers using the integration
- [x] Bookface post (done by langfuse team)
- [x] Feature in monthly startups email (PostHog startup program)
- [x] ~Changelog post for Beta + feature in changelog email~ (Won't do, will just do a single one for prod release)
- [ ] SEO content: Tutorials + Blog posts (List of posts TBD) - [issue](https://github.com/PostHog/meta/issues/194)
- [x] ~Outreach/partnerships with LLM communities, slack groups, start up accelerators, etc.~ (Won't do, not convinced it will give us the reach we need)
- [x] Changelog post for Prod release + feature in changelog email
- [x] ~Announcement blog post~ (won't do. Will save for larger launch)
- [x] In-app notification
- [x] ~Walkthrough video (to be included in announcement blogpost)~ (won't do. Will save for larger launch)
- [x] Announce via all social channels (twitter, LinkedIn, etc)
- [ ] Product for Engineers newsletter: AI/LLM themed post where we can also mention the langfuse integration
- [ ] (maybe) add to posthog in-app onboarding

## Open Questions

1. @jamesefhawkins When is the best time for the bookface launch? During the next YC batch?
2. @marcklingen / @clemra: When do you we'll be in an open beta?

**Comment by Lior539** [comment]
tagging a bunch of folks for comment+feedback: @ivanagas @andyvan-ph @jtemperton @joethreepwood @jamesefhawkins @marcklingen @clemra

**Comment by joethreepwood** [comment]
>  Email AI companies in the Startup and YC programs

We have AI teams identified for the W24 batch btw, but not old batches or the Startups program. Just FYI as you'll have to identify these separately. 

Probably worth an in-app notification for something like this btw. Anything in the changelog is also possible to go out with a changelog Pylon announcement. 

Anything in Bookface is going to be best in the next batch, which isn't for a while yet. 

Wonder if we want to start asking teams what industry they're in when they sign-up. 

I'm also going to be doing some Sales-Led stuff next quarter. I haven't planned things out there, but there's a chance we can do some stuff together to funnel AI teams to this.

**Comment by joethreepwood** [comment]
We could probably so some social threads and announcements here too. AI stuff seems to blow up there. Up to you though.

**Comment by andyvan-ph** [comment]
> Wonder if we want to start asking teams what industry they're in when they sign-up.

Was just thinking this. Dedicated onboarding flow / email campaign for AI companies?

**Comment by joethreepwood** [comment]
> > Wonder if we want to start asking teams what industry they're in when they sign-up.
> 
> Was just thinking this. Dedicated onboarding flow / email campaign for AI companies?

I imagine Growth will have thoughts. 

But yes, we could obvs then tailor a lot of things

**Comment by jtemperton** [comment]
Very much here for finding the right angle for a newsletter issue on this when the time is right. And happy to brainstorm, of course.

**Comment by Lior539** [comment]
Issue with the content plan:
- https://github.com/PostHog/meta/issues/194

**Comment by Lior539** [comment]
Closing out this Q2 issue and will create a new one for Q3. Overall a success! We reached 50 customers in early June
