### ISSUE TITLE
Megaissue 2024 Q2: Newsletter growth

### ISSUE THREAD

**Issue by jtemperton** [PostHog/meta#192]
## Summary

Product for Engineers has 10,000+ subscribers. We currently bring in ~1,000 net new subs every 30 days. We want to increase this rate of growth in 2024 with a longer-term goal of hitting 100,000 subscribers.

## Goal

Get Get Product for Engineers to 30,000 by end of 2024, with a stretch target of 35,000. Long-term goal is 100,000 subscribers. Keep open rate close to 45%.

## Plan

- [x] ~Go weekly with no drop in quality~ (We're staying fortnightly for now)
- [ ] More James (Hawkins)
- [x] Plan and maintain a publishing schedule that keeps us at least 3 issues ahead at any given time, ideally more
- [x] Make the newsletter more visible on PostHog.com
- [ ] Potentially add the newsletter to product onboarding
- [x] Better promote the newsletter on X and LinkedIn
- [x] Get more recommendations from other Substacks
- [ ] Land a big interview

## Open questions

Monthly (?) pitch/ideas meeting? Let's agree on 'content buckets' to give the newsletter better focus:

- What we've learned about...
- What we think about...
- How you can...
- How to achieve TKTK...
- Why we TKTK...
- How we TKTK...
- Why you should TKTK...

Also, some Post-it notes.

![IMG_20240321_160540](https://github.com/PostHog/meta/assets/162187331/79646112-e29c-41a7-bc3d-ab47bd93044a)

**Comment by jtemperton** [comment]
Tagging in folks for feedback, ideas, etc. @andyvan-ph @ivanagas @charlescook-ph @jamesefhawkins @Lior539 @joethreepwood

**Comment by charlescook-ph** [comment]
I like the idea of doing a _little_ bit of pitching live in a meeting - I feel like sometimes the energy leads to better/more interesting/weirder ideas than just doing it over Slack

**Comment by joethreepwood** [comment]
> Get Get Product for Engineers to 30,000 by end of 2024, with a stretch target of 35,000. Long-term goal is 100,000 subscribers. Keep open rate close to 45%.

Is there a target for Q2 specifically, or is this specifically meant to be a year-long goal?

>  Plan and maintain a publishing schedule that keeps us at least 3 issues ahead at any given time, ideally more

Yesssss

>  Potentially add the newsletter to product onboarding

I'm hesitant over this. 

We already have the newsletter featured in the onboarding emails which users get, and we've had that in place for at least six months. I feel it's really important to keep the in-app onboarding clear and simple, to get users to app activation as fast as possible. I think this could be a distraction there. Def up for making it more visible in Onboarding 5 though, if you want!

For what it's worth, a quick check on Customer.io reveals that around 1000+ people have subscribed to the newsletter after coming from the onboarding emails, so about 10% of the total audience. 

>  Land a big interview

An idea I keep pitching is to feature stuff from within out network, so I'm a big fan of this. Doing something with Porter, for example, could be great for YC exposure. Or we could interview someone like Theo or Dalton to tease some visibility out of them. 

Doing a newsletter with Theo about the hassle/opportunities of developer influencers and how to make that work is, to me, an _obviously_ great idea.

**Comment by andyvan-ph** [comment]
We're definitely thinking more in the Dalton / Theo level of interview. For smaller peeps, I think the multiple source approach of the "first time founder" piece I'm working on is better.

**Comment by andyvan-ph** [comment]
> Is there a target for Q2 specifically, or is this specifically meant to be a year-long goal?

I framed this in the team goals as "subscriber growth accelerating". We had a goal for Q1, but I don't think a single number adds a huge amount at this stage. TL;DR goal is start growing faster than we are now.

**Comment by joethreepwood** [comment]
Eh, I do think that when it's easy to add a number then we should. If we're adding ~1,000 net new subs every 30 days at the moment and the goal is to grow faster, maybe that should inform the goal? At the very least it's good to have a number to aim at. 

Doesn't impact me hugely though, so up to you - just don't see an argument against it.

**Comment by jtemperton** [comment]
Per [Slack](https://posthog.slack.com/archives/C01FHN8DNN6/p1711121522131379), but just so this is all on GitHub too...

[Newsletter ideas doc for eyeballs, feedback, etc.](https://docs.google.com/document/d/1wrHbSzBKTZ7oKamW9Xgxqj8SCaEq3klU-TAqLyxCYHM/edit)

[Newsletter schedule](https://docs.google.com/spreadsheets/d/1ZNIQw9apB7Il90Kize67RrajFJXLu49V1iVukcrdi14/edit#gid=0)
