### ISSUE TITLE
Messaging: Person profiles beta invite

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#198]
# Messaging
 
We need more users to test personless / person profiles. Discussed with the team and hitting the startup program seems a good next step. 

The email will come directly from Robbie. The personal touch generally works well, and this will help ensure all feedback funnels towards him. 

We'll tag this as a marketing email, and it'll go to all users in a team on the startup plan. About 3,500 recipients.

**Comment by joethreepwood** [comment]
<img width="663" alt="Screenshot 2024-04-16 at 11 31 13" src="https://github.com/PostHog/meta/assets/84011561/c726761e-6fca-4c32-a81a-1c7c5f8e5156">

Quick draft for feedback from @robbie-c @tiina303 and @raquelmsmith

**Comment by robbie-c** [comment]
![image](https://github.com/PostHog/meta/assets/2056078/331400c2-2351-467b-a627-ce420b6f2539)
We were just about to change posthog-js so that this option would be renamed, let me do this first. I'll do it right now and should take ~an hour including CI.

**Comment by joethreepwood** [comment]
Can you confirm the right option name? Will impact https://github.com/PostHog/meta/issues/196 too

**Comment by robbie-c** [comment]
`person_profiles`

**Comment by joethreepwood** [comment]
<img width="909" alt="Screenshot 2024-04-16 at 13 37 46" src="https://github.com/PostHog/meta/assets/84011561/500d8fdc-7257-47b2-9ea3-1225de371a91">

New name and copy. Obviously we can't mention the pricing too much because that hasn't launched yet. 

Thoughts?

**Comment by jamesefhawkins** [comment]
I'd probably add a _bit_ more incentive for people to do it ie

"our intention is to reduce the price of these events very significantly, getting set up now means you'll be ready from day one"

(it's definite, will be quite a lot, it's specific to these events)

**Comment by joethreepwood** [comment]
<img width="997" alt="Screenshot 2024-04-16 at 17 06 04" src="https://github.com/PostHog/meta/assets/84011561/089886f7-1a5c-4eae-8d7f-f36409ec9f89">

Rolled in some NPM info too. 

@robbie-c can you let me know you're happy for me to send this?

**Comment by tiina303** [comment]
We've recently discovered that PoE modes that use person_properties on the event could add complexity for users understanding this, so could we exclude all users who are in either of these features from the emails we are sending out (if not already sent) 🙏 
1. https://us.posthog.com/project/2/feature_flags/8523
2. https://us.posthog.com/project/2/feature_flags/40989

**Comment by joethreepwood** [comment]
Yep, easily done. 

https://us.posthog.com/project/2/cohorts/66865

**Comment by joethreepwood** [comment]
OK, this is set up and scheduled. Any urgent feedback must be given at least 10 mins before the time below!

<img width="492" alt="Screenshot 2024-04-17 at 09 30 07" src="https://github.com/PostHog/meta/assets/84011561/78bd53fd-2269-4eb6-9b0e-6c5c3f5827f9">

**Comment by robbie-c** [comment]
Really nice
