### ISSUE TITLE
Customer Personas

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#20]
### Context
Following some questions before the offsite (e.g. [this issue](https://github.com/PostHog/company-internal/issues/363)) I started looking at creating customer personas with the goal of giving us some direction and enabling us to onboard external resources and agencies faster. 

I've outlined two personas, one for a software developer (technical) and one for a product manager (limited technical). There's likely a bit of blur between them. Information is taken from case studies, interviews, a bunch of data from across PostHog/Orbit/Hubspot and [a survey I did](https://docs.google.com/spreadsheets/d/1WkPo6FZyT-hzaTVeWRlaZVzp839V_nivbAnvnVa03vk/edit?usp=sharing) of about 50+ users this week. It also has a sprinkle of intuition. 

Rather than burying this in an existing issue, I've stood it alone so it can be easily referred back to. 

### Personas Document Link
[Google Doc link](https://docs.google.com/document/d/12uc0y0G07KyZwinxLJZxewbMrnZ47M79c6ORl8ecWNY/edit?usp=sharing)

### Next step
We'll be immediately sharing this with our SEO consultant and our paid ad agency, to help guide them. However it's very much open for feedback and ideas.

**Comment by joethreepwood** [comment]
Additional next step: Once there's been some feedback, I'll add this to the handbook.

**Comment by joethreepwood** [comment]
@leggetter would love to get your feedback on this too, if possible.

**Comment by piemets** [comment]
Not much constructive feedback, this is super helpful! Like the needs stars a lot. 

Two things:
- I don't feel like I get a good sense from this about what would compel these key buyers to actually make the purchasing decision, ie. moving from Open Source to Scale. Or to put it another way, I'm not sure what differentiates a persona willing to spend $2k+ a month vs. one that is happy to use the OSS version. 
- Similarly, I think Pat Product's quote is weak - it just tells me that they didn't go with Pendo because they were too expensive. (Unless I am understanding this incorrectly and pricing is very important to this persona).

**Comment by paolodamico** [comment]
Added some feedback directly on the doc

**Comment by joethreepwood** [comment]
> * I don't feel like I get a good sense from this about what would compel these key buyers to actually make the purchasing decision, ie. moving from Open Source to Scale. Or to put it another way, I'm not sure what differentiates a persona willing to spend $2k+ a month vs. one that is happy to use the OSS version.

Open to push back on this as this is a weakly held opinion, but my immediate thought is that the decision between OSS and Scale is more at a company (rather than individual) level because it's dictated by needs such as number of projects, number of events. 

Maybe a next step for personas will be for me to speak to some more OSS users specifically and see if there are deeper differences. Would love thoughts on this though. 

> * Similarly, I think Pat Product's quote is weak - it just tells me that they didn't go with Pendo because they were too expensive. (Unless I am understanding this incorrectly and pricing is very important to this persona).

Agree, maybe it's not the right one. Will update. Thanks!

**Comment by joethreepwood** [comment]
> Added some feedback directly on the doc

Have actioned and responded to it all and it was all _really_ great. Thank you!
