### ISSUE TITLE
The Zendesk & Email Domain Problem

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#201]
We seem to have a big issue around how Zendesk assigns tickets to orgs. 

## What happened?
I discovered this when I raised a bug ticket for a ticket which was timing out. In response, I got back the auto-response which we send to non-paying users. That seemed wrong! I looked at the ticket and alerted @slshults and @MarconLP 

This is what we found:

![cleanshot_2024-04-29_at_08 01 25_2x](https://github.com/PostHog/meta/assets/84011561/dd82f93b-5c7c-48d2-a285-18916feeeae6)

It turns out that other users have been assigned to this org too, which is _not_ the correct org. 

## What's causing this?

Basically, Zendesk has no concept of PostHog orgs. It goes by domain, and it lumps domains together. 

In this case what happened was that I sent a bug ticket on a `@posthog.com` email domain. This is obviously the domain that Support use when testing new features. 

Because domains are lumped together, if someone on `posthog.com` downgrades to the free tier (to test something) then _all users on that domain_ are also downgraded according to Zendesk (not in PostHog, obviously). They get tagged as non_paying, and that impacts the support they get. 

## Why is this such a big problem?
Because of `@gmail.com` and `@outlook.com` domains. 

If someone with a `@gmail.com` account upgrades or downgrades to the paid tier then _all_ tickets from `@gmail.com` accounts will be associated with that org and treated as paying/non-paying users. As a result, they'll get the wrong support response and will be categorised in correctly. 

## What's the solution?
I am open to ideas.

**Comment by slshults** [comment]
Regarding "in an ideal world we would look up the correct org by ID", in the case of tickets where the user is logged in and using the support form in the sidebar, is there something currently preventing us from relaying one or more of their person IDs (other than email address as distict_id) along with their org ID to Vitally and/or Hubspot for matching with an existing org? (I assume so, but curious where that hurdle is in order to look for ways over or around it.)

**Comment by joethreepwood** [comment]
That would sound like a good solution, so I'm hoping there's no hurdle there. I've skimmed through the automations page and I'm unclear on whether automations would solve this for `@gmail.com` users and other common domains.

**Comment by slshults** [comment]
The solution is written up in this section of the handbook: [Setting the correct organization in Zendesk for new tickets](https://posthog.com/handbook/growth/sales/automations#setting-the-correct-organization-in-zendesk-for-new-tickets)
