### ISSUE TITLE
Should we have someone own docs full time?

### ISSUE THREAD

**Issue by Lior539** [PostHog/meta#206]
Should we have someone own docs full time?

Motivation:
- "Docs that spark joy" is a theme that occurs every few quarters (I did whole bunch of docs work in Q3 last year, we're doing it again this quarter)
- We get feedback on the docs in this channel constantly, but no one owns it and a result its not always actioned
I think Me and Ian sometimes action it, but I tend to forget about it /intentionally not prioritize

Should we hire someone?
- I think at this point owning the docs can be a full time job. I dont think myself or Ian are particularly excited about it though.
- We already have strong opinions on what our docs should be + we've done the job ourselves, so fits nicely into our philosophy of "do the job yourself first before hiring someone"
- If we do hire someone, we need to develop a strong vision for what we'd like our roadmap to be first, so that we can set them up for success

**Comment by charlescook-ph** [comment]
Would we consider establishing a relationship with a good contractor for this kind of thing? ie. continue doing what we're doing in terms of rotating a bit of responsibility among the team, but periodically get someone in for a 1 or 3 month burst of focused activity if there is some big piece of work we want to do?

(Not 100% sure today it would be the next marketing hire we'd make, but I could see it in the future.)

For context, do we have a list somewhere of all the docs work we'd like to get done that we're not getting to?

**Comment by Lior539** [comment]
There are three parts to this:

1. Keeping existing docs up to date
2. Addressing feedback from users
3. Up-leveling our docs

Currently, we focus only 1) every few quarters, and sometimes 2 (although not consistently).

If we hire a contractor, they could 1 mostly, and perhaps also some of 2. A full-time employee could focus on all 3.

**Comment by charlescook-ph** [comment]
@andyvan-ph do you want to have a go at filling out a role request template for this one? 

One thing - I think it would be a shame if hiring someone to 'do' community and docs basically means that as an organization we drift into everyone else not caring about that stuff because now we have a person to do it (which I can definitely see happening). 

Also worth tagging @jamesefhawkins and @corywatilo in it given the community overlap. 

This is probably more a 'Technical Community Manager' or similar - devrel/advocate type people tend to want to spend lots of time attending/speaking at conferences and doing more brand building-y stuff, whereas really the influencer stuff is more like classic marketing project managementy work (ie. a lot of grunt work briefing, chasing, reviewing etc.).

**Comment by joethreepwood** [comment]
I do have strong opinions on this, as Andy said. Short version is I think there are two ways to tackle this: 

1. We staff up support engineers and make docs a support engineer responsibility.
2. This is a community-focused role as others have said. 

My strong preference is 2. Support won't scale.

I pretty strongly agree with Charles that this should not be a Dev Rel/Adv role, for the reasons Charles says. I think we should be looking for someone with explicit experience in either/both Technical Writing (e.g. writing docs specifically) and Community Management. Someone who has in-roads or experience with influencers would be a plus. 

I do think this could be a full time job, as there's a lot to be done beyond simply updating the docs content to a point of completeness.

**Comment by charlescook-ph** [comment]
@joethreepwood maybe you are better placed to write something up [here](https://github.com/PostHog/company-internal/issues/new?assignees=couaphang&labels=people&projects=&template=new-hire-request.md&title=Proposed+New+Hire+%5BROLE%5D)? (Seems like you've thought about this the most out of everyone.)

We can then riff on the specifics of the role a bit there, but I think we're all broadly in agreement that a new role in this area would be a good thing. 

(Obv not promising we will hire or when, but it's easier to say yes when we have a more fleshed out spec for what we need the person to do! 😄)

**Comment by joethreepwood** [comment]
Thoughts welcome https://github.com/PostHog/company-internal/issues/1391
