### ISSUE TITLE
Submit PostHog to Console newsletter

### ISSUE THREAD

**Issue by leggetter** [PostHog/meta#21]
https://console.dev is a new(ish) online list and newsletter for developer-focused tools.

I'll email to request a listing with the following:

---

I'd like to submit PostHog for consideration with Console. It's an open source Product Analytics tool (competitors: Amplitude, Heap, MixPanel, Pendo). There's also a SaaS option.

GitHub: https://github.com/PostHog/posthog
Website: https://posthog.com

I recently joined PostHog to lead DevRel (previously tru.ID [I submitted], Nexmo/Vonage, Pusher).

I know you share your question for transparency on your selection process but thought I'd provide some notes to hopefully help with the process:

> Is this interesting and useful to developers?

I've spent much of my career building tools that enable developers to build features but I'm excited that this tool helps developers understand if the products and features they've shipped are successful and how they're being used.

>  Is there a self-service signup?

For Cloud, yes, with a large free tier. The main focus, for now, is our self-hosted open source offering.

> Would this form part of a daily-use set of developer tools?

For product-minded developers (Product Engineers), yes.

> Does it make me a better developer?

It helps a developer understand if the features they are building are being used and if they're being used successfully. It also allows for A/B testing via feature flags.

> Does it solve a problem I have experienced? How well does it solve it?

This one is for you. But it was definitely a big problem for me :)

> Would this be used by advanced, power-users?

We hope it has a reasonably low barrier to entry but there's plenty of scope for power-users.

> Is the tool high quality?

PostHog has moved very quickly over the past year so there have been a few bugs. But the quality is improving and I'd honestly say it's "good" now.

> Does it do the job it claims?

One for you. But it's definitely a swiss army knife tool as it has a lot of features. This means we've gone deeper with functionality in some places than others.

> Does it have a good graphical and/or command line interface? Shortcuts? Accessibility?

UI, yes. Shortcuts, yes. Some accessibility, yes, but needs more work.

> Is it being actively maintained with regular bug fixes and updates?

Definitely.

> Does it have good documentation? Is it fast?

https://posthog.com/docs covering deployment, integration and end-user guides.

> Does it have any negative impact on security or privacy?

With any analytics tool, there's plenty to consider when it comes to privacy. However, our focus on self-hosted has enabled companies to be more privacy-focused and gives them more control over their customer data.

> How would I feel recommending this to my friends? Would I tweet a link to it?

Another one for you.

I'd recommend having a quick look over the company handbook for a bit more information on the company, team and general ethos e.g. the public strategy https://posthog.com/handbook/strategy/strategy

**Comment by piemets** [comment]
Looks good to me! Just two notes:

> For Cloud, yes, with a large free tier. The main focus, for now, is our self-hosted open source offering.

Do we not count PostHog Open Source as self-serve? (Though Scale definitely isn't).  

> Does it have any negative impact on security or privacy?

I think we could be more positive, e.g. 'We offer a significantly more privacy-focused solution to analytics than other products on the market through our self-hosted version, which lets companies stay in control of their customer data instead of sending it to a third party.'

**Comment by leggetter** [comment]
I've interpreted `self-serve signup` in this context to mean cloud/SaaS. IMO you shouldn't have to "sign up" for open source software.

Your wording on privacy definitely better. To clarify: my submission wording won't be used by the folks at Console. I've just provided some more information as I thought it was helpful.

See the following, above:

> I know you share your question for transparency on your selection process but thought I'd provide some notes to hopefully help with the process:

**Comment by leggetter** [comment]
Hasn't been features but they know about PostHog. There is a sponsorship option with a CPC plan which you can cap out at $5k.

Closing for now.
