### ISSUE TITLE
Messaging: Activate Product -> Subscribe to All

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#212]
We're moving to a "subscribe to all products model". This basically means there will be no more per product upgrades. When a user adds their credit card and "subscribes" they will be upgraded to the paid level for every products.

[There's an RFC for a deeper dive](https://github.com/PostHog/product-internal/pull/606) and @zlwaterfield owns this on the Growth side. 

There are a few things we need to do. 

- Announce to all impacted users
- Update all existing flows in C.io

## The Announcement

We're going to send a single email to all users who are impacted directly and being backfilled to the new plan. 

We need to tell them that: 

- We're changing how subscriptions work generally
- As a result all teams are being opted in and are now subscribed to all products
- They'll see this reflected on their bill with new line items
- But they won't be charged anymore than they currently are because we bill based on usage
- And we've set an automatic billing limit of $0 on all their new products, so they don't accidentally use them and get charged

I'll share drafts of the email on this issue for approval from @zlwaterfield  

Timing-wise this needs to coordinate closely with the change, but no advance notice is required according to our TOS. 

### Onboarding flows
**The [main onboarding flow](https://github.com/PostHog/meta/issues/197) will need to be entirely rebuilt.** It currently relies on a check to see if users have completed `billing product activated` with a `product key` property that corresponds to the feature name. This change essentially removes that check, so we can no longer easily check if users are paying for a feature. 

The solution is:
- @zlwaterfield to advice if there's a replacement value we can check to see if users are paying for a feature
- Or, to restructure this flow to avoid this check and rely on activation/usage checks instead

All copy across the flow will also need to be rewritten after this, for each of the six subflows within onboarding. We can no longer advise users to subscribe to a product - instead we should direct them to get started with a product and advise that it's already included in their plan. This'll be a lot of copy rewriting, and I'll share samples of the copy and a preview of the flow when it's done. We'll keep changes minimal for now, because we plan to overhaul Onboarding 5.1 in Q3 anyway as we'll have additional products launching. 

We will also have to decide a new goal to use for onboarding campaign and all subsequent campaigns, as we currently use `billing product activated` and `product key` to track success of these campaigns. I'm open to feedback from @raquelmsmith and @zlwaterfield about what the goal could be, but the fallback will be activation criteria for any product - which is based on usage, not subscription. 

### Subscription flows
We currently also use subscription flows which send information to users when they subscribe to a product. It's unclear how these will work, so we may simply deactivate this plan unless there's a new trigger suggested above -- this'll have minimal impact as users will already be completing the trigger and encouragement will come from across the onboarding flow.

**Comment by joethreepwood** [comment]
Yeah, I'll have a draft for this today hopefully. I'm thinking it'll be positioned along the lines of 'We're making it even easier to get started with our other products' but will hammer something out soon.

**Comment by charlescook-ph** [comment]
'We made getting started with our products much less annoying'

**Comment by raquelmsmith** [comment]
Agree with charles. We should 100% avoid saying "we've subscribed you to everything" and just say "we've simplified our  billing flows so you only have to add your billing information once, and you'll still only get charged for what you use. Your bill will not go up.

**Comment by joethreepwood** [comment]
And here's the super short, focused version. Interested in feedback! My preference, if purely from a marketing POV, is the first.

<img width="607" alt="Screenshot 2024-06-13 at 15 55 42" src="https://github.com/PostHog/meta/assets/84011561/0dd60f14-6bc6-41eb-a1b3-ccdbbf57fa8f">

**Comment by zlwaterfield** [comment]
I prefer the first one for two reasons
1. The description in the top block is more clear to me.
2. I think the breakdown of all the products is a good reminder to users who aren't using more than one product. 

> @zlwaterfield to advice if there's a replacement value we can check to see if users are paying for a feature

We will be tracking product intent (meaning the product they clicked on to subscribe) and sending it on the `billing subscription activated` event, but that will only happen in certain instances like onboarding. If they subscribe from the billing page we won't have that information. 

I think the solution is probably something around sending information on org identify calls that say what products the customer has usage for, so you can do drips based on if they are using it or now.

**Comment by raquelmsmith** [comment]
I like the top bit of the first email but feel fairly averse to the marketing-y feeling of the big list of products below. Maybe just list them inline with links?

**Comment by joethreepwood** [comment]
I like the approach of giving the products an intro and a bit of personality. I think that what's actually making this feel marketingy is the focus on free allowances and the level of detail. Trying with a plain in-line list feels like it gets lost.

I've made some tweaks and this is the version I'd like to use unless there are strong objections. It's shorter, more informational, and doesn't have a blunt commercially focus CTA. 

<img width="601" alt="Screenshot 2024-06-14 at 12 02 12" src="https://github.com/PostHog/meta/assets/84011561/bdcef1cf-f689-4d81-ac9a-943291a91b7c">

**Comment by joethreepwood** [comment]
<img width="795" alt="Screenshot 2024-06-17 at 16 35 55" src="https://github.com/PostHog/meta/assets/84011561/35be21f2-4c85-4e85-a3ff-c5d51547face">

This needs polish, but indicative of the current draft for upsell replacements in onboarding flow.

**Comment by joethreepwood** [comment]
As per https://github.com/PostHog/billing/pull/715#event-13286116500 I've switched the broadcast for the announcement email to an event triggered campaign.

The only to-dos left here are:

- [ ] Confirm timing with Zack and activate campaign
- [ ] Update the new onboarding flow to reflect the latest decision regarding Proxies/Teams

When the new onboarding flow activates I'll leave existing users in the current flow where they are, to avoid disruption.
