### ISSUE TITLE
Q3 2024: PostHog for LLMs

### ISSUE THREAD

**Issue by Lior539** [PostHog/meta#214]
## Goal

Two goals: 

- Get 50% of YC AI startups that using PostHog to use one of our LLM integrations
- 150 companies in total using any of LLM integraitons

## Plan

- [x] [Launch Traceloop integration + related marketing](https://github.com/PostHog/meta/issues/211)
- [ ] [Keywords AI integration](https://github.com/PostHog/meta/issues/231)
- [x] Reach out to [AI Grant](https://aigrant.com/) and offer sponsorships/credit/something
- [ ] ~Bookface post when new batch starts to announce our all our LLM integrations (need to wait for Traceloop integration first too)~ Not done. Will maybe try for F24 batch
- [x] James and Tim to plug in the LLM integrations when they go new YC batch  event
- [x] [Onboarding email to LLM companies](https://github.com/PostHog/product-internal/pull/619#discussion_r1674024722)
- [x] ~Add LLM integrations component to [YC startup program page](https://posthog.com/yc-onboarding)~ (won't do)
- [x] ~Add LLM integrations component to [Regular startup program page](https://posthog.com/startups)~ (won't do)
- [ ] ~Run a Startup Spotlight featuring one the AI companies in the new batch~
- [ ] Comarketing guide/tutorial/blog with Langfuse and LlamaIndex
- [x] Add the ability to track how many companies are using the integrations in PostHog
- [ ] Comarketing blogs with AWS Bedrock
- [x] In-app onboarding: Add adding the integrations step there
- [ ] ~Stretch: Convert [langfuses chatbot blog](https://langfuse.com/blog/showcase-llm-chatbot) for Hackernews post / beginner's guide to creating LLM app~
- [x] [Custom merch for LLM startups](https://github.com/PostHog/product-internal/pull/619#discussion_r1675597744)
- [ ] ~[Launch YC](https://www.ycombinator.com/launches) post~ Not done. Will maybe try during F24 batch

## Related issues

- https://github.com/PostHog/meta/issues/211
- https://github.com/PostHog/posthog.com/issues/7416
- https://github.com/PostHog/meta/issues/170

**Comment by Lior539** [comment]
tagging @charlescook-ph @andyvan-ph @joethreepwood @ivanagas @jtemperton for comment. Anything else I should add?

@joethreepwood especially interested in your feedback, since you've YC related stuff before + the work above touches some of your usual areas (onboarding, startup spotlight)

**Comment by joethreepwood** [comment]
YC runs on merch. One thing we could do is enhance our YC offer somehow to, say, give users an exclusive t-shirt, hoodie, badge or something that's only available to YC + AI teams. 

Maybe we get super cheeky: @lottiecoxon designs two shirts. One says: "I'm in PostHog's Y Combinator program and I'm NOT making an AI product" and another one that says the opposite (or similar). Then, when people sign up, they can select one or the other. 

Beyond that, the biggest impact is on-site stuff. If we can get YC to feature us in their materials, or give us a speaking slot, or let us do an on-site giveaway, that'll move the needle. 

Spotlight-wise, I don;'t really do these anymore. If you want to write one, go for it though. It can definitely go in the emails.

**Comment by raquelmsmith** [comment]
We should add this info to in-app onboarding for product analytics, too, right? Can you come up with some suggestions for how to do that?

**Comment by Lior539** [comment]
@joethreepwood 

> YC runs on merch. One thing we could do is enhance our YC offer somehow to, say, give users an exclusive t-shirt, hoodie, badge or something that's only available to YC + AI teams.

Thanks for this. I think its a good idea, but a bit high effort. Given that we most companies in the new batches use us already (because of all your great work!), I think we only need to let them know the integrations exist. It did give me an idea though, and I've added ` Onboarding emails: Add email about LLM integrations to onboarding flow if company in YC startup program` to the list now. I think this will be significantly lower effort and should achieve similar results (combined with the other stuff on the list)

**Comment by Lior539** [comment]
> We should add this info to in-app onboarding for product analytics, too, right? Can you come up with some suggestions for what that might look like? I'm not familiar enough with these yet to know what their onboarding should look like.

@raquelmsmith I'm slightly hesitant to add it to our in-app onboarding. The integrations require you sign up to our 3rd-party partners, so Im reluctant to send people to other apps/sign-up flows when they're in the middle of ours

**Comment by joethreepwood** [comment]
Defer to you on the merch point, but it'd actually be simple to do. We just need to get the merch made (that's the hard bit) and then we can have it as an optional add-in for YC and startup kits. 

` Onboarding emails: Add email about LLM integrations to onboarding flow if company in YC startup program` to the list now. I think this will be significantly lower effort and should achieve similar results (combined with the other stuff on the list)

We can probably chat directly about how that'd work, but I think that may actually be trickier. 

The reason for this is that we don't have any event or trigger to identify YC teams within PostHog. I have to do this manually and it's a non-trivial lift. We'd also, as an output, then just end up messaging _every_ YC team about our LLM integrations regardless of whether they're an LLM team or not. 

The better way to do this would be to add LLMs as an in-app onboarding step as @raquelmsmith mentioned. Then we can use that as a trigger to create a customized onboarding flow for _every_ team building LLMs. I get your concern about the timing, but we can delay emails to compensate for that. 

One thing to add may be reaching out to Helicone et al and getting them to put us in _their_ onboarding.

**Comment by andyvan-ph** [comment]
This looks like a solid plan to me.

@KendalHall, do you know if James and/or Tim are attending any events at YC for the upcoming batch?

**Comment by joethreepwood** [comment]
> @KendalHall, do you know if James and/or Tim are attending any events at YC for the upcoming batch?

They have something pencilled in for their trip in a few weeks. Kendall and I are already discussing.

**Comment by ivanagas** [comment]
- I think https://aigrant.com/ is like the YC of AI, could we do something special for them like we do YC, or at the very least, get on their credit list? Likely has overlap with YC, but would be awesome to win all these companies.
- Newsletter getting a bunch of AI founders we know to talk about analytics, become the go-to post for future founders to read

**Comment by raquelmsmith** [comment]
> I'm hesitant to add it to our in-app onboarding. The integrations require you sign up to our 3rd-party partners, so Im reluctant to send people to other apps/sign-up flows when they're in the middle of ours

@Lior539 I think it would be the opposite - they're using an LLM provider and want to use PostHog to collect events. We used to do this with, eg Segment. If you use Segment, here's how to send stuff to PostHog, here's the API key you need, etc. 

This went away at some point, prob because we don't want to encourage people to use Segment 😛 but we could do it for the LLM providers.

**Comment by Lior539** [comment]
> @Lior539 I think it would be the opposite - they're using an LLM provider and want to use PostHog to collect events. We used to do this with, eg Segment. If you use Segment, here's how to send stuff to PostHog, here's the API key you need, etc.

@raquelmsmith super interesting! You've convinced. I'll add this to the list and look into it

**Comment by Lior539** [comment]
> I think https://aigrant.com/ is like the YC of AI, could we do something special for them like we do YC, or at the very least, get on their credit list? Likely has overlap with YC, but would be awesome to win all these companies.

@ivanagas This is great! Thank you for this. Didnt know about AI grant

**Comment by Lior539** [comment]
> @KendalHall, do you know if James and/or Tim are attending any events at YC for the upcoming batch?
>
> They have something pencilled in for their trip in a few weeks. Kendall and I are already discussing.

@joethreepwood can you let me know if/when you start planning what they'll do there? I'd want to make sure they mention the LLM stuff
