### ISSUE TITLE
Q3 2024: Comparisons

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/meta#220]
## Summary

Comparisons are high-value pages for us, but they're long and hard to maintain. I want to use Q3 to explore ways of making them better and easier to maintain.

## Outputs for Q3

- [ ] [Light refresh of existing guides](https://github.com/PostHog/posthog.com/issues/8917)
- [x] Ship PostHog vs Sentry guide as there's growing search for it - @ivanagas 

## Long Term Goals (Not Q3)

- [ ] Work with @corywatilo on shipping a properly custom-designed version comparison pages
- [ ] Convert all guides to new template
- [ ] Create a comparison landing page for all comparisons
- [ ] Create a feature "database" so we can build comparison easily / update all guides at once when we ship a new feature.

**Comment by andyvan-ph** [comment]
Tagging @charlescook-ph @Lior539 @ivanagas @jtemperton for feedback.

**Comment by charlescook-ph** [comment]
Looks good to me! Could also consider deleting any that aren't doing any work for us (maybe they are all useful, but this could be a way to make maintenance easier long-term). 

Are there no new comparisons we want to do besides PostHog vs. Sentry at this stage?

**Comment by jtemperton** [comment]
Small thing but getting snazzy custom top art for each comparison page would be great, especially as it's the sort of thing we'll only need to do once per page.

**Comment by andyvan-ph** [comment]
> Small thing but getting snazzy custom top art for each comparison page would be great, especially as it's the sort of thing we'll only need to do once per page.

We have these for the actual comparisons, but not the _alternatives_ guides. Good point, though, will add this to this one.

**Comment by ivanagas** [comment]
- Mixpanel isn't a [top alternative](https://us.posthog.com/project/2/insights/kQXtfKU5), what is the goal of shipping a custom page there? To try to make it the top traffic alternative?
- Re: database, I created the [Alternative Generator tool](https://alternative-generator.vercel.app/) and it has a bunch of data on the various alternatives, is there something we could with it to keep alternatives up to date? Maybe include the completed blogs?

**Comment by andyvan-ph** [comment]
> * Mixpanel isn't a [top alternative](https://us.posthog.com/project/2/insights/kQXtfKU5), what is the goal of shipping a custom page there? To try to make it the top traffic alternative?

I'm thinking specifically about PostHog vs Mixpanel page here, not the alternatives page.

The goal is better conversion / a better experience overall. I don't want to totally lose the editorial style, but I want a page that delights more. The high bar is people should talk about these comparison pages like they do our homepage.

**Comment by Lior539** [comment]
All looks good to me!

> A/B test new page vs old to see if there's any obvious increase in conversion

It's worth looking into if this is even something we'd be able to detect. My gut says no, but. I could be wrong

**Comment by andyvan-ph** [comment]
Small update on this, I'm thinking of running a survey on some existing pages to gauge satisfaction. May be useful down the line to gauge whether updates work.

**Comment by qb-harshit** [comment]
hey, i'm Harshit (co-founder of QBack.AI). if y'all are working on the comparison page use case. here's a deep dive on Amplitude using publicly available resources. it's free to use. you can log in and analyze everything about Amplitude for free. i've checked out the Vercel app—super neat. this might be handy for your team. here's a Loom video where I show it in action. feel free to delete this comment if it ain't handy.

https://www.loom.com/share/17f9e86ac9924fb788df9aa3b767fc00?sid=0d789f9e-bf46-4451-910f-fc8172cb215c
