### ISSUE TITLE
Q3 2024: Migration guides 

### ISSUE THREAD

**Issue by ivanagas** [PostHog/meta#221]
We want more people to migrate to PostHog, writing guides to make this easy is key to doing this (this is a goal for Q3 2024). These walkthrough how to migrate from other tools, provide code examples, translate their concepts to PostHog ones.

### Analytics

- [x] Google Analytics
- [x] Heap
- [x] Matomo
- [x] Mixpanel (refresh)
- [x] Amplitude (refresh)
  - https://posthog.slack.com/archives/C0374DA782U/p1720023095263899
- [x] Pendo
- [ ] ~Plausible~

### Feature flags

- [x] LaunchDarkly
- [x] Statsig
- [ ] ~GrowthBook~

### Meta

- [x] Move migration docs to same spot: https://posthog.com/docs/migrate
    - Specifically: https://posthog.com/tutorials/mixpanel-to-posthog
- [ ] Do edit pass of all existing docs
- [ ] Surface better in the docs (getting started, product pages?)

**Comment by simfish85** [comment]
Analytics: Pendo

**Comment by ivanagas** [comment]
> Looks good to me. Only suggestion, could we add Hotjar? It's the best-performing of our competitor ad campaigns by a long way, so seems like lots of people are trying to jump ship.

I'm not confident we can get a lot of data out of Hotjar as its heatmaps and session replay. I can test.

**Comment by andyvan-ph** [comment]
Was just going through old content idea request and a migration guide for Plausible was mentioned?

Fancy adding it to the list, @ivanagas?

**Comment by ivanagas** [comment]
Update: I've worked on Growthbook for the beginning of this week but it just has so many corner cases and options for every flag to write a good migration script, I am abandoning this one.

For example, the default option for an enabled boolean flag is for it to serve `false` for some reason. Also, their experiments are built on feature flags and most of the data is in experiments, but not the values calling the key provides.

It is going to be too much effort to cover all of the corner cases and even writing a basic conversion script would likely require a ton of customization afterwards. For anyone migrating, it will almost definitely be easier for them to just recreate all of their flags manually.

**Comment by ivanagas** [comment]
Plausible is similarly blocked. Their product only does aggregate report exports which could be turned into events (if the dashboard says 20 pageviews, capture 20 pageviews), but it misses out on a lot of the information. 

When web analytics takes off, we should consider a web analytics migration tool for GA, Plausible, and others.
