### ISSUE TITLE
Messaging: Stripe migration to Data Warehouse

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#222]
We'd like to migrate users on the Stripe plugin to using the data warehouse, because it's far better and means we don't have to maintain that plugin anymore. This will enable us to sunset the Stripe plugin. 

Two potential complications here are:

- We're already sending multiple emails about the data warehouse, so we don't want to bombard users. 
- Currently unsure about how complex the migration is, and if switching to data warehouse will bring in historical data straightaway

To address these, we'll:

- Delay the migration messaging to a week after the full launch. The full launch is currently planned for July 8th, so we'll plan to **send this migration messaging on July 15th**. 
- @EDsCODE and @tiina303 to feedback on email copy and update if guidance needs to change

We're not planning to give users making the migration any additional incentives or discounts for making the switch, as we already have a generous free tier. 

### Goal
Activation in data warehouse product. I'm currently setting up criteria for that. 

### Format
Single email. 

### Audience / Targeting
Tiina has provided a list of users here: https://posthog.slack.com/archives/C075D3C5HST/p1720084444661259

Cohort here: https://us.posthog.com/project/2/cohorts/76905

### Resources, timeline, responsibilities
1x email send on July 15th, by @joethreepwood

**Comment by joethreepwood** [comment]
Suggested copy for your feedback @EDsCODE @tiina303 

<img width="772" alt="Screenshot 2024-07-04 at 14 22 10" src="https://github.com/PostHog/meta/assets/84011561/1251edbc-9ffa-4479-a64c-14f9ec4f9ca6">

**Comment by joethreepwood** [comment]
<img width="617" alt="Screenshot 2024-07-08 at 10 42 38" src="https://github.com/PostHog/meta/assets/84011561/01258540-9d87-451b-ae68-6a61d9e0c182">

Typo and language fixes

**Comment by tiina303** [comment]
Looks good to me, whoever migrated our own usage might know best what is missing, e.g. folks might need to change their insights if they have any as the stripe plugin currently is sending the data as events to PostHog. Also means they might have destinations tied to it. In any case if there's problems they will complain and email back, so that's fine. Can we make that email go directly to data-warehouse support queue?

**Comment by joethreepwood** [comment]
Done

<img width="933" alt="Screenshot 2024-07-08 at 15 35 34" src="https://github.com/PostHog/meta/assets/84011561/448ae134-e1ef-4131-8596-ed193503b498">

**Comment by joethreepwood** [comment]
Now scheduled for July 15th.

**Comment by timgl** [comment]
I think "It's time to switch to our data warehouse" is going to be really confusing to people, especially if they already have a data warehouse. We should just give them the step-by-step on how to set up the stripe connector and how to use those tables, because it's very different from what the stripe plugin currently does which is create events.

**Comment by joethreepwood** [comment]
Headline and small language tweaks to update this. 

The broadcast is also currently on pause while we wait for a DW fix. 

<img width="596" alt="Screenshot 2024-07-09 at 14 08 40" src="https://github.com/PostHog/meta/assets/84011561/e30af869-2df9-4369-a351-6b1ef8ffe10f">

**Comment by timgl** [comment]
Yeah that's better, thanks!

**Comment by tiina303** [comment]
qq: why is the date 29th of August, that seems quite far away?

**Comment by joethreepwood** [comment]
I think I just carried that over from when our beta pricing going live, tbh - and it stayed because nobody raised it. 

Happy to jump it back. We should give roughly two weeks notice minimum, IMHO. I'll set it to Aug 1st.

**Comment by joethreepwood** [comment]
<img width="571" alt="Screenshot 2024-07-15 at 10 58 02" src="https://github.com/user-attachments/assets/03af75f2-bbe0-433e-aece-58fbd5afc29d">

This is now scheduled to send on Thursday. That still gives users a little under two weeks notice, but also gives time for the data warehouse main announcement to finish sending - and won't overlap with further announcements the following week.
