### ISSUE TITLE
Q3 2024: Paid Ads

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/meta#223]
## Summary

We'd like to refresh our paid ads strategy and start running some social campaigns again with new creatives. Goals are generally to support other priorities, e.g. mobile analytics awareness, burnishing our reputation for good value, awareness of us as an alternative to various established products.

## Planned outputs in order

- [x] LinkedIn campaign promoting scalability of PostHog / relevant case studies and use cases - need to look at targeting with Hey for that
- [x] New "comparative" social ad campaign focused on direct comparisons with select competitors on LinkedIn (starting with Mixpanel and Hotjar as those search ads are the best performing) (https://github.com/PostHog/meta/issues/233)
- [ ] Test these same ads out on Instagram
- [ ] New mobile analytics awareness ads on Twitter once the landing pages are ready
- [ ] Refresh of Google Ads campaign copy to include more language around value + scalability, as well as mobile/app analytics once we have those landing pages (see #226)

Things to check:
- Audience targeting esp. on LinkedIn (lists probably out of date)
- Creative - Lottie first mock, then give to Hey to make sure it is right format, layout etc.

**Comment by andyvan-ph** [comment]
Tagging @charlescook-ph @Lior539 @ivanagas @jtemperton @joethreepwood for feedback + suggestions.

**Comment by joethreepwood** [comment]
Didn't we try Instagram before, once?

**Comment by andyvan-ph** [comment]
No, was considered but we never did anything in the end.

**Comment by jtemperton** [comment]
Think we could have some fun and good success with ads/promoted posts on LinkedIn, especially if we want to push people towards, say, the newsletter or especially eye-catching blog entries. Or to promo something like [this](https://posthog.com/founders/product-market-fit-game). Happy to incorporate some paid post experimentation into my other social work once we've got a plan.

**Comment by charlescook-ph** [comment]
I like these as ideas - in terms of new channels, I think we should pick one channel to start with and work on it e.g. for a month and see what we learn, as if we do a bunch I suspect we won't learn anything definitive. 

I'd start with LinkedIn personally because the targeting is really good, and we're doing a lot of organic work on Twitter anyway via James H (plus most creative on LinkedIn is _so_ boring that we can easily stand out).

**Comment by andyvan-ph** [comment]
> I'd start with LinkedIn personally because the targeting is really good, and we're doing a lot of organic work on Twitter anyway via James H (plus most creative on LinkedIn is _so_ boring that we can easily stand out).

Starting with some case study promotions on LinkedIn. Nothing too ambitious of these, tbh, I just want to promote a few that are core ones for us. Going to use this week to make some progress on more interesting / creative ideas.

**Comment by jtemperton** [comment]
Happy to help out with copy / creative for this. Just let me know!
