### ISSUE TITLE
Messaging: Legacy plan migration

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#225]
# Messaging

### Context
https://posthog.slack.com/archives/C043VJ93L3B/p1720568728209939

### Audience / Targeting
https://docs.google.com/spreadsheets/d/1PPoHdUy2EV2EeeR-eyuzmFzoxUk2Vp8AyHWSNAKHL1E/edit?gid=1474575637#gid=1474575637

### Resources, timeline, responsibilities
1x email, from C.io, to all users in these orgs, to be sent giving them two weeks warning. 

### Requested input
_Are there any outstanding questions, potential blockers, or feedback you need? Spell it out._

### Previews
Incoming soon.

**Comment by joethreepwood** [comment]
<img width="535" alt="Screenshot 2024-07-11 at 14 50 12" src="https://github.com/PostHog/meta/assets/84011561/63ed522b-2d6e-4553-8521-3ba2b1edd5aa">

Feedback welcome, @camerondeleone @zlwaterfield @minekansu

**Comment by camerondeleone** [comment]
This looks good to me. If people respond with frustration we can say "hey, look, you got this product for free _by mistake_ for x months/years, and with sampling you can still get coverage for most scenarios for free or little cost."

**Comment by charlescook-ph** [comment]
> "hey, look, you got this product for free by mistake for x months/years, and with sampling you can still get coverage for most scenarios for free or little cost."

Why don't we actually say some version of this? Saying 'legacy plan' doesn't mean anything to a customer, only to us internally as a business. As it's written right now, it's very vague, both in terms of what I'm on and what I'm moving to.

**Comment by joethreepwood** [comment]
<img width="498" alt="Screenshot 2024-07-11 at 18 09 45" src="https://github.com/PostHog/meta/assets/84011561/7d170954-d89a-4cda-b2b2-8d51a48a5ba4">

**Comment by charlescook-ph** [comment]
Sorry couple of followup questions here:
- If the customer was already using less than 5k anyway, we could probably reframe this as 'we're moving you onto our new plan which gives you up to 5k replays free'
- If they were using way more than 5k and not paying, shouldn't we tell them 'hey heads up if you continue at your current rate, this will cost you X?' (Or something to basically avoid the annoyed shock bill effect)

**Comment by charlescook-ph** [comment]
(Don't feel strongly about this btw, if you just want to get this out then go ahead!)

**Comment by joethreepwood** [comment]
Yeah, I'd like to push ahead here and will schedule it to go out on Monday. Your second point is a good one, but it'd be just a bigger lift to get it done compared to the value I think it'd add vs just having those customers reach out to us and having a conversation. Appreciate the feedback though!

**Comment by joethreepwood** [comment]
<img width="473" alt="Screenshot 2024-07-12 at 11 47 08" src="https://github.com/user-attachments/assets/c148fdf0-d1ab-4913-96c2-7f3efeaafc22">
