### ISSUE TITLE
Continuously contribute to/support key open-source projects

### ISSUE THREAD

**Issue by leggetter** [PostHog/meta#23]
There are some pieces of software that PostHog would not exist without. We should setup a continuous monthly donation for those projects to do our part to support their continued development. An additional benefit is the visibility it will give PostHog.

What are those key projects? Please comment below👇  providing:

- Link to repo
- How we use it
- Why we should support it
- What we'd do if it went away (optional)

Analysis of our codebase to detect dependencies can be seen via https://backyourstack.com/PostHog

#### [Open Collective](https://opencollective.com)

Open Collective provides a mechanism for us to sponsor projects each month e.g. 

![image](https://user-images.githubusercontent.com/328367/132736926-8316284c-0b2f-4840-8ac7-c85fd49389d1.png)

#### [GitHub sponsors](https://github.com/sponsors)

![image](https://user-images.githubusercontent.com/328367/132743108-2a44979e-af50-4660-b1f0-6d028a4143c2.png)

#### Other

In other cases, we may need to contact the project maintainers directly.

**Comment by macobo** [comment]
I consider [rrweb](https://github.com/rrweb-io/rrweb) a critical investment.

Not only because we're already getting so much out of it, but also because we're only scratching the surface of session recording and a lot of deep technical work needs to go into making it competitive. 

Working together with the people behind it will help us accelerate that development a lot, since our own expertise is much more narrow.

Some other context under https://github.com/PostHog/product-internal/issues/86

**Comment by mariusandra** [comment]
This [graphile/worker](https://github.com/graphile/worker) is powering scheduled jobs, retries and other such logic for the plugin server. Its existence definitely saved us a lot of headache.

**Comment by paolodamico** [comment]
[DRF](https://www.django-rest-framework.org/) is pretty critical, but might be quite big already. [social-auth-core](https://github.com/python-social-auth/social-core) enables custom auth solutions purely for Enterprise and paid plans, so might make sense to support too.

**Comment by leggetter** [comment]
@timgl can you or someone else with elevated GitHub permissions please give me whatever level of access is required to make sponsorships on GitHub via PostHog? I believe **Member** should do. See https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/permission-levels-for-an-organization 

I presently get the following message when trying to create a sponsorship:

![image](https://user-images.githubusercontent.com/328367/134026754-115ff60d-06e5-45a8-95df-874ef3cfd47f.png)

https://github.com/sponsors/Yuyz0112?preview=false&sponsor=PostHog

**Comment by leggetter** [comment]
## rrweb

**Status**: Sponsoring at $100 a month. This will get us logo placement on all of the author's projects.

TODOs:

- [ ] PR against the [rrweb README](https://github.com/rrweb-io/rrweb/blob/master/README.md) to add PostHog under "Who's using rrweb"

## Django REST Framework

**Status**: Signup up. Awaiting set up which isn't fully automated.

$250 for Premium sponsorship which includes logo placement at the top of the main website. Seems like a really good way to both support the framework and get brand visibility.

![image](https://user-images.githubusercontent.com/328367/134485293-82ffd8e4-05e6-4801-9236-e9e0ada60396.png)

**Comment by benjie** [comment]
Thank you so much for your support! :heart: :rocket:

**Comment by leggetter** [comment]
https://www.rrweb.io/

![image](https://user-images.githubusercontent.com/328367/136165799-0f999bc2-624a-4118-b52d-ee9b487c5d25.png)

https://github.com/rrweb-io/rrweb

![image](https://user-images.githubusercontent.com/328367/136165893-fe58948b-ce62-4384-9174-4127248fe561.png)
