### ISSUE TITLE
Mega-ish issue: Keywords AI integration

### ISSUE THREAD

**Issue by Lior539** [PostHog/meta#231]
### Alpha/Private Beta

- [x] Dashboard template
- [x] Email mutual PostHog and Keywords AI customers
- [x] Docs page in Posthog for the integration

To be done by Keywords AI team:
- [x] Add posthog page in Keywords AI docs
- [ ] Keywords AI to include integration announcement in their newsletter/emails/changelog etc.

### Open Beta / Prod release

- [ ] Case study post(s) featuring customers using the integration
- [ ] Feature in monthly startups email (PostHog startup program)
- [ ] Changelog post 
- [ ] Changelog email
- [ ] In-app notification
- [ ] Announce via all social channels (twitter, LinkedIn, etc)
- [ ] Can we get some keywordss AI partners to promote the integration?

**Comment by Raymond1415926** [comment]
Hey @Lior539, I have built my dashboard template. How do we share this with your team?

**Comment by Lior539** [comment]
Closing as this is not a focus in Q4
