### ISSUE TITLE
Visual template for changelog social posts

### ISSUE THREAD

**Issue by jtemperton** [PostHog/meta#232]
We're working on [a plan to improve social](https://github.com/PostHog/meta/issues/218). As part of this, we're making posting changelog updates on X (and LinkedIn) a priority. Why? It helps show we've got a great product and that we ship fast.

Some great context  [here](https://github.com/PostHog/meta/issues/218#issuecomment-2250006846) from @andyvan-ph on what we want to achieve.

We want to post every single [changelog update](https://posthog.com/changelog/2024) on social. But we want to make it eye-catching and fun. The changelog already includes screenshots for _almost_ all updates so we need a neat frame to drop product screenshots into when we post changelog updates to X and LinkedIn.

This has the right kinda vibe.

![image](https://github.com/user-attachments/assets/1fb617ff-8278-4b22-b363-c906edc17ad3)

What we need is a template we can drop an image and some text into each time we post a changelog update on social. I'm thinking  TV shopping. tongue-in-cheek, playful, a little bit cheesy. Here's a mock-up to (hopefully) spark some ideas. The text of the social post would include the full details of the changelog update.

![image](https://github.com/user-attachments/assets/465eabae-2bf4-4608-a3b8-811ae2139d61)

Feedback welcome on the direction and approach! I'm going to need some help working up a final, polished template that we can use on social for all changelog updates. Thanks!

**Comment by andyvan-ph** [comment]
Tagging @joethreepwood as well since changelog is his thing.

**Comment by corywatilo** [comment]
We can use each product's color to add a little variety. Here's a version for the recent surveys update:

![image](https://github.com/user-attachments/assets/6a4dbdd7-b88c-42a9-90c3-4d31b8bcb16b)


And here's a version for a recent product analytics update:

![image](https://github.com/user-attachments/assets/b3431898-068b-477f-9903-9af6e07b09b8)

We can also vary up the hogs to make it more fun.

[Figma source](https://www.figma.com/design/CLj2U34xpNiHuZRo73GJPm/posthog.com?node-id=15286-15275&t=5PK87CnpWaejF3rI-1)

**Comment by joethreepwood** [comment]
Take or leave the design feedback, but the font in the example above doesn't feel like it matches our font/brand elsewhere: are we changing to adopt this style more generally? I'm not personally a huge fan of it, but I care more about consistency. 

I also LOVE the idea of celebrating individuals on social and building on the way I try to celebrate people in the changelog currently - but we need to respect that there's a small handful of people who have specifically requested they don't get publicised in this way. 

I assume a good way to do this is to have me select the individual when I write the changelog update, and then these images are created as an OG image for each link? In that situation, we'd just need a fall-back option which credits the whole team instead.

**Comment by corywatilo** [comment]
Yeah we could definitely templatize this:

1. ~Select product~
2. ~Choose type of update~
3. Select team member
4. ~Add a title~
5. ~Add image~
6. Choose a hedgehog

Then once the update is published, you can just grab the image from the site to use in social.

Re: font, I am intending to add a more fun font for marketing purposes to contrast with our clean brand look. Not 100% locked in on the font and still exploring options, but have been using it lately so it's consistent on that front for now.

**Comment by andyvan-ph** [comment]
Like this. Bits and bobs:

- Kind of agree with Joe on the font, but don't feel super strongly about it.
- How easy can we make these to create? Assuming it'll be @jtemperton or someone like me doing it. Replacing text etc is pretty simple, so it's more about making sure images are easy to drop in and out of a template.

- Could we use these from the teams page? I feel like we'd need to make the text on them a bigger for legibility on social, 
<img width="251" alt="Screenshot 2024-08-08 at 14 21 17" src="https://github.com/user-attachments/assets/6cbeab6f-f86e-48b3-bb6b-b726731c0fe4">

> I assume a good way to do this is to have me select the individual when I write the changelog update, and then these images are created as an OG image for each link?

Just an FYI, we wouldn't be posting links, so no need to go the OG image route.

**Comment by corywatilo** [comment]
>How easy can we make these to create?

Yes, it would literally be us adding a couple extra fields on the changelog form that we'd use to auto-generate these.

<img width="711" alt="image" src="https://github.com/user-attachments/assets/88fd0be2-0c09-4133-ad9c-c1f88704c878">


> Could we use these from the teams page?

We've discussed making mini versions of the crests that are usable at smaller sizes. Don't think we've had any movement on that so I've [created an issue](https://github.com/PostHog/posthog.com/issues/9136).

Hence why I've left them out for now, but maybe in the future we can adjust if we have the assets to support it.

> no need to go the OG image route

OG generation would be the easiest way to support this, so having these as OGs is a byproduct.

**Comment by joethreepwood** [comment]
This all seems great. Agree that OG is the best way to go - and if helpful then I can sink an hour or so into going through old changelog stuff too and applying fields there.

**Comment by andyvan-ph** [comment]
> OG generation would be the easiest way to support this, so having these as OGs is a byproduct.

Ah, good to know. So long as it's easy to pull the image so we don't have to post a link, that's all good.

**Comment by jtemperton** [comment]
This looks great. Agree we maybe want the font to be a little more... fun? And I'm fine to do some manual tweaking if we can't automate it all based on the changelog field. Just let me know. Thanks!

**Comment by corywatilo** [comment]
Tracking implementation of this in the issue linked above ☝️

**Comment by joethreepwood** [comment]
Attached to this: I have now individually chased everyone without a community bio, asking them to write one.
