### ISSUE TITLE
Messaging: Overcharge response, Aug 2024

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#236]
# Messaging

### Context
31 users got charged too much due to a bug: https://github.com/PostHog/billing/pull/830

We declared an incident, solved the issue, refunded the amount, and all in less than 24 hours. But we should still tell people. 

Proposed comm, for approval by @raquelmsmith - will be targeted just to affected individuals.

<img width="1035" alt="Screenshot 2024-08-16 at 15 15 25" src="https://github.com/user-attachments/assets/7dc75bc7-393b-449e-acb6-ead6602a1544">

**Comment by joethreepwood** [comment]
@raquelmsmith if you let me know the customer who originally reported this, I'll merch them too.

**Comment by raquelmsmith** [comment]
@joethreepwood customer is in this zendesk ticket: https://posthoghelp.zendesk.com/agent/tickets/16849 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19213)

What's the link you have to "fixed the bug"? The fix was in the billing repo, so isn't publicly available.

**Comment by joethreepwood** [comment]
> What's the link you have to "fixed the bug"? The fix was in the billing repo, so isn't publicly available.

Ah, I was linking to the PR but didn't realize it was private. Will remove that now.

**Comment by joethreepwood** [comment]
Updated the copy in the email, to reflect that it's just 8 users. 

Will schedule this for Monday AM, BST.

**Comment by joethreepwood** [comment]
<img width="568" alt="Screenshot 2024-08-16 at 16 29 30" src="https://github.com/user-attachments/assets/1d619559-7ecb-4f7d-bd19-3483efd782ad">
