### ISSUE TITLE
Messaging: New Billing Emails in Customer.io

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#237]
# Messaging

### Context
RFC: https://github.com/PostHog/product-internal/pull/636
Art: https://github.com/PostHog/posthog.com/issues/9198

Starting to get ahead of this by building it all into Customer.io to discover where we need work. For now, I'll just build it into one campaign that splits by properties -- but in the future we'll likely want to set up multiple campaigns.

**Comment by joethreepwood** [comment]
<img width="746" alt="Screenshot 2024-08-19 at 12 53 20" src="https://github.com/user-attachments/assets/0fb393aa-8aed-4f8f-9f87-8dae4af131c9">

Quick mock-up for a first draft. One outstanding question is where we want these emails to be sent from. Hey@posthog.com is default, but we can use a different one if we want to enable replies, @zlwaterfield ?

**Comment by joethreepwood** [comment]
Quick look at how some of these are shaping up in first draft. 

<img width="822" alt="Screenshot 2024-08-20 at 15 23 14" src="https://github.com/user-attachments/assets/ed120da2-e90a-4368-9850-18f58ff2b175">

<img width="829" alt="Screenshot 2024-08-20 at 15 25 51" src="https://github.com/user-attachments/assets/fa87808a-9b6c-4440-9b0c-d56affc79f48">

<img width="835" alt="Screenshot 2024-08-20 at 15 27 26" src="https://github.com/user-attachments/assets/c13c4acb-3829-41f4-b244-af45d735ffc8">

<img width="832" alt="Screenshot 2024-08-20 at 15 29 19" src="https://github.com/user-attachments/assets/7842616d-3390-47e2-acde-0141a2146298">

<img width="836" alt="Screenshot 2024-08-20 at 15 30 33" src="https://github.com/user-attachments/assets/641d4569-dc8d-4f50-9338-81ef8205a288">

<img width="824" alt="Screenshot 2024-08-20 at 15 31 39" src="https://github.com/user-attachments/assets/2a6abd82-2825-4b32-93c1-5c9bee3e6d53">

<img width="825" alt="Screenshot 2024-08-20 at 15 35 55" src="https://github.com/user-attachments/assets/070d12fd-cf01-4a8d-ab87-ef928fc9d69d">

<img width="828" alt="Screenshot 2024-08-20 at 15 37 12" src="https://github.com/user-attachments/assets/e95c4bd2-d5e7-4ee0-8d1c-d0d1ddd2ef5c">

<img width="836" alt="Screenshot 2024-08-20 at 15 39 04" src="https://github.com/user-attachments/assets/cf714acd-5a98-43d8-9c4b-86a7180dd41f">

<img width="828" alt="Screenshot 2024-08-20 at 15 39 34" src="https://github.com/user-attachments/assets/04db97be-67f7-4f30-81f2-12765bbf0bbe">

<img width="824" alt="Screenshot 2024-08-20 at 15 40 17" src="https://github.com/user-attachments/assets/b8d1f87f-1fa2-4546-bbd2-2118ea673bb1">

<img width="824" alt="Screenshot 2024-08-20 at 15 42 57" src="https://github.com/user-attachments/assets/bd9143a6-c314-4f90-b756-aba80b08a460">

**Comment by zlwaterfield** [comment]
These looks awesome - thank you for putting these together so quickly :) 

Few notes:

- The startup one should never trigger. I think we've moved everyone off that, but it's good to have it just in case.
- I need to review all these triggers and ensure we align on the event parameters so they are all triggered correctly. I will work on that later this week.
- Let's make sure the invoice totals are formatted nicely. We've had some issues with that in the past. 
- For the allowance reset email - I think there's room to improve and add clarification _why now_. It's based on their subscription billing dates and the email doesn't explain that well, it can come off as a bit random. I realize this could be said for all emails but it popped out at me for this one. 
- Thought: we don't have emails for removing addons, we should probably add them.

**Comment by raquelmsmith** [comment]
These are great! 

- 80% limit one - sentence "Which know _we'd_ prefer you to do" reads weird. Maybe "Which we would obviously prefer you to do ;)"
- 100% free allowance one - "you can set billing limits" (not bill limits)
- Updated limits one - should we list what the limits are?
- Startup plan ending one - we should add what their forecasted bill is and don't so strongly suggest billing limits. Limits aren't great for customers in a lot of situations - they lose data. It's better for them to tune their usage so they get everything they need but don't collect the things they don't.
- You've sub'd to posthog - the vast majority of people who sub don't ever pay us money. I'd focus this on having unlimited usage (that you pay for) and better features. And maybe promote the Teams plan 👀 
- First bill - link to controlling usage first, then billing limits

**Comment by joethreepwood** [comment]
Will roll with those amendments and add more polish shortly, thanks both! 

For now, two new previews.

<img width="552" alt="Screenshot 2024-08-20 at 16 38 47" src="https://github.com/user-attachments/assets/42ee559b-a8be-42ac-847b-39d3ee64b1fd">

<img width="828" alt="Screenshot 2024-08-20 at 16 37 47" src="https://github.com/user-attachments/assets/8ea91e7f-dfba-4837-aed3-20cf54fef29c">

**Comment by joethreepwood** [comment]
I've made all the suggested amends, with a couple of further discussions below...

> * The startup one should never trigger. I think we've moved everyone off that, but it's good to have it just in case.

> * Startup plan ending one - we should add what their forecasted bill is and don't so strongly suggest billing limits. Limits aren't great for customers in a lot of situations - they lose data. It's better for them to tune their usage so they get everything they need but don't collect the things they don't.

I've replicated the new art and message into the dedicated startups flow, but keeping this just in case as you say and have made the other changes. 

> * Let's make sure the invoice totals are formatted nicely. We've had some issues with that in the past.

Yep, I can't mock these up just yet because I need to have that data sent on the event so I can grab it - which I can't do until we start getting the integration moved across. What sort of issues have you had in the past?

> * For the allowance reset email - I think there's room to improve and add clarification _why now_. It's based on their subscription billing dates and the email doesn't explain that well, it can come off as a bit random. I realize this could be said for all emails but it popped out at me for this one.

How's this? Little confused if this is for free users, paid users, or both. Free users don't have a billing subscription date, do they?

```
We've reset your free allowance, giving you more free usage for every tool. We do this every 30 days from your subscription date.

Last month we began dropping data because you hit 100% of your free allowance. Now, we've resumed ingestion as normal for you.

In the future you can that by [upgrading your plan](https://us.posthog.com/organization/billing), which also lets you add custom billing limits to help you control your costs too.
```

> * Thought: we don't have emails for removing addons, we should probably add them.

I need to know an event for these, but we could easily do something like this and adapt it for each one (or include the add-on name if it's set as an event property). 

<img width="695" alt="Screenshot 2024-08-21 at 11 51 51" src="https://github.com/user-attachments/assets/7b1fae79-4724-4349-a86c-a0b674b5902a">

> * 80% limit one - sentence "Which know _we'd_ prefer you to do" reads weird. Maybe "Which we would obviously prefer you to do ;)"

Changed to:
`Your limit resets each month, but you can increase the limit to give yourself more breathing room (and maybe give us more money).`

> * Updated limits one - should we list what the limits are?

I can do this, I just need the limits to be set on the event as a property so I can read it in Customer.io - then it's an easy add.

**Comment by zlwaterfield** [comment]
@joethreepwood how do you handle links to EU and US. Are they dynamic based on a property on the customer? 

Few other points
- for the failed payments, we send it for every failed payment, so maybe we can update the copy to say the attempt number? Or how many attempts are left? I can make these properties in the event.
- for the billing limit email, can we display the product and total like we do in the current emails?

**Comment by joethreepwood** [comment]
> @joethreepwood how do you handle links to EU and US. Are they dynamic based on a property on the customer?

From what I know, we route people to the correct domain, yes. I'm actually not sure how it works though. Usual pattern in all our emails is to send people to either `us.posthog.com` or `app.posthog.com` and they'll be switched to EU if needed. 

> * for the failed payments, we send it for every failed payment, so maybe we can update the copy to say the attempt number? Or how many attempts are left? I can make these properties in the event.

> * for the billing limit email, can we display the product and total like we do in the current emails?

For these I _think_ we can do this as long as we're updating the property on the event. It's not something we've done before for repeated emails, but we should be able to use a bit of Liquid to pull in the variable off the event property.
