### ISSUE TITLE
Messaging: Web Analytics announcement emails

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#239]
# Messaging

As per https://github.com/PostHog/meta/pull/179

Plan is to have two emails. One for the 13,000 users in the beta. One for everyone else. 

Beta users are going to get an exclusive hedgehog for hedgehog mode as a reward: https://github.com/PostHog/posthog.com/issues/9298

@robbie-c and I have discussed two potential ways to position web analytics: 

1. Around value and price. Basically: First, we made everything cheaper. Now we're giving you more value for your cheapest events, with web analytics. 
2. Around GAs unpopularity. Basically: GA4 is horrible, so we built our own version for engineers. 

We're going to move forward with the first option, as it helps reinforce our position as the cheapest product analytics tool. 

CTA wise we'll direct everyone to the web analytics product page. 

Previews to come.

**Comment by joethreepwood** [comment]
<img width="734" alt="Screenshot 2024-09-06 at 12 58 20" src="https://github.com/user-attachments/assets/117aa703-6b7d-4296-95bb-f43d12b6033d">

Initial version for thoughts, @robbie-c @charlescook-ph @andyvan-ph

**Comment by joethreepwood** [comment]
Early first draft of the beta version too

<img width="682" alt="Screenshot 2024-09-06 at 16 17 58" src="https://github.com/user-attachments/assets/b3970649-d808-4e15-98d3-44060eea9775">

**Comment by corywatilo** [comment]
I worked a bit on setting this up in [a new email template](https://fly.customer.io/workspaces/127208/journeys/layouts/6) but didn't quite finish it:

- Isn't set up as a customizable template - it's just hard-coded right now
- Footer links aren't linked
- Didn't get to the beta callout

I'm out Mon-Wed, so if the plan is to get this out before then, go ahead and use the old template and I'll try to get this ready for the next one.

<img width="745" alt="image" src="https://github.com/user-attachments/assets/82db3270-885c-4b55-975d-c3153c157577">

**Comment by robbie-c** [comment]
> It's easy to migrate from GA4, too

If I saw this I would expect that I could import my data, but this isn't something we've built.

What does "our version of Google Analytics" link to?

Other than that I really like this :)

**Comment by joethreepwood** [comment]
It links to the Web Analytics product page

**Comment by joethreepwood** [comment]
We now have a [cohort](https://us.posthog.com/project/2/cohorts/85524#panel=exports) of users who we're considering in the beta (5x accessed web analytics) - 20,000 of them.

**Comment by joethreepwood** [comment]
<img width="711" alt="Screenshot 2024-09-16 at 10 04 00" src="https://github.com/user-attachments/assets/c446342e-ad7f-49a1-88ea-a3bd4417caf6">

<img width="626" alt="Screenshot 2024-09-16 at 10 04 08" src="https://github.com/user-attachments/assets/b2ad21b3-b83c-42ee-b0c4-659ec1a1ac6a">
