### ISSUE TITLE
Marketing Experiment: Sponsor Data Science Weekly

### ISSUE THREAD

**Issue by leggetter** [PostHog/meta#24]
# Experiment

## Context

We're attempting to raise awareness, acquire, and activate data engineers on the PostHog platform. We've identified a number of newsletters to sponsor. [Data Science Weekly](https://www.datascienceweekly.org/) was one of those newsletters.

Latest issue of DataScience Weekly: https://mailchi.mp/datascienceweekly/data-science-weekly-issue-928254

#### Goal

We're attempting to raise awareness, acquire, and activate data engineers on the PostHog platform.

#### Hypothesis

We're looking to grow the number of reference-type customers on the PostHog platform and our hypothesis is that we are introduced into those companies by Data Engineers. Sponsorship/advertisement on a Data Science focused newsletter will put the PostHog brand and value prop in front of a target audience.

#### Campaign details

All ad details to be sent to Data Science Weekly 48 hours before the newsletter publish date.

Publish date: _28 Oct_

- URLs: https://posthog.com?utm_source=datascienceweekly&utm_medium=email&utm_campaign=dsw-28-oct
- logo
- ad title
- ad copy (Max 100 words)

Publish date: _4 Nov_

- URLs: https://posthog.com?utm_source=datascienceweekly&utm_medium=email&utm_campaign=dsw-4-nov
- logo
- ad title
- ad copy (Max 100 words)
 
Publish date: _11 Nov_

- URLs: https://posthog.com?utm_source=datascienceweekly&utm_medium=email&utm_campaign=dsw-11-nov
- logo
- ad title
- ad copy (Max 100 words)

#### Audience

Data Science Weekly newsletter subscribers: Data Scientists and other people interested in Data Science.

#### Resources and timeline
_How long will this experiment run for?_

Three (3) weeks from 28 October 2021. See Campaign details, above.

### Tracking
_How are we tracking results of this experiment? Include any UTM parameters or other relevant details._

See URLs, above.

### Primary
_What is the primary metric to help us track our hypothesis?_

See funnel, below.

##### Pre-experiment baseline:
_What is the baseline value for this metric? Add a link to a PostHog chart._

We don't have a baseline value. We'll look to establish one here.

https://app.posthog.com/dashboard/13064

##### Why 
_Why is this the metric? What does it indicate about the hypothesis?_

This gives us visibility across a desirable journey. I wouldn't expect too many to fully convert. As above, this is an experiment that will help us establish a baseline and understand what we can achieve here.

![image](https://user-images.githubusercontent.com/328367/132824222-9162e9d7-a748-4f03-9265-57b8617421f6.png)

## Results
_What are the top learnings from this experiment?
What impact was there on the primary metric or any secondary metrics?
What are the next steps based on the learnings of this experiment?_

**Comment by leggetter** [comment]
@joethreepwood - would you be able to help me craft three (3) ads for this newsletter? I'm assuming we'll utilise the [messaging framework](https://posthog.com/handbook/growth/marketing/messaging_framework)?

As above, the focus is to reach and resonate with Data Engineers.

Once we've got the three ads we can potentially request some artwork too.

**Comment by piemets** [comment]
> @joethreepwood - would you be able to help me craft three (3) ads for this newsletter? I'm assuming we'll utilise the [messaging framework](https://posthog.com/handbook/growth/marketing/messaging_framework)?

I'd personally use the [value props sheet](https://docs.google.com/spreadsheets/d/1VVLqk8xiKPj_rzDDhVA2eMFx7ENlhg9WnYDj2rkd_E4/edit#gid=1752905631) as they are more current and I don't think @joethreepwood has had time to update the framework yet with the new messaging we're now using across the site in terms of self-host, data warehouses etc. 

For creating the ads in case it's helpful @lottiecoxon made this [nifty Figma file](https://www.figma.com/file/MRmFaOSXV1zYTGnOODGyCc/Social-Media?node-id=1307%3A13884) with a bunch of templates that I usually use for Twitter, LinkedIn etc.

**Comment by joethreepwood** [comment]
> > @joethreepwood - would you be able to help me craft three (3) ads for this newsletter? I'm assuming we'll utilise the [messaging framework](https://posthog.com/handbook/growth/marketing/messaging_framework)?

Yep. Will draft some in a doc and share by end of day. 

> I'd personally use the [value props sheet](https://docs.google.com/spreadsheets/d/1VVLqk8xiKPj_rzDDhVA2eMFx7ENlhg9WnYDj2rkd_E4/edit#gid=1752905631) as they are more current and I don't think @joethreepwood has had time to update the framework yet with the new messaging we're now using across the site in terms of self-host, data warehouses etc.

This is my first to-do item next week, FYI. Apologies it has taken me a while, had a lot to clear this week.

**Comment by joethreepwood** [comment]
[Some quick copy options, based on looking at the formatting they used in past issues.](https://docs.google.com/document/d/14kEQsv2R10Y8km9JrpIJ8gebewRMYYc7h7gBdQ3E29k/edit?usp=sharing)

**Comment by leggetter** [comment]
- Nearly $2k for sponsorship
- 955 pageviews
- 245 unique users
- 0 signups
- $8.16 per user

<img width="1208" alt="Screen Shot 2021-11-16 at 21 19 02" src="https://user-images.githubusercontent.com/328367/142067369-68737530-d7c1-454f-a7f4-8b05a8349df8.png">

![image](https://user-images.githubusercontent.com/328367/142067769-666e8522-ba59-4c97-bda4-0d8afb555604.png)
