### ISSUE TITLE
Messaging: Webhook & Old Pipeline Migration

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#244]
# Messaging

### Context
The short version, via @mariusandra:

> the tldr is that we have "slack action webhooks" and "old real time pipeline destinations" that we want to move users off of. Both of them have a one-click migration button (see the link above for one example). We want to tell users "hey, this is happening, click the button to migrate yourselves, otherwise, remember, on the 5th of november, we're going to treason and plot and move you all over automatically... you just have a chance to test that everything is according to his majesty's highest standards yourself if you want"

### Goal
Email to all users who are using the old versions, telling them they need to migrate by the 5th November (this is an arbitrary deadline for now). 

@mariusandra will get a cohort / list of all org_ids for targeting. It'll be two emails: one sent now, one reminder sent closer to the time. 

### Previews
Coming shortly.

**Comment by joethreepwood** [comment]
First draft, for your approvals @benjackwhite and @mariusandra 

<img width="495" alt="Screenshot 2024-09-30 at 15 25 41" src="https://github.com/user-attachments/assets/f73657e3-807a-4cfa-9e02-e8743899eab5">

**Comment by joethreepwood** [comment]
<img width="665" alt="Screenshot 2024-09-30 at 15 27 02" src="https://github.com/user-attachments/assets/76306583-f462-421a-b805-b79d39a19a8d">

**Comment by joethreepwood** [comment]
Corrected the footer

<img width="657" alt="Screenshot 2024-09-30 at 15 32 14" src="https://github.com/user-attachments/assets/958c6686-4004-437c-b581-2fe7a9f16024">

**Comment by joethreepwood** [comment]
> I think it's great. We will likely want to send some reminders (increasingly stronger nudges) in the weeks leading up to the deadline. This should give us enough early users to start with.

Yep - but once we have base comm, the reminder is easy. 

> What's the best format for you to receive this? A cohort in PostHog? List of team_ids? List of emails?

Cohort is probably easiest!

**Comment by ivanagas** [comment]
Just merged some potentially helpful docs updates for this too: https://github.com/PostHog/posthog.com/pull/9489

**Comment by mariusandra** [comment]
Some more TODOs
- [ ] Release [the flag](https://us.posthog.com/project/2/feature_flags/50654) / [feature](https://us.posthog.com/project/2/early_access_features/01912264-8c92-0000-5e0e-386f59cfdeec)
   - Note: Releasing the flag removes the ability to create new action-based slack webhooks, invalidating a bunch of documentation
- [ ] PR to update docs to remove all mentions of
    - [ ] "Pipeline Destinations 3000" early access feature
    - [ ] Action-based Slack Webhooks
    - [ ] Project settings "Webhook Integration" 
- [ ] PR to remove the [Webhook Integration](https://us.posthog.com/project/2/settings/project-integrations#integration-webhooks) from project settings. (It should still remain if you have unmigrated actions)
- [ ] Create a test cohort of users (here's an unexported [list](https://us.posthog.com/project/2/insights/Xi5JsdwM/edit))

**Comment by joethreepwood** [comment]
I've updated the CTA with a link to Ian's new docs. 

And I've specced out a reminder email below, which we can send closer to the time. I'm basically prepped (minus the cohort), so relying on you to let me know when you want the deadline to be and you're ready for me to send @mariusandra 

<img width="480" alt="Screenshot 2024-10-01 at 12 21 10" src="https://github.com/user-attachments/assets/2b79c160-83f4-421f-ba51-221a4d485bf0">

**Comment by joethreepwood** [comment]
First email:
<img width="499" alt="Screenshot 2024-10-03 at 11 20 58" src="https://github.com/user-attachments/assets/a941ee5c-5559-46f8-99f5-6ee046d873c0">

Reminder, 1 week ahead of deadline:
<img width="614" alt="Screenshot 2024-10-03 at 11 22 44" src="https://github.com/user-attachments/assets/a0c0bff5-3f73-4e8a-a48b-dab28976811a">
