### ISSUE TITLE
Messaging: New teams upsell

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#247]
In the Teams growth review with @PostHog/team-growth @jamesefhawkins suggested we could have an upsell email for the Teams plan which triggered when users invite a number of users. It wasn't a bad idea!

I've built a new campaign today. It triggers when a user has invited 5x new team members as long as they are NOT on the teams plan already. These users enter the campaign and we then wait until the invite their 6th user, at which point we send this email. 

<img width="570" alt="Screenshot 2024-10-08 at 17 17 48" src="https://github.com/user-attachments/assets/092b1108-d3b5-410b-9a2f-4f339967af12">

We then wait 4x weeks so we're not being annoying and, the next time they invite someone, they trigger this. 

<img width="647" alt="Screenshot 2024-10-08 at 17 17 31" src="https://github.com/user-attachments/assets/8b528b31-ebf0-46e4-83e8-d8e32f313958">

Users will then exit the campaign if they activate with the Teams plan at any point. 

One downside of this is that I can't see a way to target this so we exclude users on the Enterprise plan currently, but we may just have to accept that.

**Comment by zlwaterfield** [comment]
Thanks for the quick turn around on it.

Is 5 users too early? Should we do 10?

1st one:
- we could also say at a fraction of the cost of typical enterprise maybe? Not sure if that would conflict with the new enterprise plan we are launching. 
- I don't think the contracts link makes sense here

2nd one:
- maybe re-list some of the feature?

**Comment by joethreepwood** [comment]
> Is 5 users too early? Should we do 10?

It's currently 5k people in the 5x user segment. It drops to 3k at the 10x. 

Personally, I think the slightly lower end is a good place to aim. 

> * we could also say at a fraction of the cost of typical enterprise maybe? Not sure if that would conflict with the new enterprise plan we are launching.

Yeah, issue here is that users may already be on the Enterprise plan. 

> * maybe re-list some of the feature?

<img width="532" alt="Screenshot 2024-10-08 at 17 43 25" src="https://github.com/user-attachments/assets/f521ca38-bce9-4e09-87a7-fdd82dcfecdf">

**Comment by zlwaterfield** [comment]
Changes look and sounds good on the numbers.

Will we be backfilling this for existing users? Or just ones that hit it from here on it?

**Comment by joethreepwood** [comment]
> Will we be backfilling this for existing users? Or just ones that hit it from here on it?

It'll backfill all the existing people who have invited 5+ users into the campaign, but will only trigger when they next invite someone. That'll get this working fastest. 

Now launched!
