### ISSUE TITLE
Messaging: Startups & YC Flows 3.0

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#249]
# Messaging
We've seen some repeated issues with [the old startup flows](https://github.com/PostHog/meta/issues/245). These have come down to a few things, including:

- Anonymized users (solved by removing the option)
- Users triggering both the `plan_added` and `backfill` event (fix unknown)
- Me messing up a workflow (they're complex; I'm stupid)
- Users triggering events incorrectly (various causes)
- Some events not firing (@zlwaterfield has fixed, we think)

As a result, we need to change things up. I think the best solution here will be to split the current two campaigns (one for backfill, one not) into more campaigns which each trigger a specific email based on a single event. 

Best case: This will solve the issues, remove any logic problems, and mean that users more reliably get the correct emails. 
Worst case: We'll compartmentalize any problems, remove any logic problems, and have a better view of where things go wrong. 

What I'm proposing is we completely deactivate the existing Startup flows and replace with four more campaigns: 

- One which triggers whenever the `plan_added` event fires, sends a welcome email
- One which triggers whenever the `50_percent` event fires, sends a warning and an internal sales email
- One which triggers whenever the `75_percent` event fires, sends a warning and an internal sales email
- One which triggers whenever the `bonus_added` event fires, sends a bonus and goodbye

Going forward there shouldn't be any situations where users trigger the removal event. Instead, they should trigger the `bonus_added` event, and we can tell them: Goodbye, here's a bonus. 

Content for these emails doesn't need to change based on what's used in the existing flows.

**Comment by joethreepwood** [comment]
I'll just link directly to the new flows here, for quicker approvals: 

- Welcome: https://fly.customer.io/workspaces/127208/journeys/campaigns/115
- 50%: https://fly.customer.io/workspaces/127208/journeys/campaigns/116
- 75%: https://fly.customer.io/workspaces/127208/journeys/campaigns/117
- Bonus and Goodbye: https://fly.customer.io/workspaces/127208/journeys/campaigns/118/

@minekansu and @zlwaterfield let me know your thoughts on this approach!

**Comment by zlwaterfield** [comment]
@joethreepwood this looks good to me.

Few thoughts:
1. I can update the events to be like the transactional emails with a property if you want them in the same campaign (just LMK)
2. Can we still make sure we don't trigger the same email for a user twice in the case an event does get triggered twice?

**Comment by zlwaterfield** [comment]
Note: we will still send `startup_plan_customer_removed` and `startup_plan_balance_100_percent` but they can be ignore from a campaign perspective.

**Comment by joethreepwood** [comment]
> 1. I can update the events to be like the transactional emails with a standard startup event name and a property to differentiate the event type if you want them in the same campaign (just LMK)

No need for that now, as I've built them out already. Thanks though!

> 2. Can we still make sure we don't trigger the same email for a user twice in the case an event does get triggered twice?

Yep. I can set it to be once only. 

> Note: we will still send startup_plan_customer_removed and startup_plan_balance_100_percent but they can be ignore from a campaign perspective.

Yeah, I don't think we need this for messaging anymore. 

Launching today!
