### ISSUE TITLE
Data Elixir sponsorship

### ISSUE THREAD

**Issue by leggetter** [PostHog/meta#25]
We've agreed to run sponsorship for three issues taking the Secondary Ad placement:

![image](https://user-images.githubusercontent.com/328367/133781230-a662e39b-e497-4233-bc8c-9c893c828336.png)

So we require:

- a headline of up to ~55 chars
- body text of 1 to 5 lines at ~70 chars per line

The dates for this are:

- January 4th
- January 18th
- January 25th

The placement of this advert is after the tutorials section so we may want to consider linking to some sort of tutorial?

**Comment by joethreepwood** [comment]
@leggetter Can I get a deadline of when you need this copy? 

If you don't need it until January we should probably wait until closer to the time.

**Comment by joethreepwood** [comment]
I've made a note to work on this as we get closer to the time and will share content directly with Lon, who Phil has introduced me to over email.

**Comment by joethreepwood** [comment]
[Drafted some copy. ](https://docs.google.com/document/d/13fWP0ZSV-Sy2e-CF3Dn1KpzIUdxqFOMxNQ03GoQ2R0s/edit?usp=sharing)

Will leave here for 24 hours in case of feedback, then send later this week.

**Comment by joethreepwood** [comment]
[Tracking results here. ](https://app.posthog.com/insights/GP60iDIp?insight=TRENDS&display=ActionsLineGraph&interval=day&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%5B%22https%3A%2F%2Fposthog.com%2Fproduct%3Futm_source%3Ddata%2Belixir%26utm_campaign%3D1%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3A%22First%20Ad%20-%20Jan%204th%22%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22%24pageview%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%5B%22https%3A%2F%2Fposthog.com%2Fproduct%3Futm_source%3Ddata%2Belixir%26utm_campaign%3D2%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3A%22Second%20Ad%20-%20Jan%2018th%22%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%2C%22name%22%3A%22%24pageview%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%5B%22https%3A%2F%2Fposthog.com%2Fproduct%3Futm_source%3Ddata%2Belixir%26utm_campaign%3D3%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3A%22Third%20Ad%20-%20Jan%2025%22%7D%5D&properties=%5B%5D&filter_test_accounts=true&new_entity=%5B%5D)

**Comment by charlescook-ph** [comment]
@joethreepwood can we close this one? Seems like it's run its course.
