### ISSUE TITLE
Meet with Kevan for Technical Interview

### ISSUE THREAD

**Issue by fruitvale** [PostHog/meta#258]
Hi @joethreepwood! In the spirit of step-on-toes/bias-to-action, here is our google meet for the technical interview -- November 13, 4 pm your time. I've also sent you a calendar invite: 
https:// meet.google.com/gbo-dbqv-keh

**Who is Kevan Gilbert again?**
Candidate for the Product Marketer role, who just moved through the culture screen interview with Coua  

**Why is Kevan sending me this?**
I was asked to fill out a bundle of available times via the Ashby interface, but it created a lot of unproductive possibilities given our timezone overlaps. The best time for us us 8 am PST / 4 pm your time. Each time we don't land on a day, we lose a day. Yesterday was a public holiday in Canada (Remembrance Day), shortening the week already. 

**But why?**
Your culture handbook says your Slack is mostly for informal use, and you, like, never use email. Your to-do list says you got a great deal going on, and I wager one of those items shouldn't be "endlessly coordinate next stages of interviews. The recent send from [Lenny's Newsletter](https://www.lennysnewsletter.com/p/product-manager-is-an-unfair-role) suggested Tal Raviv's "unfair" secret of just plain-old scheduling things. 

**What if this time doesn't actually work?**
Oh, no worries at all. Here's my [Google appointment slots](https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ0Cvf16GOAfupJLB_cn5di1F0xyEk8wgktBHEKXRfhfX-V6DLSPC4zVRlN0w0Q44ucItNL1W76w). Feel free to pick one that works better!

**Comment by joethreepwood** [comment]
Hey Kevan -- Thanks for this, but the proposed time works fine for me as Kendall and Coua have access to my calendar. Looking forward to chatting! 

For now, I'm going to close this out as we can discuss everything on the call tomorrow, and remove the Google Meet link as it's a public meeting.
