### ISSUE TITLE
Seeking an owner for the PostHog community homepage

### ISSUE THREAD

**Issue by corywatilo** [PostHog/meta#260]
i'm looking for an owner for the editorial content on posthog.com/community

![image](https://github.com/user-attachments/assets/1204ee5b-694a-4ad5-993a-81918b11e115)

i hard-coded some bits i had planned on us updating, and there are also sections that could just use someone keeping an eye on them to make sure they stay fresh.

- max quote - i literally generated with this chatgpt while creating the original wire and haven’t updated it since. we could even just generate a dozen of them and have them cycle through.
- from the posthog slack - i try to keep an eye on interesting things to share with the community, in order to seed these topics for others to post. we have a slack app that makes it easy - just hit the … menu → Message shortcuts → Publish to [posthog.com](http://posthog.com/) and you can set the topic
- meet a team member. would be cool to cycle through this once a month at minimum.
- featured swag - we can probably automate this, but we can also use it to push specific things if we care enough.
- musing from the ceo - just a random tweet i found. we could also just load up a bunch of these, or have them cycle through on a time period (bi-weekly, etc)

everything else is updated automatically.

tagging some obvious candidates: @bijanbwb @daniloc @ivanagas @Lior539

**Comment by andyvan-ph** [comment]
Bijan is the man :)
