### ISSUE TITLE
Django Rest Framework open-source sponsorship

### ISSUE THREAD

**Issue by leggetter** [PostHog/meta#28]
## TODOs

- [x] Create DRF Pull Request
- [x] Get images
- [x] Update https://posthog.com/handbook/growth/marketing/open-source-sponsorship

---

Pull request to add PostHog as Premium sponsor here:
https://github.com/encode/django-rest-framework/pull/8193

## Artwork Request

**Deadline**: no specific deadline

@lottiecoxon - I have two image requests, please. Are we willing to consider vertical logos where the hedgehog is above the text?

1. for the following with dimensions 275 x 250 
![image](https://user-images.githubusercontent.com/328367/135616427-dec3dac6-cf89-4334-8408-2635b485684d.png)
2. for the following at 130 x 130 (excluding the text below the logo)
![image](https://user-images.githubusercontent.com/328367/135616223-0762e249-c301-4c8f-96d7-8016e0a2b02f.png)

**Comment by lottiecoxon** [comment]
Can do! If you could add a deadline to this that would be ideal :)

**Comment by lottiecoxon** [comment]
### Three options for you 
<img width="832" alt="Screenshot 2021-10-05 at 10 13 16" src="https://user-images.githubusercontent.com/65415371/135995202-2e55d122-f572-4c8b-954c-ce4e7f61a33d.png">
<img width="823" alt="Screenshot 2021-10-05 at 10 13 21" src="https://user-images.githubusercontent.com/65415371/135995230-d0d95402-b1f5-4358-b310-f66183bf867f.png">
<img width="826" alt="Screenshot 2021-10-05 at 10 13 38" src="https://user-images.githubusercontent.com/65415371/135995248-3fb302a0-ca9a-4e20-ac40-05a9de00c8bf.png">

**Comment by leggetter** [comment]
Thanks @lottiecoxon. I'd vote for vertical with logo + text.

**Comment by leggetter** [comment]
Actually...

1. 275 x 250 ... hog + text
2. 130 x 130 ... just the text since the text appears as text on the page

**Comment by lottiecoxon** [comment]
ah silly me

**Comment by lottiecoxon** [comment]
### Did you mean this?
**Little** with no text 
![small_square_logo](https://user-images.githubusercontent.com/65415371/135996800-d49fe024-32d9-441a-98d9-4c7596287a67.png)
**Large** with text
![square_logo](https://user-images.githubusercontent.com/65415371/135996807-e6d71622-63d4-4610-b30f-5ee582521b32.png)

**Comment by leggetter** [comment]
@lottiecoxon - PERFECT! Thank you.

**Comment by leggetter** [comment]
README updated. Website updated on next build.

![](https://user-images.githubusercontent.com/647359/136030811-68b267c5-b2fa-4c54-a14a-b3e59bbf74d6.png)
