### ISSUE TITLE
Create Meetup/Event Small Drop Ship in Printfection

### ISSUE THREAD

**Issue by leggetter** [PostHog/meta#31]
_This may not be the right solution for larger events where we have a booth but will be suitable for meetups and socials._

Create a Drop Ship in Printfection that we can use whenever we host or attend a meetup.

![image](https://user-images.githubusercontent.com/328367/136054949-157974f4-d76c-4508-bd30-2390143b5851.png)

## Status

Once we have all the inventory we want for a social/meetup drop-ship we should create a drop-ship campaign in Printfection including:

- Tote bags
- T-shirts
- Socks
- Stickers (3)
- Foldable hedgehog

When an event occurs we can then execute the campaign and send the drop-ship to a postal destination for that small event.

---

## Ideas

Will likely pick two or three of the following for a drop.

- Eco-friendly socks with custom design https://www.printfection.com/swag/conscious-step-crew-socks/
- Custom cut stickers https://www.printfection.com/swag/custom-cut-sticker/
- Moleskin notebook https://www.printfection.com/swag/moleskine-volant-lined-large-journal-5quot-x-825quot/
- Eco-friendly sun glasses (orange?) https://www.printfection.com/swag/wheat-straw-malibu-sunglasses/
- Eco-friendly tote bag https://www.printfection.com/swag/recycled-cotton-convention-tote/ or https://www.printfection.com/swag/econscious-hemp-market-tote/
- Sprout Pencil (not available in Printfection but have requested) https://sproutworld.com/plant-a-green-mindset-with-a-sproutpencil/
- Eco-friendly (apple pulp) notebook https://www.printfection.com/swag/appeel-apple-scented-notebook-525quot-x-838quot/
- Eco-friendly water bottle:
  - 25oz https://www.printfection.com/swag/mira-cascade-bottle-25-oz/
  - Other options available via https://www.printfection.com/swag/category/drinkware/ or we could ask Printfection to stock [Chilly's water bottles](https://www.chillys.com/us/categories/bottles-series-2)
- T-shirt tri-blend: straight cut (listed as men's) and fitted (listed as women's) with brand being one of:
  - Next Level
  - BELLA+CANVAS
  - American Apparel

Other swag options can be found via https://www.printfection.com/swag/

**Comment by lottiecoxon** [comment]
I think that the socks and pencil are probably a more exciting alternative to books or water bottles -

**Comment by lottiecoxon** [comment]
# Updates 
### Tote Bag
Mockup here:
![tote](https://user-images.githubusercontent.com/65415371/140710310-5aceb183-9fa4-457d-9575-d4f28b6ce408.jpg)

This is still in the process of being mocked up/processed by Printfection so this will be ready within the next month. 

### Foldable Hog Origami 
This hasn't finished its initial testing stage yet (aka internal company testing -thanks Joe and Paul who have given feedback). But I have begun to make some changes. I am aware that our hog style could potentially be changing so I am keen not to force this out too quickly if that is so (as the hog will be outdated pretty quickly. 
You can get a sense of the design though from the pages below. 
![Foldable-hog page 1](https://user-images.githubusercontent.com/65415371/140710794-6965d819-6676-4c37-860d-7acdc13ecc1b.jpg)
![foldable-hog page 2](https://user-images.githubusercontent.com/65415371/140710822-1bfd24d9-1b3f-4696-b829-74a4438c3c4e.jpg)
![foldable-hog page 3](https://user-images.githubusercontent.com/65415371/140710830-2e6f3307-8791-4667-8882-67985ce4371b.jpg)
![foldable-hog page 4](https://user-images.githubusercontent.com/65415371/140710838-2c9ea6a6-9593-4f6e-9fe7-2c4603d17455.jpg)
