### ISSUE TITLE
T-shirt design request

### ISSUE THREAD

**Issue by leggetter** [PostHog/meta#32]
For https://github.com/PostHog/meta/issues/31

Suggestion:

- Design on front
- Small PostHog logo on back of neck
- (Optional) logo on arm

**Deadline:** No specific deadline.

cc @lottiecoxon

**Comment by leggetter** [comment]
@lottiecoxon - I don't have an example for this. The example I remember speaking about was for blog post feature images... I think.

**Comment by jamesefhawkins** [comment]
Closing as we have lots of new merch.
