### ISSUE TITLE
Tutorial/blog feature image template

### ISSUE THREAD

**Issue by leggetter** [PostHog/meta#33]
The plan is to create tutorials that show how to analyse user behaviour on various technology stacks. So, it'd be good to have a nice feature image that shows PostHog + Tech Stack. Sometimes there may be more than one Tech Stack. For example:

- PostHog + Supabase
- PostHog + Next.js + Supabase
- PostHog + Nuxt.js + Supabase
- PostHog + Next.js + Stripe

For the developer, the benefit of PostHog is helping them understand if the feature they've shipped is being used as expected. Is it helping their end-user be successful?

From a visual perspective, it'd be great to bring the brand logos together and demonstrate they work really well together.

A super-basic example is the header images used here: https://developer.tru.id/tutorials

These are generated via https://devx-og-image.vercel.app/

**Comment by joethreepwood** [comment]
@lottiecoxon I think we can either close this or reassign to the Web/Docs team? LMK.
