### ISSUE TITLE
Content Calendar & Andy Onboarding

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#37]
Andy is joining soon! It's very exciting. 

We have a task set up already for the People-side of the onboarding. However this issue can help us onboard him into the team and handover the content calendar. 

Really, we should be tackling our content in a more structured and repeatable way - we should have a clearer idea of our cadence, our promotion opportunities and the themes we're covering. The same is true for social media, as became obvious during the previous Marketing Sprint discussion. 

This issue can act as the handover of the content calendar to Andy and start the discussion for how we move forward in 2022.

**Comment by charlescook-ph** [comment]
Useful links:
- [Marketing board generally](https://github.com/orgs/PostHog/projects/8?fullscreen=true)
- [SEO audit report and recommendations](https://github.com/PostHog/company-internal/issues/448) (obv he can implement/ignore as much as he wants)
- [Content calendar](https://docs.google.com/spreadsheets/d/1-6QYxi46d5y88BQ8vdGWmgrFZBbCMs1CAIc5JGLuf4Y/edit#gid=1857648072)
- He should be the main admin for SEMRush - they keep pinging us about toxic backlinks, not sure if these are actually a problem that needs fixing or not (Annika said yes at some point, but it's not exactly urgent)

**Comment by joethreepwood** [comment]
> Hey guys. Could you give me access to the links above? Would be good to have a look at the SEO audit report specifically just to see what had and hasn't been covered in that.

Sent you access to the report and the calendar. The rest is probably fine to leave for now and is on our GitHub private boards.

**Comment by joethreepwood** [comment]
This won't be viewable yet, but we should absolutely go through the [Marketing & Community Epic](https://github.com/PostHog/company-internal/issues/508) when you've joined and plan ideas for the future.
