### ISSUE TITLE
Hogtalk: Mike Cook, AI Researcher

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#38]
I've arranged for a new upcoming Hogtalk, in January, with Dr Michael Cook. Mike will join us for a fireside chat led by me, which then opens to a general Q&A.

**I want to be this the first Hogtalk we open up to the community. Feedback, interview topics and specific questions welcome below!**

## Who is speaking?
Mike is an AI researcher who currently holds a research fellowship at the Royal Academy of Engineering in Queen Mary University. He focuses on the field of computational creative and AI-related design.

Mike is the founder of [the ProcJam Procedural Generation gamejams](https://www.procjam.com/), has written [a book about Twitterbots](https://mitpress.mit.edu/books/twitterbots) and is a member of [Knives and Paintbrushes](https://www.knivesandpaintbrushes.org/). More [info on his website](https://www.possibilityspace.org/).

### Did you say 'computational creativity'?

Yep. That's the field of trying to create software which is capable of human-level creative acts. [The Wikipedia page](https://en.wikipedia.org/wiki/Computational_creativity) is worth a look if you like heady philosophical questions, such as:

- Is it possible for an AI to paint a portrait that we would consider to be a work of art? 
- Is it possible for software to emulate the human process of writing a joke?
- How do we define human creativity? Should computational creativity be analogous? 

There's also a lot of practical work in this space. Mike, for example, has previously created [the ANGELINA AI](https://www.possibilityspace.org), which is an AI capable of designing, making, testing and evaluating simple games.

### What can Mike speak about and not speak about?

I've interviewed Mike before and he's a great person to speak to. He's an expert on AI, game design and computational creativity as broad fields. If you want specific prompts, how about:

- The ethical questions of AI development
- AI in software design and content generation
- The philosophy and definition of art
- Automated software evaluation

There are unlikely to be areas of his work which Mike cannot talk about. 

## When and where is the talk happening?

Time is 6 Jan, 5PM BST.

The talk will take place virtually, over Zoom. We will record the call. 

## Next steps

All the below are actions for @joethreepwood unless otherwise noted. 

- [x] Intro the idea internally, write this issue, discuss on Sprint, etc. 
- [x] Lock in a date with Mike, [get it in the calendar](https://calendly.com/joe-posthog/posthog-hogtalk-jan?month=2022-01) and update this issue
- [x] Write a list of questions and do general interview prep
- [x] Get feedback on topics to focus on
- [x] Invite and promote this to the PostHog community
- [x] Do the talk, record it

**Comment by ZionMRichmond** [comment]
Hello! I really want to be there for the interview, where will the link to the zoom call be when the interview starts?
I'm very interested in Dr. Cook's work, thank you for setting this up.

**Comment by tiina303** [comment]
You can reserve your space [here](https://calendly.com/joe-posthog/posthog-hogtalk-jan?month=2022-01). The link was shared in the announcement in our user slack https://posthogusers.slack.com/archives/CT7HXDEG3/p1638889419278300

**Comment by ZionMRichmond** [comment]
> 

Thank you!

**Comment by joethreepwood** [comment]
Unfortunately, Mike let me know that he's currently too sick (waiting on a positive result) to do this at the agreed date. It looks like we're going to have to delay by 10-14 days until he feels better. I'll plan something out and reschedule soon.

**Comment by joethreepwood** [comment]
Well, I think that went OK.
