### ISSUE TITLE
Ideas for funny hedgehog cartoons

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/meta#47]
Every two weeks, @lottiecoxon is creating an awesome little cartoon to feature in our newsletter, and on social media etc. Here's a recent one. 

![hogmails](https://user-images.githubusercontent.com/92976667/165270156-4a3607de-333a-4bf5-9f80-e28d5429d4a9.jpeg)

We need more ideas for jokes, memes – anything we think our audience will enjoy.

Please share them here.

**Comment by andyvan-ph** [comment]
Throwing this in as an option for next week. A version of this...

![run-as-admin](https://user-images.githubusercontent.com/92976667/165271881-b105b147-578a-41f5-a338-ce196ba1adbe.jpeg)

**Comment by charlescook-ph** [comment]
One additional route (bit easier than writing jokes) could be topical hogs from the latest news in tech? e.g. something around Elon/Twitter

**Comment by andyvan-ph** [comment]
> One additional route (bit easier than writing jokes) could be topical hogs from the latest news in tech? e.g. something around Elon/Twitter

Yeah, definitely a posibility, but trickier given we're doing these every two weeks.

**Comment by mariusandra** [comment]
> Throwing this in as an option for next week. A version of this...
> 
> ![run-as-admin](https://user-images.githubusercontent.com/92976667/165271881-b105b147-578a-41f5-a338-ce196ba1adbe.jpeg)

I get it, as someone who also uses a Windows machine sometimes.

That's not everyone here 🤣

**Comment by andyvan-ph** [comment]
@lottiecoxon So we should probably settle on something so you can get working on this.

I'm thinking, as per the Slack thread, perhaps we should do our own version of the Drake meme?

One idea I just came up with... thoughts?

![Screenshot 2022-04-28 at 11 16 59](https://user-images.githubusercontent.com/92976667/165731387-f02bc6c1-660e-4b23-8f18-6adba6cb30be.png)

**Comment by jamesefhawkins** [comment]
i think going timely will make these not feel tired

**Comment by joethreepwood** [comment]
![6dwagk (1)](https://user-images.githubusercontent.com/84011561/168558211-502b0a72-333d-4e28-a29b-2bbe77fb9f25.jpeg)

![1651071927641 (1)](https://user-images.githubusercontent.com/84011561/168558326-470ba7e4-9b4d-4c84-8c5f-7bd1c1306fca.jpeg)

**Comment by andyvan-ph** [comment]
@lottiecoxon Ok, idea for this week.

It's a riff on the people mis-pronouncing SQL as "es-queue-el".

We could do it a couple of different ways...

1. Two hedgehogs chatting, one reacting angrily / surprised / shocked and the caption reads "It's pronounced "es-queue-el" right?

2. Same basic layout but with speech bubbles, one saying "It's pronounced "es-queue-el" right?" and the other saying "We can't be friends anymore"

I've also thought of a third where's two hedgehods on a date, which might be fun.

As usual, plan is for newsletter to go out around 5pm BST on Wednesday.

**Comment by lottiecoxon** [comment]
I like the second idea with 'we can't be friends anymore'

**Comment by tiina303** [comment]
Maybe a comic around how product analytics isn't evil tracking everyone but actually helps make the products you're using better & it's not about selling your data for advertising. Source of the idea: sometimes when I mention that I work on product analytics people have a negative reaction.

**Comment by lottiecoxon** [comment]
this is a cool idea - could do an expectation vs reality but with product analytics?

**Comment by tiina303** [comment]
could be a cool blogpost too, if we don't already have one potentially

**Comment by joethreepwood** [comment]
May be worth following[ this subreddit ](https://www.reddit.com/r/ProgrammerHumor/comments/us85bb/i_wasnt_taught_about_this_loop/)for inspo.

**Comment by andyvan-ph** [comment]
At Charles' suggestion, we're canning the funny cartoons mainly for time reasons. We're just going to use a new hedgehog avatar in each newsletter. Way easier for both me and Lottie.
