### ISSUE TITLE
[Offsite RFC] Diversity & Tutoring

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#48]
I wasn't actually involved in this specific group at the offsite, but I did get feedback that I can do more to champion diversity given my strong feelings on it and, at the same time, @pauldambra said he could do with a hand. So, that's why I'm meddling!

### What's the objective and why?

One of the ideas discussed at the offsite was doing more to champion diversity ([because we think it's important](https://posthog.com/handbook/company/diversity)) and to attract diverse candidates to PostHog.

One way which we feel we can encourage diversity at PostHog is through coaching and tutoring, inspired by work @pauldambra has done previously and @liyiy has done recently. The goal of this objective would be to identify who, how and where we can continue doing such activities, with a particular focus on engineering opportunities due to the type of company we are and the type of team we have. 

### Where would we focusing?

Diversity in this case can mean anything which makes people unique. Diversity can stem from gender, race and age, etc., but also from medical issues, neurodiversity and background. It's been suggested that two areas we may prioritize because they seem particularly under-represented in our current team are: individuals who identify as female, and individuals in the southern hemisphere. However, we should be mindful to make this initiative inclusive of many different types of diversity and not limit activities to a single axis. 

Because we are planning to approach this initiative from the perspective of coaching and tutoring, we will focus on areas where we have considerable experience. Specifically, tutoring others on Python, Django and Javascript. 

Due to bandwidth, we want to focus on working with existing organizations. This will help us have a more immediate impact and play to our strengths more than, for example, launching a PostHog scholarship or organization of our own.

### Who could we work with?

The following organizations have been suggested previously...

- [Codenation](https://wearecodenation.com/), which @liyiy already supports
- [Lesbians Who Tech](https://lesbianswhotech.org/), suggested by @postgrace 
- [Elpha](https://elpha.com/), suggested by @postgrace 
- [Django Girls](https://djangogirls.org/en/), suggested by me (and who we already support)
- [Women Who Code](https://www.womenwhocode.com/), suggested by me
- [Stemettes](https://stemettes.org/), suggested by @lottiecoxon 
- [Black Girls Code](https://www.blackgirlscode.com/about-us/) - Taken from [a list](https://www.fullstackacademy.com/blog/black-coders-tech-orgs) @tiina303 suggested 
- [All Star Code](https://allstarcode.org/about/) - Taken from [a list](https://www.fullstackacademy.com/blog/black-coders-tech-orgs) @tiina303 suggested 

But there are others, so suggest some more!

### What would be involved?

The way we would collaborate with each organization would change based on a variety of factors. However, volunteers should assume that they'd have to donate some non-trivial amount of time to activities such as mentoring individuals, giving a talk about their personal experiences or attending events in person.

### What's next?

This is just the first step and as such I'm especially interested in hearing feedback on the above, ideas for organizations and - most importantly - who would be interested in volunteering their time. It doesn't have to be just about engineering and engineers! 

Once we've got some input, I'd be happy to help organize acitivities, do some outreach to organizations and raise visibility of the work we're doing to help inspire others.

**Comment by lottiecoxon** [comment]
This sounds great- no feedback comes to mind yet but I would like to express my interest in volunteering (not that I'm always around in the general European area) - I will be in UK over the summer for around 3 months if that helps.

**Comment by tiina303** [comment]
Why not launching a PostHog scholarship? For example it could be a mini version of PostHog vc, we pick a CS student or a few, they get to hack on their project during the summer break from University & use PostHog for their product analytics. This might help with recruiting, marketing, ... and involve more folks not in engineering. 

As an engineer I feel like there's more to do than I have time for already and at the current moment I'm not willing to offer up my personal time. Furthermore I feel like we haven't really established mentoring and coaching within the company and I think we could benefit from doing that first.

**Comment by pauldambra** [comment]
> Why not launching a PostHog scholarship?

That's an awesome idea @tiina303 

> I'm not willing to offer up my personal time.

The first step in this was to [update policy](https://posthog.com/handbook/people/training#time-spent-training-others) so that this is considered work time

> Furthermore I feel like we haven't really established mentoring and coaching within the company and I think we could benefit from doing that first.

Can you expand on why you think that should come first? (Not disagreeing, don't want to assume I understand)

**Comment by liyiy** [comment]
> Why not launching a PostHog scholarship? For example it could be a mini version of PostHog vc, we pick a CS student or a few, they get to hack on their project during the summer break from University & use PostHog for their product analytics.

Isn't this what an internship is? If not, what are the differences?

**Comment by lottiecoxon** [comment]
Scholarships are usually paying for someones education no?

**Comment by tiina303** [comment]
btw I stole the scholarship idea from the original post 

> Due to bandwidth, we want to focus on working with existing organizations. This will help us have a more immediate impact and play to our strengths more than, for example, launching a PostHog scholarship or organization of our own.

---
> Can you expand on why you think that should come first? (Not disagreeing, don't want to assume I understand)

From what I'm seeing mentoring/coaching internally isn't currently happening much - partially due to everyone having too much on their plates, partially due to it not being encouraged/prioritized, partially due to lone wolfing, ...

If we now encourage and push everyone to mentor externally it's even less likely to happen as we'll have even less time available. I don't want us to end up in a place where PostHog is known for great coaching externally, but internally we don't have any/much.

Specifically here I want to be very cautious of more senior members time that I would love to keep to help more junior folks at PostHog to have coaching/mentoring. Why more senior you ask? While it's true that anyone can learn from anyone, I have personally benefited more from coaches/mentors who are more senior than me. Also selfishly I'd like a coach/mentor. Would be lovely if everyone who wants can have a mentor and a mentee - prioritizing internal folks first before doing external mentoring. At my previous larger companies there was a place to sign up to do either/both and then a matching system (usually a human) to pair people up. Rotating was also encouraged, so e.g. you work with someone for 3-6 months and then can choose to continue or switch.

---
> Isn't this what an internship is? If not, what are the differences?

No, my idea was: they come to us with a project, we'll provide a scholarship/money so they can eat while hacking on their amazing product. vs an internship is something where you go to work at the company on their project and get mentoring etc.

> Scholarships are usually paying for someones education no?

There are different kinds of scholarships afaik, not sure on the exact rules.

**Comment by joethreepwood** [comment]
> btw I stole the scholarship idea from the original post

Ha, where I originally dismissed it!

Personally, I worry that a scholarship would be a very high-expense way of doing this with only a limited impact. But I mainly dismissed it because I'm piggybacking on someone else's topic from the hackathon and it'd be rude to derail it on the first step!

> Isn't this what an internship is? If not, what are the differences?

As Lottie says. My understanding is:

Scholarship: We give you £X to fund your education. 
Internship: You come and work with us to learn on the job. Maybe we pay. 
Mentorship: We meet you to help you grow your skills more directly.

What I think @tiina303 is suggesting in terms of payments during a project would be  _patronage_. Which I think would be _much_ easier to scale than a scholarship for a few individuals. We could make a certain amount of money available to projects led by/for diverse audiences and then invite applications. We could _potentially_ even view that as a feeder program for Hedgehog.vc @charlescook-ph ?

> Specifically here I want to be very cautious of more senior members time that I would love to keep to help more junior folks at PostHog to have coaching/mentoring.

To me this is a great, but separate idea and they don't have to be mutually exclusive. We could, for example, match internal mentees with external mentors so that they still have mentors but our internal mentors can pursue external mentees. I mention this because my experience of being mentored is that it's been best with someone external anyway.

**Comment by postgrace** [comment]
Two more angles that can be pursued either separately or in conjunction with volunteering: 

1. sponsoring and/or sending representatives to career fairs or summits held by these organizations (Lesbians Who Tech does a Pride summit each year, and the career fair was super popular among attendees -- not sure if they are back in person yet, as they've been online since the beginning of the pandemic). 
2. posting open roles on these organizations' job boards, and in the case of platforms like Elpha, actively engaging with their membership by posting on their forum and hosting things like AMAs.

**Comment by tiina303** [comment]
>  match internal mentees with external mentors

Why not both :) Just to call out one of the pro's for internal mentors: there's a lot more context the internal person would have and that can be helpful especially for engineers.

**Comment by joethreepwood** [comment]
So, I love all the ideas, but I'm personally keen to focus this initiative on an idea we can definitely move forward with as a first step and feel it would be unrealistic to do _all_ of the above. Some of the things discussed above, like mentoring existing staff, are great ideas which probably need to be discussed separately from this diversity initiative. 

I'm also aware that nobody, either above or in the original thread, has volunteered explicitly yet (except for Lottie). 

What I'd suggest is that we choose one or two organizations above and investigate from there how we can engage with them more deeply across a variety of activities, such as hosting workshops, speaking at events, providing materials, etc. I'd be happy to reach out to a few organizations and report back with the specific things that they would want us to do. 

Personally, I think Django Girls, Lesbians Who Tech and Codenation seem like the best fit because they cover wide geographies and we have an existing connection with each of them. 

Happy to take feedback on this!

**Comment by charlescook-ph** [comment]
> Personally, I think Django Girls, Lesbians Who Tech and Codenation seem like the best fit because they cover wide geographies and we have an existing connection with each of them.

Agree - support you just going ahead and taking action here, otherwise we're risking getting bogged down in a super wide ranging conversation 👍

**Comment by pauldambra** [comment]
I can volunteer time...

**Comment by postgrace** [comment]
I'm happy to take on exploring engagement opportunities with Lesbians Who Tech -- I'll post what I find here with recommendations for how to move forward with them.

**Comment by clarkus** [comment]
I can make time to talk to folks about product design if that comes up as a need. I already do 1:1 mentoring for product designers by request, so this would be easy to fold into my current scope of work. Let me know if I can support! 👍

**Comment by postgrace** [comment]
Update: The [Lesbians Who Tech summit](https://lesbianswhotech.org/sanfrancisco2022/) is being hosted in person in San Francisco again, as well as virtually.

I've submitted a request for sponsorship information, and plan to register for the conference before early bird pricing ends this Friday. I'm also thinking of applying to be a speaker, with the angle of evangelizing the benefits of an open-source culture from an operations perspective. I'd love some feedback/brainstorming on that if anyone has ideas.

**Comment by postgrace** [comment]
Managed to find some [sponsorship information](https://drive.google.com/file/d/17Y9eXnjCY2EXwefYhT9wlQs_-LIO6dC4/view) -- I'll do a deep dive with @charlescook-ph next week once he's back

**Comment by joethreepwood** [comment]
Awesome - I've reached out to Codenation and Django Girls, but no response yet.

What sort of ideas are you looking for, Grace? I think the open-source culture is a good focus point. 

We could explain how we encourage people to adapt open-source practices into how they work with others -- for example, encouraging the use of READMEs for individuals so that others can clearly communicate their needs. My readme, for example, explains a few things that I'm uncomfortable with and I've really appreciated that PostHog is one of the first places where I can communicate that to others and they listen to it. We could also talk about how our remote focus and communication norms enable people to be their most authentic selves at work, share passions and life stories, etc. 

Probably worth not being too self-congratulatory too - especially if we want to be transparent. We could offer up information on how we want to become more diverse and talk about some of the things we struggle with. 

Just my starting thoughts though, happy to collaborate further if helpful!

**Comment by postgrace** [comment]
@joethreepwood that's a really great jumping-off point for me to have a deeper think, thanks for brainstorming a bit.

After some discussion and reviewing sponsorship options, we think that sending Coua and me to the LWT SF summit as a "walking booth" of sorts makes the most sense for this year -- the minimum sponsorship tier is $10k+ and you don't even get a virtual booth for that amount.

**Comment by joethreepwood** [comment]
Just to keep everyone updated: I am now in touch with both DjangoGirls and Codenation, will be meeting with them next week. They've been a bit slow to respond.

**Comment by joethreepwood** [comment]
So, I caught up with DjangoGirls. There are three things they were interested in.

1. Getting a free license to run on their site.
2. Having PostHog staff contribute to their docs and online tutorial to improve it. 
3. PostHog running an event. 

### 1 - Free licesnes
From a marketing perspective, providing free licenses for their site (and potentially adding it as part of their tutorial process) feels like the easiest win. However, it doesn't really solve much of the diversity intent here. Still, tagging @charlescook-ph to continue discussion there. 

### 2 - Improving their docs & site
[Their docs are open source and online.](https://tutorial.djangogirls.org/en/) They believe there's a lot of room to update these. They'd love to have an engineer from PostHog look through it and make updates. 

Maybe we could bundle this with Step 1. and give those who complete the tutorial a link to a tutorial in our docs about installing open-source PostHog on the blog which they create in the tutorial? This would need a volunteer with engineering experience (tagging @tiina303 and @pauldambra as you've been vocal here), though I'm happy to support if I can. 

Their actual site is also open source. Contributions from the website/docs team (tagging @corywatilo @lottiecoxon @smallbrownbike) would be appreciated too. 

### 3 - Running an event
We could run a DjangoGirls workshop online, or physically. I feel a physical workshop is best, but it isn't something we could bundle with an offsite unless we were willing to add an extra 48 hours to the agenda. 

A workshop would be a big commitment. 

DjangoGirl workshops are structured events where participants run through the tutorial linked above, with an 'installation party' the day before (which can be online). It takes a full day. They have a full step-by-step guide, but the short version is that it takes around three months to plan, costs around £2k for typical logistics and requires one engineering coach for every three attendees. DjangoGirls has guidelines for promotion, but we'd _mostly_ be on our own there. 

I'm happy to do some of the heavy lifting on organizing a workshop, however based on the experience of HostHog I anticipate it would be a _lot_ of work and attendance may be minimal. Again, volunteers from engineering are needed. 

After looking into this now, I think 1. and 2. are the best opportunity for moving ahead right now. But I'm open to thoughts.

**Comment by tiina303** [comment]
> tagging @tiina303 

For the reasons I outlined earlier I am _not_ signing up to help with the docs, perhaps this could fit better for the dev advocate or growth engineer work.

**Comment by joethreepwood** [comment]
I (finally) got chance to speak with Codenation. I'm aware of the lack of engagement for the DjangoGirls idea above, so I think/hope this plan could work better. 

**In short:** Codenation teaches high-school kids in the US how to code. They focus on a few geographical areas, particularly New York and San Fran. 

We would do a _virtual field trip_ as a first step. This would be a 1 hour, online session about a set topic, with Q&A. Topics are catered to classes, but can include anything. Ideas we discussed:

- Product design, UX and how creative roles work with technical roles
- Live coding session to build something, intro to open source, technical topics 
- Career paths into technical roles and tech start-ups, our open source culture

We don't need to define the topic now, as classes are on summer break. You do **not** need to be an engineer to be involved. I just need to know who would be interested so I can go back to Codenation and let them know the topics we _could_ cover with those people. 

⚠️ **ACTION REQUIRED** ⚠️ 
If you're interested in participating with this, react with a 👍 on this post so I can plan next steps.
