### ISSUE TITLE
Hedge house retro

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/meta#49]
Context

I'd like to make the house iteratively nicer each time.

Currently planned:

* Garden will be sorted
* There's more artwork appearing
* Somewhere to hang clothes / towels in each room

What went well:

* I sorted out a decent cleaner, so it's easy to make it clean
* I think having towels, pillows etc made it feel nicer.
* Had furniture mostly made in advance this time
* Internet seemed pretty decent
* Sorted a combo lock so it's easy for people to let themselves in

What didn't go well:

* Didn't get time to put a sofa in the kitchen. I have got a sofa ready, need to organise transporting it.
* Didn't have second bed made in one of the bedrooms. This would have meant we'd have had the living room spare for meetings when there are lots of us here
* Slightly annoying only being able to make ie 2 coffees at a time. I _could_ enhance the coffee facilities... but I'm super biased in favour of this as it's why I wake up each morning. If several people want this, it justifies it IMHO
* I was slightly confused about numbers, so I'll sort a permissionless calendar out in future
* Forgot earl grey tea

Open qs:

* Better coffee facilities?
* Do people live out of suitcases or do they prefer chests of drawers to put clothes in?

**Comment by benjackwhite** [comment]
From a new-joiner perspective it was great. 
* Better coffee facilities - **Would be great but then again pressure to go out and get a nice local coffee was actually good for me.**
* Living out of suitcases - **Totally fine for me. Preferred even.**

**Comment by jamesefhawkins** [comment]
done:

- updated docs around laptop stands / mice / keyboards (suggesting people just bring their own as they're quite expensive and not huge objects). If this frustrates people next time I'll buy some!

todo:

- [ ] buy some wall hooks!
