### ISSUE TITLE
Marketing Experiment - 13 July - Self Hosted vs Open Source

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#5]
# Experiment

## Context
For the second marketing experiment, running a basic a/b test on Reddit Ads to see which performs best.

In the red corner we have the sauciest message in the northern hemisphere..."PostHog is Open Sourcccceeee!!"
And in the blue corner is a contender that needs no introduction (but will get one anyway)..."PostHog can be self-hosteddd!"

Which message will win out when focused on identical Reddit targeting? Tune in two weeks from today to discover who wins this heavyweight high-level messaging test!

We have a number of USPs that set us apart. Two of the biggest are self-hosting and open source. This experiment tests those messages using otherwise identical imagery and targeting. The test uses Reddit Ads, targeting users rather than search keywords.

#### Goal
We are trying to see which of these two messages has the most impact with a developer audience. Open source or self-hosting. 

#### Hypothesis
One of these messages should have greater impact than the other. My suspicion is that it will be self-hosting, as this originates from a user need. However, open source also evokes strong opinions and there's only one way to be sure. 
Update: At Kunal's suggestion, have added a third option merging both ideas.

#### Campaign details
![RedditAds_Open_Big](https://user-images.githubusercontent.com/84011561/125467966-e43eee62-4a18-44c8-93da-5122d4ed6061.png)
![RedditAds_Self_Big](https://user-images.githubusercontent.com/84011561/125467982-1fe03239-899d-48b4-b1b7-d66795b05f89.png)
Title: Analytics, session recordings, feature flags, heatmaps and more. All in a single product you can host yourself. vs Analytics, session recordings, feature flags, heatmaps and more. All in a single, open source product.
CTA: Learn more
Channel: Reddit Ads.
Destination: Posthog.com (no bespoke landing page)
Bidding: $5 per click (may increase as needed)

#### Audience
Devices: Desktop
Locations: Worldwide
Placements: In feed only
Interests: Programming, Computing, Programming, Business
Communities: productmanagement, prodmgmt, opensource, coding, programming, dataisbeautiful, analytics, dataanalytics, postgresql, aws

#### Resources and timeline
Like other ads in this series of experiments, the ads will run for two weeks with a £1000 budget each. 

### Tracking
UTM parameters:
```
CampaignID = open-vs-selfhost
CampaignSource = redditads
CampaignMedium = cpc
CampaignTerm 1 = openandself
CampaignTerm 2 = opensource
CampaignTerm 3 = selfhost
```
Additional ad tracking through Reddit Ads. Will export a report at end of experiment. 

### Primary
CTR
##### Why 
CTR tracks which message in the ad resonates best with the audience. 
##### Pre-experiment baseline:
No baseline as these ads haven't run before. Once we have more ads running in this channel we can aim to formulate an average. 
### Secondary
We can potentially go further and look at conversion rate for each group, but we can only optimise conversion for each group once we know which group performs best. 

## Results
To be filled out later. 
_What are the top learnings from this experiment?
What impact was there on the primary metric or any secondary metrics?
What are the next steps based on the learnings of this experiment?_

**Comment by joethreepwood** [comment]
@kpthatsme Used the new template you provided. Thanks! Feedback is that it felt a little repetitive to fill out in a few places, but that may also be down to this being a simple test.

**Comment by kpthatsme** [comment]
@joethreepwood – it looks like the "Tracking" section of the template was removed? Could we please get that section added back in with information on how we're tracking clicks?

Also – one idea: thoughts on running a third variant with both open source _and_ self-hosted included? I feel like we should be able to combine both of those concepts into a single ad and I would love to see how that performs versus the individual inclusions.

**Comment by joethreepwood** [comment]
> @joethreepwood – it looks like the "Tracking" section of the template was removed? Could we please get that section added back in with information on how we're tracking clicks?

Added back in. I removed it because the answers were feeling a little repetitive (we're tracking CTR through Reddit Ads' platform directly) and wanted to cut it shorter. Let me know if there's extra info you need?

> Also – one idea: thoughts on running a third variant with both open source _and_ self-hosted included? I feel like we should be able to combine both of those concepts into a single ad and I would love to see how that performs versus the individual inclusions. Something like **Open source** product analytics that you can **host in your own infrastructure**.

This is a good idea and one I should have thought of. Will tweak the budgets and spin up a variant today, add to this thread.

**Comment by joethreepwood** [comment]
![RedditAds_Variant3](https://user-images.githubusercontent.com/84011561/125602654-11b6c778-6885-4aa0-875e-e31d792449dd.png)

New ad. Dropped budgets for each variant to $550, accounting for 20% overspend to equal original overall budget.

**Comment by kpthatsme** [comment]
> Added back in. I removed it because the answers were feeling a little repetitive (we're tracking CTR through Reddit Ads' platform directly) and wanted to cut it shorter. Let me know if there's extra info you need?

Thanks! think we're still missing information. re: repetition - the prompt for the this section was: "How are we tracking results of this experiment? Include any UTM parameters or other relevant details." – I don't think that's actually covered elsewhere in the spec?

This section is meant to capture specifically, how are we tracking traffic to this specific campaign. If we wanted to look at pageviews in PostHog that originate from this campaign, how can we find that?

Typically, for each campaign we run, I'd expect us to be setting some UTM terms on the links and capturing those terms in these specs.

**Comment by joethreepwood** [comment]
Ah, understood. With this campaign I checked against Charles' campaign before the template was created and didn't set up any third party tracking or UTMs. We can add this in still if needed, but intent was to export a report directly from Reddit Ads once the campaign had finished.

**Comment by joethreepwood** [comment]
Wouldn't be a blocker, but related question: do we have any standards around UTMs currently?

**Comment by kpthatsme** [comment]
No, we don't have any standards (yet!) – I think Charles missed them by mistake.

We should definitely get some created as part of the work this week so we can tie this back into product data.

As a suggestion, what do you think about these? 
```
utm_source=reddit
utm_medium=cpc
utm_campaign=open-vs-selfhost
utm_term= either opensource, selfhost, openandhost - based on the specific AD
```
I'm not great at naming so feel free to suggest others :) I think the most important things here are the source and medium. Those will let us measure $$. The others are important to help us measure longer-term impact of specific campaigns and variants.

**Comment by joethreepwood** [comment]
Thanks Kunal -- I've set some UTM parameters and added above.

**Comment by joethreepwood** [comment]
And the results are in! 

**Summary Results:** The three campaigns reached a total 194,446 impressions, with 128 clicks at an average $2.40 CPC. The average CTR was 0.066% and the amount spent of a $2000 max budget was $307.85. 

**Results:** The results are a little skewed because one option (the combined message) went live a few days later. The difference in performance for all three was only slight. OS option had the highest number of impressions, the highest number of clicks _and_ the lowest CPC, however.

Full performance report: 
[t2_d9a2w6mg___2021-07-19_2021-07-25 (1).csv](https://github.com/PostHog/meta/files/6877057/t2_d9a2w6mg___2021-07-19_2021-07-25.1.csv)

**Learnings:**
- There isn't much difference between self-host and open source options. The best approach is probably to combine the messages going forward, though if a choice is forced then open-source seems to get more attention initially. 
- We can afford to bid _very_ aggressively. Each campaign was set at a max bid of $5 per click, but achieved approximately half of this. In two weeks, none of the campaigns hit their budget limits. Setting a higher big limit will likely create more, faster results. 
- Targeting developers and data analysts on Reddit is hard. For this campaign I selected the following broad categories: _Business, Computing, Programming_. And the following specific communities: _Coding, Analytics, ProductManagement, Programming, AWS, Opensource, Dataanalytics, ProdMgmt, PostgreSQL, DataIsBeautiful_ and was only able to reach a 7.6-9.5m audience size. 

**Recommendations**
If we're going to continue experimenting on Reddit, it would be worth compiling a bulk community list of subreddits which we believe would be worthwhile to target.

**Comment by piemets** [comment]
> * We can afford to bid _very_ aggressively.

I found this as well - I think for the next experiment I'll try doubling to $10. I think it's worth running the same experiment again maybe, as $307 is probably too low to learn from definitively?

> If we're going to continue experimenting on Reddit, it would be worth compiling a bulk community list of subreddits which we believe would be worthwhile to target.

Yeah, we'll need to keep adding to this list, this is a good start though!

**Comment by joethreepwood** [comment]
@piemets @kpthatsme 

Went ahead and used a few community research tools I've tried before to throw together [a list of 70+ subreddits which we can use for the next Reddit test](https://docs.google.com/spreadsheets/d/1KA_2CEEYhXISx31taA7PH2PUMT8ZoljyAyG9ei7Rpxw/edit?usp=sharing). Looked into it and we can just bulk upload Column A from here when creating ads. There's arguably a lot more subreddits we can add, but beyond these the tools I've used suggest either we'll hit dilution or diminishing returns.

**Comment by kpthatsme** [comment]
Great summary @joethreepwood! I think I agree with your takeaway, assuming all else relatively the same it's probably best to float the version w/ both phrases. 

One question re: the Ad copy, we aren't really highlighting "open source" and "self-host" as keywords in the joint ad. Only the "host in your own infrastructure" part really jumps out at me. Could be worth a treatment where all key words are highlighter a special color?

In general I'm eager to see how these experiments net out with some more money and compare against other channels – specifically those CTRs. I think Reddit can provide some niche communities but I feel most are not the type to 1) browse without an adblocker 2) interact with an ad whilst using reddit

**Comment by joethreepwood** [comment]
Yeah, highlighting the copy with different colours or something was something I considered, but as we weren't doing that with the other ads I felt we'd end up biasing the results in the other direction. 

My understanding is that Marketing will be leading further experiments for now. @piemets do you have plans for what sort of experiments are coming up next? It could be interesting in the coming weeks to start thinking about a landing page strategy based on results.

**Comment by piemets** [comment]
> Went ahead and used a few community research tools I've tried before to throw together [a list of 70+ subreddits which we can use for the next Reddit test](https://docs.google.com/spreadsheets/d/1KA_2CEEYhXISx31taA7PH2PUMT8ZoljyAyG9ei7Rpxw/edit?usp=sharing). Looked into it and we can just bulk upload Column A from here when creating ads. There's arguably a lot more subreddits we can add, but beyond these the tools I've used suggest either we'll hit dilution or diminishing returns.

Thanks! I've added a link to the Paid Ads page in the Handbook (and also updated the page generally a bit)

> My understanding is that Marketing will be leading further experiments for now. @piemets do you have plans for what sort of experiments are coming up next? It could be interesting in the coming weeks to start thinking about a landing page strategy based on results.

Yep that's right - cadence is that we launch an experiment every Tuesday, and then report back on the previous experiment every Thursday. I'll tag you both in the next issue I create - I want to do a Twitter ad this week as we haven't done one yet.
