### ISSUE TITLE
track b2c discount enquiries automatically

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/meta#61]
we currently have a spreadsheet that is haphazard - a quick look through email enquiries shows they aren't all tracked properly

suggest we automatically insert into the spreadsheet from the form so we don't lose any data here

**Comment by simfish85** [comment]
All forms are tracked through HubSpot [automatically](https://app.hubspot.com/forms/6958578/ee6b0bef-e2d6-45f7-b946-ab7ae54cc2e4/submissions) - are we missing ones from here?

**Comment by camerondeleone** [comment]
Maybe easier to view it in HubSpot as a list — can do that [here](https://app.hubspot.com/contacts/6958578/objects/0-1/views/9521633/list).
