### ISSUE TITLE
Feedback, trends and opportunities from industry report

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#67]
Quantable is an independent analytics consultancy which put out a 160 page report examining alternatives to Google Analytics. I wanted to go through and summarize a few key points which jumped out. I've loosely grouped these into three sections which should be most immediately useful -- [but the whole report is worth a read](https://quantable.gumroad.com/). I've proposed a simple action and CCed relevant people or suggested owners for each. 

### Trend: GA4 market disruption
GA product changes and legal rulings are causing disruption. There's been a -6% annual trend in the number of GA deployments on the top 1M sites. Competitor trends in this time: Amplitude (+6%), Heap (+51%) and Fathom (+37%). In decline: Mixpanel (-11%) and Matomo (-51%).

**Action:** Prioritize competitive comparisons with the fastest growing competitors, especially Heap. Owners: @joethreepwood, @andyvan-ph 

### Opportunity: CMS integrations
50% of Snowplow's install base run the Weebly CMS, which integrates with Snowplow natively. Integrating with CMS' is a scalable way for non-technical users to be introduced to PostHog. 

**Action:** Create non-technical tutorials to integrate PostHog with Wordpress, consider integration apps. CC @ivanagas and @pjhul 

### Opportunity: Template library
Many tools (e.g. Amplitude) force users to start from a blank slate. Often, teams need different sorts of reports. PostHog provides some default reports, which is great - but we could do more. 

**Action:** Propose additional templates for different user personas which can be integrated to the product. Owners: @joethreepwood, @andyvan-ph  

### Opportunity: Marketing campaign
It was noted that several of the competitors do not dogfood their own product and instead use Google Analytics on their own websites (likely for ad-related reasons). PostHog is unique in this respect, creating an opportunity to, um, pick a fight with some combative ads or other marketing activities. 

**Action:** Consider a marketing campaign or ad set which clarifies that even Amplitude doesn't just use Amplitude to track their users. Owner: @charlescook-ph via Hey Digital, @andyvan-ph

### Opportunity: Competitor comparisons
Some tools were judged to be especially close or comparable to PostHog. Heap was the biggest example of this, where it was suggested a comparison would be especially useful. Framing of the report also suggested that users struggle to differentiate between tools without hands-on opportunities. 

**Action:** Prioritize competitive comparisons with Heap, create a hub for comparison content aids differentiation. Owners: @joethreepwood, @andyvan-ph  

### Feedback: Pricing considerations
We believe we offer best fit for B2B businesses. However, the report argues this is less clear. B2C sites may have high traffic but low user engagement, in which case PostHog becomes an attractive option due to event-based pricing. B2B is more likely to have low traffic, but high engagement. 

**Action:** No suggested action. 

### Feedback: Free trials 
Some competitors offer 14-day free trials, [something we're currently considering](https://github.com/PostHog/company-internal/issues/876). The report judged 14 days to _definitely_ not be long enough to assess analytics tools. 

**Action:** If we proceed with a trial mode, it needs to be at least 4 weeks long. CC @kappa90, @raquelmsmith 

### Opportunity: Favourable consultantcy
The report is largely very favourable of PostHog. The author is indepdendant and is able to offer deep comparisons compared to our competitors. There's an opportunity to either point to the report as a resource for interested users, or to collaborate with Quantable further if users continue to request unbiased comparisons. 

**Action:** No specific action, but FYI @camerondeleone and @simfish85 that I've been in dialog with the author.

**Comment by andyvan-ph** [comment]
Great job @joethreepwood.  

Additional point from me...

## Feedback: Negativity around IsGAillegal.com

The author felt the [isgoogleanalyticsillegal.com](https://isgoogleanalyticsillegal.com) was fear mongering, particularly noting the the scrolling red sidebar for criticism. This almost lead them to ignore us entirely until they investigated the product further.

**Action:** Keep the website (it's still valuable) but remove the scrolling sidebar and replace the red all caps "ILLEGAL" with lowercase lettering. Owner: @corywatilo / @smallbrownbike

**Comment by joethreepwood** [comment]
I don't think we need to be too reactive to an individual POV personally, but will defer to Cory and Eli on that.

**Comment by andyvan-ph** [comment]
I think they're valid criticisms and the fix straightforward enough, but agree it's not high priority.

**Comment by joethreepwood** [comment]
PRs > Comments, so: https://github.com/PostHog/isgoogleanalyticsillegal.com/pull/50

**Comment by charlescook-ph** [comment]
> Action: Consider a marketing campaign or ad set which clarifies that even Amplitude doesn't just use Amplitude to track their users. Owner: @charlescook-ph via Hey Digital, @andyvan-ph

I don't think we should do this - not because it's combative, but because ads should be genuinely useful to the user and communicate PostHog's value, rather than attack the internal policies of competitors. Still agree it's fun to include in comparisons though.

**Comment by charlescook-ph** [comment]
> The author is _indepdendant_

@joethreepwood what happened here 😆

**Comment by simfish85** [comment]
There's already a request for [Wordpress integration here](https://github.com/PostHog/posthog/issues/11882)
