### ISSUE TITLE
Email campaign: Announce new versions to self-hosted users

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#72]
### Context
While planning some improving some improvements to the way we do announcements, I created [this insight](https://app.posthog.com/insights/dinq2CN0) which shows approximately 1/3rd of users who log in on a self-hosted instance are doing it from an old version of PostHog. 

Many of these are only 1-2 versions behind, but approximately 1/5th of users who log in are running version 1.38.0 or earlier. That means those users are missing out on important features such as persons-on-events, chart types, UI improvements and session recording features.

Anecdotally, I've spoken to at least one user who has become a paying customer of LogRocket because they did not know we offered session recording console logs in our latest versions. 

Currently we do not have a way to inform all users about upgrades. Array hits many users, but not all. 

### Why is this a problem?
Firstly, we want users to have a good time and enjoy the best possible experience with the latest possible version. If users have better times with a good-er product, we can assume that'll create positive word of mouth (or at least prevent bad WOM). 

Secondly, we want users to be aware of several of the features which may help them convert to more paying users, especially around session recording.

### What's the solution?
Using the insight above, create a cohort of users who have logged in over the last X days and are on an old version. Say; last 180 days, version 1.39.0 to 1.31.0. 

Hit this cohort with a targeted email campaign which encourages them to upgrade and links them to relevant documentation, while also highlighting the best of the new features they'll get. 

Separately create a second campaign targeted to users on 1.30.0 or older and offer similar messaging which is more catered to the significant jump they'll make and any PostgreSQL / ClickHouse impacts. 

### OK...

I'll use this issue to centralize copy for feedback and track any noiticeable improvement in updates. 

Potentially, depending on results and some nuances about Customer.io adoption, we could make this a repeating activity. Say, once a quarter.

**Comment by tiina303** [comment]
Not sure we should do this given https://github.com/PostHog/product-internal/pull/373

**Comment by joethreepwood** [comment]
> Not sure we should do this given [PostHog/product-internal#373](https://github.com/PostHog/product-internal/pull/373)

I think this becomes a stronger reason to do it, for two reasons. 

1. We can use these emails (and the associated hassle of upgrading) as a way to encourage SH users on to Cloud, supporting the de-emphasis on self-hosting. 
2. Abandoning users on SH will only create more hassle. Getting them on to newer, more robust versions will assumedly mean we have to support these users less. 

De-emphasizing SH for new users and reducing support for them makes sense, and I don't think this runs too counter to that.

**Comment by joethreepwood** [comment]
[I've drafted up some copy](https://docs.google.com/document/d/1knNv2NMg0RWzjiUC1Mj6AY44QoGmpCXcX953bmTjqTk/edit?usp=sharing) and will bunch these users into three roughly-equal tiers. 

1.30.0 to 1.36.0 
1.36.1 to 1.38.0 
1.38.1 to 1.41.0 

Each group gets copy with features tailored to them, so we don't end up boasting about World Map to users who already have that. 

Specifically, I'm targeting these emails to users who have logged in in the last 180 days, broken down by their version.

**Comment by joethreepwood** [comment]
<img width="619" alt="Screenshot 2022-12-01 at 15 09 48" src="https://user-images.githubusercontent.com/84011561/205088213-cb8e4d7a-584a-434e-bcdf-641be8362793.png">

Tweaked copy, laid it out in Mailchimp. 

I'm currently blocked on exporting a list of customers due to [a quirk in cohorts](https://posthog.slack.com/archives/C02E3BKC78F/p1669902777223119), but Neil is kindly offering some solutions.

**Comment by joethreepwood** [comment]
Cohorts created, audiences imported. I'll try and get this sorted tomorrow, so we can send on Monday.

**Comment by joethreepwood** [comment]
Example of the final email, scheduling for Tuesday morning. https://mailchi.mp/7a730befbfc4/upgrade-to-1420-today-to-unlock-new-features

**Comment by joethreepwood** [comment]
Right, all sent. 

There's a consistent open rate of 27-29% so far, with a CTR of 1%. That's a decent conversion compared to other, non-newsletter emails, so I'll close this out for now and report back on more detailed results in due time.
