### ISSUE TITLE
Design request: Popup invitation for a user interview with the PostHog team

### ISSUE THREAD

**Issue by lharries** [PostHog/meta#78]
Instead of sending emails to users to invite them to a user interview I'm planning to create an in-app popup

@lottiecoxon - I'd love your input on the UI/UX of the popup. Ideally the popup should spark joy instead of causing annoyance.

In return for doing the user interview they get a $30-$50 voucher towards PostHog merch. One idea for the hedgehog could be them being overloaded with PostHog stash e.g. PostHog hat, PostHog, socks, mug etc. Equally, if you have lots of other stuff on we could re-use another PostHog e.g. the one with the sign

I'm aiming to get this live by the end of next week, but I could go live without a nice design to start with

**Comment by lottiecoxon** [comment]
I can start this tomorrow and have it done by latest tuesday does that work?

**Comment by lharries** [comment]
That'd be great!

**Comment by lharries** [comment]
Some extra info - it's possible to embed the calendly link on the page: 
<img width="843" alt="Screenshot Select a Date   Time - Calendly (Google Chrome) 2022-12-04 at 20 40@2x" src="https://user-images.githubusercontent.com/22766134/205514388-a203003b-c3ce-49e8-8ee4-2e0ee54d1494.png">

And I'm thinking we might want to start with something small and non-intrusive that's easy to dismiss, then show the full popup if they click yes

**Comment by corywatilo** [comment]
Can we just use the in-app messaging dialog we have? I personally get annoyed with these types of popups, so if we're going to solicit them at all, it would be nice to keep them subtle and not intrusive. A simple text-based version seems like a good balance between prompting and not at all.

**Comment by lharries** [comment]
@corywatilo could you send a screenshot of the in-app messaging dialog so I know what you're referring to?

**Comment by lottiecoxon** [comment]
I will prioritise artwork on this project for now (hedgehog with stash - as if we **can** re-use a pop up/notification template that would be quicker

**Comment by lottiecoxon** [comment]
just to clarify do I need to make artwork for this still if it's a small pop up?

**Comment by lottiecoxon** [comment]
this is great !
