### ISSUE TITLE
Marketing Experiment: 20th July - keyword variants on Google Ads

### ISSUE THREAD

**Issue by piemets** [PostHog/meta#8]
# Experiment

## Context
We want to try out a couple of Google Ads as we've not been active on there at all since Feb 2020, ie. during YC. Currently there is a single Ad running for the keyword 'posthog' and a handful of variants:

<img width="461" alt="Screenshot 2021-07-20 at 15 26 20" src="https://user-images.githubusercontent.com/70321811/126341460-4af6ef28-bb7c-4a69-a38f-29516190a932.png">

#### Goal
To figure out if we should be bidding on alternate keywords for relevant terms. 

#### Hypothesis
Our hypothesis is that there may be certain additional keywords worth buying on Google Ads:
- 'open source analytics'
- 'self host analytics'

#### Campaign details

Given we already have an advert running, I won't create additional ads (in future we should though, Google recommends 3 ads per ad group in a campaign). Instead I will take some quick actions to optimise the existing ad by:
- Ensuring the copy and links are up to date
- Add the two additional keywords

#### Audience
Google Ads - the current campaign is targeting USA, UK, New Zealand, Australia and Canada. I won't change this. Otherwise the ad will target people who enter the above keywords. 

#### Resources and timeline
2 weeks, $2,000 total spend. 

### Tracking
UTM parameters:
```
CampaignID = posthogbrand
CampaignSource = googleads
CampaignMedium = cpc
CampaignTerm 1 = posthog
CampaignTerm 2 = opensourceanalytics
CampaignTerm 3 = selfhostanalytics
```
Additional ad tracking through Google Ads. Will export a report at end of experiment. 
### Primary
Average CPC
##### Pre-experiment baseline:
$3.35
##### Why 
It will help us understand how expensive this might be as a route. 
### Secondary
CTR - currently 6.58%. I'd expect this to go down, given the campaign currently only has the keyword 'posthog'.

**Comment by kpthatsme** [comment]
Hey @piemets are you familiar with UTM parameters? Generally that's what we want to cover in the tracking section. 

There's a little bit of a discussion around them here in this experiment https://github.com/PostHog/meta/issues/5 if you scroll towards the bottom of the issue. 

These parameters are important because they help us differentiate users that came to PostHog via an ad campaign versus other sources. This is going to be critical when we want to go deeper in understanding how ad traffic converts to usage versus organic traffic and measuring profitability of our various channels.

**Comment by piemets** [comment]
> Hey @piemets are you familiar with UTM parameters? Generally that's what we want to cover in the tracking section.

Yeah, but I couldn't figure out how to assign them in Google Ads! But @shehuphd has helped me out (thanks Mo!)

**Comment by piemets** [comment]
## Results

_What are the top learnings from this experiment?_

Half of the experiment was successful, half not:
- Updating the ad copy and structure itself was really successful
- Experimenting with new keywords was really unsuccessful
- We haven't quite figured out how to spend budgets properly on Google Ads

_What impact was there on the primary metric or any secondary metrics?
We only had 21 clicks so hard to say if statistically significant, but for the ad our CPC went down massively from $3.35 to $1.10 _and_ our CTR increased from 6.58% to 10.77%. We definitely have a lot of room to improve this further however - I think 10.77% is still very low. 

None of the clicks however were for the new keywords, only for 'posthog' and variants. 

_What are the next steps based on the learnings of this experiment?_

Share this information with the PPC agency.
