### ISSUE TITLE
Ad artwork

### ISSUE THREAD

**Issue by corywatilo** [PostHog/meta#85]
We're going to be promoting a couple blog posts on Twitter this month:

- [What is a product engineer (and why they're awesome)](https://posthog.com/blog/what-is-a-product-engineer)
- [Master Feature Flags: Best practice, tips and examples](https://posthog.com/blog/feature-flag-best-practices)

It would be worth trying our Youtube-style thumbnail approach for these posts (to override the open graph image). We could:

a) get these up asap
b) put them up after a week, to benchmark CTR with the open graph images vs custom artwork we add

@charlescook-ph I think I'd lean toward the 2nd. Thoughts?

**Comment by charlescook-ph** [comment]
2nd sounds great!
