### ISSUE TITLE
Missing .md extension on two /requests-for-comments/ files

### ISSUE THREAD

**Issue by runofthemill** [PostHog/meta#91]
Hi there! 

While normally I'd open a PR to apply a fix, in this case it's probably way quicker for someone internal to do it since it's just file renaming :)

These two files don't have `.md` extensions and so GitHub doesn't render a preview/MD view when looking at them:
https://github.com/PostHog/meta/blob/main/requests-for-comments/2023-01-11-g2-automation
https://github.com/PostHog/meta/blob/main/requests-for-comments/resilient-feature-flags

Cheers :)

**Comment by corywatilo** [comment]
Nice catch, thanks!
