### ISSUE TITLE
RFC: Go all in on 'PostHog does that'

### ISSUE THREAD

**Issue by charlescook-ph** [PostHog/meta#92]
### Background

PostHog doesn't have a good, overarching tagline that people associate with us. We've had various contenders, varying from thought leader-y to fun to technical:

- The open source Product OS
- A suite of product and data tools. Built on the modern data stack.
- The modern platform for product analytics and experimentation
- PostHog is the single platform that can replace an entire suite of tools you’re already paying for.

[Coming soon](https://www.figma.com/proto/CLj2U34xpNiHuZRo73GJPm/posthog.com?page-id=4046%3A85573&node-id=6503%3A55935&viewport=-56683%2C-2479%2C1&scaling=min-zoom&starting-point-node-id=4138%3A110560&show-proto-sidebar=1) are things like:
- Built for builders
- Build products people want

Our propensity for writing catchy copy hooks means that we tend to come up with lots of nice one-liners, _but_ we haven't really committed to any in a consistent way except maybe 'Product OS'. 

### Proposal

_PostHog does that._

Why?

- It covers the all-in-oneness of PostHog, which is our number one differentiator (open source is number two)
- You can actually remember it
- It's way more fun to use in other contexts than the others lines we've tried:
  - Ads and product pages: 'Session recording? PostHog does that'; 'Host your data in the EU? PostHog does that'
  - Roadmap: 'PostHog doesn't do that - yet'
  - FAQ: 'Does PostHog do that?' 'Yes'
  - Future: this will be fun for video ads
- We used to have it on a t shirt and people liked it

Why not?

- Taglines don't make a difference for product-led growth/word of mouth, this is a distraction
- What is 'that'? Is it too vague? (Counterargument: Just Do It, Think Different, Don't Be Evil, )
- But PostHog doesn't do everything (yet)

### Places we'd need to update

If we agree on this, that is. I've probably missed stuff - feel free to add!

- [ ] Marketing
  - [ ] All paid ads where relevant
  - [ ] Twitter, LinkedIn etc. - anywhere we have a profile page
  - [ ] Any time we do a newsletter sponsorship
  - [ ] Whenever we post and it's relevant (e.g. sneak peek tweets)
- [ ] PostHog.com:
  - [ ] Home page
  - [ ] Product pages
  - [ ] Roadmap
  - [ ] Pricing 
  - [ ] Apps
  - [ ] FAQ

**Comment by joethreepwood** [comment]
My main counter arguments would be that 
- 'That' doesn't make it clear what we do, which is important when our product is technical and aimed at a specific user persona
- A variation of this _exact_ tagline has been discussed at the last two start-ups I worked at ('Scoro does that.' for time-tracking, invoicing, etc / 'Pollen does that' for free festival tickets, upgrades, experiences) so I don't feel it's very unique. Also very similar to 'There's an app for that'. 

Personally, while I wasn't a fan of 'Product OS' at launch, I think as our product continues to diversify we should lean into that as a category we can essentially create and fully own. 

That said, this is simple to implement and catchy enough that I don't have an ultra-strong feeling on it.

**Comment by andyvan-ph** [comment]
@charlescook-ph Could you post of our current creatives here for reference? I could do with some visual references for where we're at.

Some thoughts:

- I like "The Product OS built for builders" as a strapline. Could we consider this an alternative to the "The open source Product OS". Dropping 'open source' is a little controversial, I suppose, but it doesn't frame the Product OS concept at all. What's the closed-source Product OS? Answer. It doesn't exist, so the fact we're the open source one seems a bit redundant. We can get 'open source' in somewhere else.

- I think "PostHog does that" dovetails quite nicely with "The Product OS built for builders" and also leans into the [features, not benefits](https://posthog.com/blog/features-sell) credo. It's not super original, but sometimes simple works.

- Alternative: "Just use PostHog" – i.e. "Problem: Too many tools etc.. Solution: Just use PostHog." Again, plays into the all-in-oneness and I like the idea this is a thing people might actually say in a thread on r/productmanagement – i.e. "You could use Launch Darkly, Amplitude etc, but you're better off just using PostHog. It's 90% of what they do in one tool." 

Not advocating for this particularly over "PostHog does that", but figured it's worth throwing some alternatives around.

PS: Not relevant to this convo, but it does kind of remind me of the "Simpson did it" meme from South Park.

**Comment by charlescook-ph** [comment]
[(Most of) our current paid ads creative for reference](https://www.figma.com/file/gZkPcLJ9SmjYnKVPki2Ev4/PostHog---Client---10%2F2022?node-id=1042%3A2&t=2wlbnr68tr41AtQI-0)

**Comment by andyvan-ph** [comment]
> I obviously back this as I really want to add a 'PostHog does...' block to various pages on the website, not only would it explain what we do product wise but also as a company/ people -[ linked issue ](https://github.com/PostHog/posthog.com/issues/4622)

Looks good. In that context, it's less "does that" and more PostHog does "actual thing", which sounds good to me.

@charlescook-ph should we table "The Product OS built for builders" separately? Maybe "The Product OS for builders" is better? 🤷

**Comment by joethreepwood** [comment]
> @charlescook-ph Could you post of our current creatives here for reference? I could do with some visual references for where we're at.
> 
> Some thoughts:
> 
> * I like "The Product OS built for builders" as a tagline. Could we consider this an alternative to the "The open source Product OS". Dropping 'open source' is a little controversial, I suppose, but it doesn't frame the Product OS concept at all. What's the closed-source Product OS? Answer. It doesn't exist, so the fact we're the open source one seems a bit redundant. We can get 'open source' in somewhere else.
> * I think "PostHog does that" dovetails quite nicely with "The Product OS built for builders" and also leans into the [features, not benefits](https://posthog.com/blog/features-sell) credo. It's not super original, but sometimes simple works.
> * Alternative: "Just use PostHog" – i.e. "Problem: Too many tools etc.. Solution: Just use PostHog." Again, plays into the all-in-oneness and I like the idea this is a thing people might actually say in a thread on r/productmanagement – i.e. "You could use Launch Darkly, Amplitude etc, but you're better off just using PostHog. It's 90% of what they do in one tool."
> 
> Not advocating for this particularly over "PostHog does that", but figured it's worth throwing some alternatives around.
> 
> PS: Not relevant to this convo, but it does kind of remind me of the "Simpson did it" meme from South Park.

I'm not very much a fan of these and would back 'PostHog does that' more. 

I really don't think 'Built for builders' is as clear as we think it is.

**Comment by fuziontech** [comment]
Reminds me of one of my[ favorite Southpark episodes](https://en.wikipedia.org/wiki/Simpsons_Already_Did_It):
![](https://media2.giphy.com/media/l2SpKs2YVFuS1CzOU/200w.gif?cid=6c09b952cyycfpsg8cezmir9thsa661cgqdrvlf1z2g6zufx&rid=200w.gif&ct=g)
Very similar to, but the inverse of?:
![image](https://user-images.githubusercontent.com/391319/217359348-6eee71d9-b4dd-4780-a93e-dfb1bf280da6.png)

<img width="431" alt="image" src="https://user-images.githubusercontent.com/391319/217359423-7807cd8e-2eb9-4d58-8994-1f349b8af525.png">

My only worry is that it sounds a bit...basic. One of the strengths of Sentry's marketing is that it's kind of funny 'hah who hasn't had a phone drop on their face in bed' and kind of tells you what they do - 'ok they are used to fix stuff, but not sure what? But seems like it's for developers since a bunch of them are using it'. It's a pretty solid way of getting people to remember your brand just because of how the ad was somewhat cryptic. I'm not sure 'PostHog does that' is that clever or memorable unless they looked into us and literally found out we do everything they are looking for, maybe that is true?!

Something like
'Happy users. Happy life.' would be a good one
'Happy users. Happy ARR' lol IYKYK
'Happy users. Happy growth.'

For the record I do like it for the site - it conveys that we are more than just product analytics, but I worry that if we went in 100% it would hurt us from an SEO and new customer perspective...it could also hurt us from a focus perspective as well.
“Startups don’t starve; they drown.”
