### ISSUE TITLE
Messaging: K8s Sunsetting Email Campaign

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#93]
We've started to sunset K8s on PostHog, with May 31st as the cut-off. I'm preparing an email campaign to encourage migrations to Cloud as a result. 

### **Proposed dates and actions:**

- Email on Mon 3rd April with upsell message focusing on the benefits of Cloud
- Email on Mon May 1 with content focused on what users who don't migrate will lose
- Email on Mon May 24 with one week warning, to add urgency
- Email on Thurs Jun 1 with a farewell to unmigrated users

The emails will be sent from Customer.io, with an automated campaign which targets all self-hosted users. The campaign checks before each send whether the recipient exists in either the US or EU Cloud segments. If they do, they do not receive emails. I've compiled the emails into a single campaign with appropriate delays, to simplify sending processes. 

### **Preview of emails**
**First email**
<img width="817" alt="Screenshot 2023-02-13 at 14 57 43" src="https://user-images.githubusercontent.com/84011561/218492342-9cd2d7ba-9600-451c-8d93-8442d6fe070b.png">

**Second email**
<img width="827" alt="Screenshot 2023-02-13 at 14 58 18" src="https://user-images.githubusercontent.com/84011561/218492516-d86cbb5f-7ad8-4bc0-8470-162f06a474f3.png">

**Third email**
<img width="817" alt="Screenshot 2023-02-13 at 14 58 46" src="https://user-images.githubusercontent.com/84011561/218492645-37e37f92-9aad-454c-8cf1-43534f7b6514.png">

**Final email**
<img width="818" alt="Screenshot 2023-02-13 at 14 59 56" src="https://user-images.githubusercontent.com/84011561/218492954-9edfb2a5-ca08-48ef-a87d-42ecc6b65335.png">

**Feedback welcome**

**Comment by tiina303** [comment]
I'm not sure about them losing new features and bug fixes. We won't be providing upgrade paths (so it can be a hassle to make everything work), but they can probably still use the latest image same as docker compose users.

**Comment by joethreepwood** [comment]
I've now expanded this campaign to include Open Source users too, after chatting with @simfish85
