### ISSUE TITLE
Art Request - Banners & Logos for new newsletter

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/meta#95]
We're planning to launch a new newsletter called 'Product for Engineers' the strapline for which is:

> "A newsletter by PostHog for engineers and founders who want to flex their product muscles 💪 "

It'll be launched / hosted on Substack, which requires a few different bits of art / branding.

1. A 1100 x 220 email banner image that appears at the top of each email. 
2. A 600 x 600 cover photo that would appear on a signup page
3. A 300 x 300 smaller logo for user in the Substack app / other places

It probably makes sense to start with the 1100 x 220 banner and work from there. Here's an example of what one of these looks like IRL:

![Screenshot 2023-02-15 at 17 30 28](https://user-images.githubusercontent.com/92976667/219107252-d9a2e764-3f56-4414-9155-629140de0b84.png)

Considerations:

- The newsletter is specifically targeted at engineers and technical founders

- It needs to include the 'Product for Engineers' as the title

- Ideally, I'd like to include a line like "A newsletter from PostHog, the open-source Product OS" or maybe just "A newsletter from PostHog" in the banner for brand awareness, but we could live without this.

Ideas:

- Could we riff off the "swol hog" and the "flex their product muscles" somehow? Like a shirt bursts open to reveal "Product" written on the hedgehog's chest / on a vest, or something. Something to play around with.

### Timing

**In the next two weeks** is a realistic launch window, though it could end up being three weeks depending on content.

**Comment by lottiecoxon** [comment]
Okay soooo as per request, I have created some interesting banners that I'm sure no other company would dare to post (hehe) 

OPEN for feedback !!

File is [here](https://www.figma.com/file/HwUmk7WqccLkGgNNGAs4zN/Art-board?node-id=10059%3A57205&t=3YA83FjxGRgVbPSN-1)

![Image](https://user-images.githubusercontent.com/65415371/220687645-e2bbe6bb-fab6-461a-8413-ba962028d88c.png)

**Comment by charlescook-ph** [comment]
omg I'm dying, this is the best thing I've ever seen

**Comment by andyvan-ph** [comment]
Random thoughts:

- We go with singular 'muscle' as Cory suggested on Slack as it matches up with the art
- Maybe swap out the cog tattoo with the GitHub logo, or something similar?
- Question for others: I was thinking it would be fun to some kind of coding gag tattoo on the other peck, but I have no idea what that would be. Suggestions welcome.

**Comment by andyvan-ph** [comment]
Thanks again for your awesome work, Lottie and Cory for the assist. Closing.
