### ISSUE TITLE
Onboarding: Splitting Hosted and Cloud campaigns

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#97]
### **What's the problem?**
The onboarding flow currently mostly directs users to resources on the site, such as tutorials. We do this in part because we cannot direct users to specific parts of the app, because we have to accomodate for self-hosted users and cannot predict their URL. In some cases ([for example](https://github.com/PostHog/posthog/issues/14257#issuecomment-1434446882)) this means we direct people to odd places.

We can fix that.

### **What's the change?**
I'm going to split the onboarding flow into three variants -- one for US Cloud users, one for EU Cloud users, and one for self-hosted users. 

Links in the self-hosted campaign will remain basically as they are now. We'll, for example, direct people to resources about feature flags when we discuss feature flags. 

Links in the Cloud campaigns will direct to the apps instead, enabling us to push users more directly to the features we want them to engage with. We'll continue to push the resources as secondary CTAs. 

### What benefit will this have?

Obviously this will mean we're pushing people back into the app, promoting better engagement. 

Additionally, we could _potentially_ build this into an app experience -- so that users arriving in the app from these links will be served onboarding content _within the app_ that drives further engagement. But that's just an idea for now.

**Comment by joethreepwood** [comment]
OK, I have now set up three campaigns. 

### Cloud Onboarding
This is the same as it was before, albeit focused on Cloud (EU and US) users and with a few extra language and link tweaks to send users to better resources. 

### Self-hosted Onboarding
We're sunsetting, so this is mainly redundant. However, it is mostly the same as the Cloud workflow, with a few changes to accomodate the self-hosted experience (e.g. not sending users to app.posthog.com)

### Open Source Onboarding
This is a very small segment and I've shortened it to two emails only. 
- The first is an adapted version of the welcome email that is also seen in the other campaigns. 
- After two weeks, we send a follow-up email which upsells users to Cloud and uses content similar to our sunsetting messages. See that message below.  

<img width="647" alt="Screenshot 2023-02-21 at 15 28 20" src="https://user-images.githubusercontent.com/84011561/220387682-3c3c85b6-0d57-41b8-8c96-1731b2c06558.png">

**Comment by charlescook-ph** [comment]
For the open source onboarding, is that for people on the Docker Compose version? If so, probably the biggest appeal of Cloud is the scalability? I'd swap that in for 'less cost' given the open source version is already free! (Unless we're going to start wiring them money...)

**Comment by joethreepwood** [comment]
<img width="635" alt="Screenshot 2023-02-21 at 18 15 20" src="https://user-images.githubusercontent.com/84011561/220426567-3d9380b2-1d41-40ae-98ca-55d878a9875c.png">
